### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by weirongxu** [weirongxu/coc-explorer#1]

**Comment by weirongxu** [comment]
![image](https://user-images.githubusercontent.com/1709861/64406207-d43cf980-d0b3-11e9-8167-71b9c6adcf2f.png)

**Comment by weirongxu** [comment]
![image](https://user-images.githubusercontent.com/1709861/64673276-49d40b80-d4a0-11e9-95d0-9744febd7da0.png)

**Comment by weirongxu** [comment]
![image](https://user-images.githubusercontent.com/1709861/64966850-1e9f5100-d8d2-11e9-9490-438c6d1cf378.png)

**Comment by giovannigiordano** [comment]
Hi, how can i configure the icon set to use?

**Comment by weirongxu** [comment]
> Hi, how can i configure the icon set to use?

Install [nerdfont](https://www.nerdfonts.com/) and add `"explorer.icon.enableNerdfont": true` to you coc-settings.json

**Comment by weirongxu** [comment]
> Hi, how can i configure the icon set to use?

Custom icon set are not support now

**Comment by ovidius72** [comment]
Hi, is it possibile to have the buffers expanded by default and have a command that focus the explorer tree at the current file (like NerdTreeFocus)  ?
I've tried with --reveal but couldn't figure out what path need to be added at the end.

**Comment by iamcco** [comment]
@ovidius72 
try this mapping
```
" coc-explorer
noremap <silent> <leader>e :execute 'CocCommand explorer' .
      \ ' --toggle' .
      \ ' --sources=buffer+,file+' .
      \ ' --file-columns=git,selection,icon,clip,indent,filename,size --reveal ' . expand('%:p')<CR>

```

**Comment by ovidius72** [comment]
> @ovidius72
> try this mapping
> 
> ```
> " coc-explorer
> noremap <silent> <leader>e :execute 'CocCommand explorer' .
>       \ ' --toggle' .
>       \ ' --sources=buffer+,file+' .
>       \ ' --file-columns=git,selection,icon,clip,indent,filename,size --reveal ' . expand('%:p')<CR>
> ```

Wonderful. Thanks a lot. The buffers list anyway is not open by default.

**Comment by iamcco** [comment]
It's weird, it's default open for me.

**Comment by ovidius72** [comment]
Something was wrong with my configuration. It works. Thanks a lot.

**Comment by weirongxu** [comment]
![image](https://user-images.githubusercontent.com/1709861/76720090-c5c44e80-6776-11ea-88eb-100a39066a17.png)

![image](https://user-images.githubusercontent.com/1709861/76720263-471be100-6777-11ea-82c1-614627097b02.png)

**Comment by weirongxu** [comment]
Moved to https://github.com/weirongxu/coc-explorer/wiki/Screenshot
