### ISSUE TITLE
[Question] Integration with Startify

### ISSUE THREAD

**Issue by alex-popov-tech** [weirongxu/coc-explorer#100]
I have current setup as Startify + NerdTree as following:
1.  when save session, do not save explorer buffer https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L39
2. if the only window opened is nerdtree - close it https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L58
3. on start - open startify screen - open nerd tree - focus startify buffer - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L138

with that i'm able to open files/sessions from startify screen or nerdtree and all will work as expected (no errors, sessions saved without nerdtree buffer etc.)

I want to fully replace nerdtree with coc-explorer, but i'm not sure about:
1.  how to avoid saving coc-explorer buffer ? https://share.getcloudapp.com/geu2koOv
2. how to auto-close coc-explorer if that the only buffer opened? 
3. i figered on how to start coc-explorer automatically on startup, but i would like to start it without focusing buffer - is that possible?

**Comment by weirongxu** [comment]
Moved to #120 and #121 

For question 1, I can't see the explorer buffer save in startify mru and coc-lists mru

**Comment by yatli** [comment]
@weirongxu the buffer would not show up in mru, but will be saved in a session.
the explorer won't be properly restored on session load:

![image](https://user-images.githubusercontent.com/20684720/90983858-dd182b00-e5a3-11ea-86f8-eb8fa40870cf.png)

**Comment by weirongxu** [comment]
@yatli 
> @weirongxu the buffer would not show up in mru, but will be saved in a session.
> the explorer won't be properly restored on session load:
> 
> ![image](https://user-images.githubusercontent.com/20684720/90983858-dd182b00-e5a3-11ea-86f8-eb8fa40870cf.png)

It appear every time? Seems I didn't have explorer saved in the session

**Comment by yatli** [comment]
Yes. I use Startify to auto save my sessions. Every time I forgot to manually close the explorer window on `:wq`, the next time a blank window is presented.

**Comment by weirongxu** [comment]
@yatli 
> Yes. I use Startify to auto save my sessions. Every time I forgot to manually close the explorer window on `:wq`, the next time a blank window is presented.

Remove `blank` from your `sessionoptions` options.

**Comment by yatli** [comment]
aww nice!
