### ISSUE TITLE
confilct with Yggdroot/indentLine

### ISSUE THREAD

**Issue by physicistgeng** [weirongxu/coc-explorer#101]
when let g:indentLine_showFirstIndentLevel =1, open coc-explorer close it and reopen it, the indent will be entirely wrong.

**Comment by reisnobre** [comment]
You should add this line to your config.
coc-explorer doesn't work well with indentLine.

`let g:indentLine_fileTypeExclude=['coc-explorer']`

**Comment by physicistgeng** [comment]
thank, it works fine now.
