### ISSUE TITLE
[Feature Request]: Floating window border and custom background highlight support

### ISSUE THREAD

**Issue by iamcco** [weirongxu/coc-explorer#103]
It would be great to have border and custom background support.

![image](https://user-images.githubusercontent.com/5492542/74940841-05747080-542d-11ea-8829-185c6e070b03.png)

**Comment by kuntau** [comment]
Sorry to hijack this.. How do you have file preview? or that isn't coc-explorer?

**Comment by weirongxu** [comment]
> Sorry to hijack this.. How do you have file preview? or that isn't coc-explorer?

I think that is [vim-clap](https://github.com/liuchengxu/vim-clap)

**Comment by kuntau** [comment]
Ahhh that's junngunn/fzf, I just realized it already have file preview support now.

**Comment by weirongxu** [comment]
I have added this feature. check out the `explorer.floating.border.chars`, and highlights wiki https://github.com/weirongxu/coc-explorer/wiki/Highlight

**Comment by sangdth** [comment]
I try the highlight and `explorer.floating.border.chars` but seems like it does not work.

<img width="1464" alt="Screenshot 2021-01-20 at 20 02 53" src="https://user-images.githubusercontent.com/1083478/105215877-8581e980-5b5a-11eb-9c64-67ff011a6953.png">
