### ISSUE TITLE
Unknown functon coc_explorer#command#generate

### ISSUE THREAD

**Issue by alex-popov-tech** [weirongxu/coc-explorer#104]
when trying to use example from readme - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L198
getting error
```
Error detected while processing /Users/alexanderpopov/.config/nvim/plugins.vim:
line  200:
E117: Unknown function: coc_explorer#command#generate
E15: Invalid expression: coc_explorer#command#generate({ 'toggle': v:true, 'file-child-template': '[git | 2] [selection | clip | 1] [indent][icon | 1] [filename growRight 1 omitCenter 1][modif
ied]', 'file-child-labeling-template': '[fullpath][size][modified][readonly]', }, '/root/path')
```

**Comment by weirongxu** [comment]
The function command#generate example is not very good, I will consider another better solution

**Comment by alex-popov-tech** [comment]
@weirongxu can you please provide any example on how to configure explorer now then? I see you changed the way i should pass args to explorer, but I can't find an example on how to do that now

**Comment by weirongxu** [comment]
1. Use `coc-settings.json` to change the file template.

2. Use execute command like `coc_explorer#command#generate`
```
let cmd = "CocCommand explorer --file-child-labeling-template =". fnameescape (value). "--file-child-template =". fnameescape (value)
nmap <leader>e :execute cmd<CR>
``` 

3. Copy `coc_explorer#command#generate` to your vimrc and rename the function name

https://github.com/weirongxu/coc-explorer/blob/master/autoload/coc_explorer/command.vim

**Comment by weirongxu** [comment]
But I'll add a `g: coc_explorer_presets` variable to give the user a choice directly in the `CocList explorerPresets`, and it can be called by `CocComand explorer --preset preset1`

e.g.
```vim
let g:coc_explorer_presets = {
\   "preset1": {
\      "root-path": '',
\      "file-child-template": '',
\      "position": "floating", 
\   }
\ }
```

**Comment by alex-popov-tech** [comment]
@weirongxu waiting for that feature, thanks!

**Comment by alex-popov-tech** [comment]
@weirongxu can you please make a release to make this feature available?

**Comment by weirongxu** [comment]
@alex-popov-tech Released
