### ISSUE TITLE
cannot open file

### ISSUE THREAD

**Issue by onichandame** [weirongxu/coc-explorer#107]
# problem
when a file is selected to edit(using 'e' or 'E') from the explorer, a directory list of C:\ is opened instead of the file.
![屏幕截图(13)](https://user-images.githubusercontent.com/23728505/75026704-61e09a00-54d8-11ea-9872-5cb804f18144.png)
# diagnostic message
:message
```
[coc.nvim] Error: request error nvim_command - Vim(normal):E20: Mark not set
```
:CocInfo
```
## versions

vim version: NVIM v0.4.3
node version: v13.9.0
coc.nvim version: 0.0.74-c57062d0da
term: vtpcon
platform: win32

## Messages
[coc.nvim] Error: request error nvim_command - Vim(normal):E20: Mark not set
## Output channel: explorer

Error: request error nvim_command - Vim(normal):E20: Mark not set
    at C:\Users\iaint\AppData\Local\nvim\plugged\coc.nvim\build\index.js:14222:32
    at NvimTransport.parseMessage (C:\Users\iaint\AppData\Local\nvim\plugged\coc.nvim\build\index.js:10826:17)
    at DecodeStream.<anonymous> (C:\Users\iaint\AppData\Local\nvim\plugged\coc.nvim\build\index.js:10796:18)
    at DecodeStream.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (C:\Users\iaint\AppData\Local\nvim\plugged\coc.nvim\build\index.js:13746:12)
    at DecodeBuffer.flush (C:\Users\iaint\AppData\Local\nvim\plugged\coc.nvim\build\index.js:12736:12)
```

# environment
- **OS:** Windows 10 Pro 18363.657
- **nvim:** 0.4.3(with node v13.9.0, python v3.6.1 and pynvim v0.4.1)

Coc and coc-explorer have been re-installed using Vim-Plug and `CocInstall` so the latest version is installed.

# my guess
I have no idea about the cause as it just suddenly appeared today. I don't recall that I have touched init.vim or install/uninstall/update coc plugins and nvim plugins manually for at least 2 days.

I have googled for a couple of hours but found nothing. Hence I guess it may be a new bug.

**Comment by onichandame** [comment]
just add for notice. When I try to open a file using 'e' or 'E' from the explorer, a swap file called 'C%%.swp' is created. I am not sure whether it is caused by the opened C:\ directory list or the bug itself.

**Comment by weirongxu** [comment]
Later I will test it on windows

**Comment by cbusenbu** [comment]
This is still an issue, I have tested it on two machines with a recent update to coc-explorer this occurs on Windows where a file goes to C:

**Comment by cbusenbu** [comment]
I have a strong suspicion this came through with v0.3.0 or v0.3.1

**Comment by weirongxu** [comment]
@cbusenbu Released now

**Comment by cbusenbu** [comment]
Coolio, thanks a ton friend!

**Comment by onichandame** [comment]
@weirongxu thx. I can confirm that the bug has been fixed in the latest release.

just for curiosity, how did you start developing coc extensions? I have been trying to search for dev documentation but nothing useful is found. Could you kindly point me to the article/API docs/template repository/etc that you find useful?

**Comment by weirongxu** [comment]
> @weirongxu thx. I can confirm that the bug has been fixed in the latest release.
> 
> just for curiosity, how did you start developing coc extensions? I have been trying to search for dev documentation but nothing useful is found. Could you kindly point me to the article/API docs/template repository/etc that you find useful?

First of all, use `vim-plug` install the local extension like this
```vim
Plug 'path/to/coc-explorer'
```

Related Wiki
* https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension
* https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim#use-chrome-developer-tools

In first, I read the vscode API, and then research the difference between `coc.nvim` and `vscode` via `coc-tsserver`

https://code.visualstudio.com/api/references/vscode-api

BTW, There is a script to create coc extension https://github.com/fannheyward/create-coc-extension

**Comment by onichandame** [comment]
@weirongxu thx. you rock!

**Comment by weirongxu** [comment]
@onichandame 
The coc.nvim created also writes some articles, you can take a look
https://github.com/neoclide/coc.nvim#articles
