### ISSUE TITLE
是否支持coc-bookmark 插件？？ 

### ISSUE THREAD

**Issue by solly0880** [weirongxu/coc-explorer#108]
装完coc-bookmark 插件后，打开coc-explorer 好像没有显示。是需要设置？还是不支持显示bookmark，大佬？

**Comment by weirongxu** [comment]
还没有支持的

**Comment by weirongxu** [comment]
@voldikss 有什么建议吗?

**Comment by voldikss** [comment]
要支持的话你是想怎么支持呢 @solly0880 ？如果要是在文件树的那一列里面增加个数字，那我觉得其实也用处不是很大，有什么典型用例吗？

**Comment by solly0880** [comment]
-[BUFFER]
   1. plugin.vim
   2. init.vim
-[BOOKMARK]
   plugin.vim line: 83
   general.vim line:13
   <filename> line : <number>
-[FILE]
  xxx 
  xxx

@voldikss  看这种形式行不

**Comment by voldikss** [comment]
还有就是我之前并没有写将 bookmark 数据导出的部分，现在写也没头绪。况且我觉得 coc-bookmark 用户并不多，所以受众少的话做这个没有什么用处

**Comment by solly0880** [comment]
这种协同作战的机会，可以尝试下啊。。

**Comment by voldikss** [comment]
> 没准别个看了 coc-explorer 里面带bookmark 功能 就会去装你的插件也有可能。。

emmm 我不是这个意思的，我的意思是说用处不大；而且最近没精力了，荒废好多天了已经（o´・ェ・｀o）。

**Comment by weirongxu** [comment]
> -[BUFFER]
> 1.plugin.vim
> 2.init.vim
> -[BOOKMARK]
> plugin.vim line: 83
> general.vim line:13
> <filename> line : <number>
> -[FILE]
> xxx
> xxx
> 
> @voldikss 看这种形式行不

这格式看起来和 CocList 区别不是很大

**Comment by solly0880** [comment]
> > 没准别个看了 coc-explorer 里面带bookmark 功能 就会去装你的插件也有可能。。
> 
> emmm 我不是这个意思的，我的意思是说用处不大；而且最近没精力了，荒废好多天了已经（o´・ェ・｀o）。

从要从一只蝙蝠说起。。。

**Comment by solly0880** [comment]
> > -[BUFFER]
> > 1.plugin.vim
> > 2.init.vim
> > -[BOOKMARK]
> > plugin.vim line: 83
> > general.vim line:13
> >  line : 
> > -[FILE]
> > xxx
> > xxx
> > @voldikss 看这种形式行不
> 
> 这格式看起来和 CocList 区别不是很大

是不大。。能直接从:CocList bookmark 里面去取吗。。

**Comment by weirongxu** [comment]
> 是不大。。能直接从:CocList bookmark 里面去取吗。。

不能的，需要有 API。

实现这个功能的意义不大，体验和 CocList 差不多。
优先做其他特性，以后再考虑

**Comment by bitterjug** [comment]
```
-[BUFFER]
1.plugin.vim
2.init.vim
-[BOOKMARK]
plugin.vim line: 83
general.vim line:13
<filename> line : <number>
-[FILE]
xxx
xxx
```
This looks like a great addition (I.e. I use bookmarks a lot in Nerdtree and want to be able to switch) how did this issue get resolved?

**Comment by weirongxu** [comment]
> This looks like a great addition (I.e. I use bookmarks a lot in Nerdtree and want to be able to switch) how did this issue get resolved?

It is can't until `coc-explorer` can support external API to create a source

**Comment by bitterjug** [comment]
Thanks for explanation. :+1:

**Comment by voldikss** [comment]
@weirongxu @solly0880 Could we reopen this issue? I would like to add bookmark support for coc-explorer.

**Comment by weirongxu** [comment]
Sure, but I haven’t considered how to support it.

**Comment by voldikss** [comment]
I am working on this for two days. The basic functions has been implemented(here is the overview).

![image](https://user-images.githubusercontent.com/20282795/84349701-744b2480-abea-11ea-9757-b93c3811676a.png)

I made coc-explorer read the bookmarks data stored at `$XDG_CONFIG_HOME/coc/extensions/coc-bookmark-data/bookmark.json` and display them in the top of explorer sidebar.
