### ISSUE TITLE
Compact Middle Packages

### ISSUE THREAD

**Issue by BodneyC** [weirongxu/coc-explorer#109]
More of a feature request than anything.

Would it possible to be able to collapse directories with only one directory inside?

So, instead of:

```
com
└ company
  └ some
    └ package
      └ name
        └ file.kt
```

It would be:

```
com / company / some / package / name
└ file.kt
```

I'm currently doing quite a few JVM-ish projects and with the former you lose a lot of screen real estate.

If this is already an option and I've missed it, I apologise.

Thanks for any comment you have.

**Comment by weirongxu** [comment]
This feature is similar to vscode, but first I need to think about how to operate it under vim.

**Comment by BodneyC** [comment]
Cracking, thanks for taking a look. Great extension either way

**Comment by weirongxu** [comment]
The result of first expand

![image](https://user-images.githubusercontent.com/1709861/81802850-6356b700-9549-11ea-97c8-d54ef60fcb70.png)

Expand again

![image](https://user-images.githubusercontent.com/1709861/81802939-884b2a00-9549-11ea-900d-369244280231.png)

**Comment by BodneyC** [comment]
That's spot on, thanks for getting round to this
