### ISSUE TITLE
explorer.icon.enableVimDevicons don't work

### ISSUE THREAD

**Issue by PetrusZ** [weirongxu/coc-explorer#110]
Set explorer.icon.enableVimDevicons true or false, don't have any different.

My config:
```json
  "explorer.icon.enableNerdfont": true,
  "explorer.icon.enableVimDevicons": true,
  "explorer.sources": [
      {
          "name": "buffer",
          "expand": true
      },
      {
          "name": "file",
          "expand": true
      }
  ]
```

Screenshot:
![image](https://user-images.githubusercontent.com/4990592/75096732-5e830680-55dd-11ea-82da-f851f5fac764.png)

**Comment by PetrusZ** [comment]
After restart computer, icons change to VimDevicons ...

**Comment by weirongxu** [comment]
This screenshot looks like the icon of devicons, because the text icon is only exists in devicons.

![image](https://user-images.githubusercontent.com/1709861/75104516-eea86680-5644-11ea-9bc7-101999c4ac02.png)

**Comment by PetrusZ** [comment]
Thank you ... I didn't notice the details.
