### ISSUE TITLE
can not click by mouse 

### ISSUE THREAD

**Issue by swloki** [weirongxu/coc-explorer#112]
can not click by mouse

**Comment by weirongxu** [comment]
No support yet

**Comment by motephyr** [comment]
Try it?
  "explorer.keyMappings": {
    "<2-LeftMouse>": ["expandable?", "expandOrCollapse", "open"]
  },

**Comment by swloki** [comment]
> Try it?
> "explorer.keyMappings": {
> "<2-LeftMouse>": ["expandable?", "expandOrCollapse", "open"]
> },
it works,thank you very much

**Comment by swloki** [comment]
@motephyr it works thank you very much
