### ISSUE TITLE
Removed default shortcuts have no effect

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#114]
I configured my own shortcuts in coc-settings.json. For example, I deleted the shortcut `a`, but it still works.

**Comment by weirongxu** [comment]
Have you tried this?
```jsonc
"explorer.keyMappings": {
     "a": "unmap"
}
```

**Comment by weirongxu** [comment]
Also, you can set `explorer.keyMappingMode` to `none` to cancel all default mapkeys

**Comment by fgheng** [comment]
thank You very much, it works
