### ISSUE TITLE
[Feature Request] Add function list source

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#115]
Would you like to add a source of  function list to show functions, variables, etc. These info can be get from language server.
sure, if we do hover on the function or variable there will be a float window to show detail info or context of it.

**Comment by weirongxu** [comment]
I'm still using `vista.vim`, until git and ssh sources are done. Might consider creating extensions like coc-expl-outline, coc-expl-npmscripts, etc...

**Comment by fgheng** [comment]
thank you very much
