### ISSUE TITLE
[question] Some custom keymap cannot be used

### ISSUE THREAD

**Issue by qiuyue77** [weirongxu/coc-explorer#118]
I'd customed coc-explorer keymap in `coc-settings.json` ,but when I use `:CocCommd explorer` in nvim, I found some custom keymap can not be used, and other custom keymap can be used.
This is the screenshot from coc-explorer(left picture shown) and coc-setting.json(right picture shown).
The problematic is in the red circle.
![ExplorerAndCocsetting](https://user-images.githubusercontent.com/25001635/75599336-d7eb8f00-5ade-11ea-8dcf-1f8d635f2b5c.png)

I checked it that there is no conflict with keymappings
Does it lack depends?

**Comment by weirongxu** [comment]
`openInVsplit` is deprecated. Use `open:vsplit`. more information in readme.

**Comment by qiuyue77** [comment]
Thanks, it does work. This is my careless.  But the  problematic mapkey did work few days ago, before I changed some other coc.nvim configuration.
