### ISSUE TITLE
Find file & Open when `nvim .`

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [weirongxu/coc-explorer#119]
Hello,

First of all, thank you very coc-explorer is super good.

I have a couple of questions:

1. By default coc-explorer focuses on the buffer in use unless the buffer is in a hidden directory, is there a way to make it work with hidden directories too? or something along the lines of find file in explorer?

2. Is it possible to have something similar to find file in tree which would take us to the home directory of the buffer that is currently open in the tree? this is in case I'm in dir: /my/code but I opened /my/config/init.nvim with shortcut. when I open the explorer it still opens the current dir and I would like it to take me to the directory of the current buffer no matter what.

2. Is there a way to get coc-explorer to open by default when `vim .` is executed in a directory? currently it netrw opens.

Cheers!
Alaa

**Comment by weirongxu** [comment]
These features are not supported yet, I have moved them to other issues, #122, #81, #123
