### ISSUE TITLE
Explorer not found when installed using repo format

### ISSUE THREAD

**Issue by kuntau** [weirongxu/coc-explorer#124]
> `[coc.nvim] Command: explorer not found`

The error I got when installing using `Plug` but when installing using `CocInstall` it work just fine. I haven't test using other plugins manager but I guess would be the same.

**Comment by weirongxu** [comment]
How did you use the Plug command?

**Comment by kuntau** [comment]
Just the plain `Plug 'weirongxu/coc-explorer'`

**Comment by weirongxu** [comment]
Check out this https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension
