### ISSUE TITLE
The floating window steals the focus

### ISSUE THREAD

**Issue by wookayin** [weirongxu/coc-explorer#127]
When navigating the coc-explorer window using `j`, `k`, etc., sometimes a floating window displaying fullpath, access time, etc. still the focus. There is no reason to automatically move the cursor/focus onto the floating window. I wonder this is a bug?

Another question: how to disable the floating window completely?

**Comment by weirongxu** [comment]
> When navigating the coc-explorer window using j, k, etc., sometimes a floating window displaying fullpath, access time, etc. still the focus. There is no reason to automatically move the cursor/focus onto the floating window. I wonder this is a bug?

Maybe a bug, but I can't reproduce it. Please provide `:CocInfo`

> Another question: how to disable the floating window completely?

Use `explorer.previewAction.onHover`
