### ISSUE TITLE
Question: Map `<cr>` to "expandOrCollapse or open"?

### ISSUE THREAD

**Issue by wookayin** [weirongxu/coc-explorer#128]
The default behavior of `<CR>` is to open the directory or file. However, I would like to have it mapped to `expandOrCollapse` **for directories** and `open` (default) **for files**. How can I achieve this?

Please note that is the behavior NERDTree has.

**Comment by weirongxu** [comment]
```jsonc
{
  "<cr>": ["expandable?", "expandOrCollapse", "open"]
}
```

**Comment by AxelJunker** [comment]
`expandOrCollapse` is deprecated. I used `[
      "expandable?",
      ["expanded?", "collapse", "expand"],
      "open"
    ]` instead (same as double clicking left mouse).
