### ISSUE TITLE
[coc.nvim] Error: request error nvim_win_close - Invalid window id

### ISSUE THREAD

**Issue by physicistgeng** [weirongxu/coc-explorer#131]
## Messages
[coc.nvim] Error: request error nvim_win_close - Invalid window id
## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /Users/xxxx/.config/nvim
resolved root: /Users/xxxx/.config/nvim
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/xxxx/.config/nvim
> git ls-files -- init.vim
resolved root: /Users/xxxx/.config/nvim
resolved root: /Users/xxxx/.config/nvim
> git symbolic-ref --short HEAD
> git ls-files -- init.vim
resolved root: /Users/xxxx/.config/nvim
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :init.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :init.vim
> git diff /Users/xxxx/.config/nvim/init.vim
> git diff /Users/xxxx/.config/nvim/init.vim
resolved root: /Users/xxxx/.config/nvim
resolved root: /Users/xxxx/.config/nvim
> git symbolic-ref --short HEAD
> git ls-files -- init.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :init.vim
> git diff /Users/xxxx/.config/nvim/init.vim
resolved root: /Users/xxxx/.config/nvim
resolved root: /Users/xxxx/.config/nvim
> git symbolic-ref --short HEAD
> git ls-files -- init.vim
> git --no-pager show :init.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git diff /Users/xxxx/.config/nvim/init.vim
resolved root: /Users/xxxx/.config/nvim
resolved root: /Users/xxxx/.config/nvim
> git symbolic-ref --short HEAD
> git ls-files -- init.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :init.vim
> git diff /Users/xxxx/.config/nvim/init.vim

## Output channel: explorer

Error: request error nvim_win_close - Invalid window id
    at /Users/xxxx/.local/share/nvim/plugged/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (/Users/xxxx/.local/share/nvim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (/Users/xxxx/.local/share/nvim/plugged/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at DecodeStream.Readable.push (_stream_readable.js:224:10)
    at DecodeStream.Transform.push (_stream_transform.js:150:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/xxxx/.local/share/nvim/plugged/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (/Users/xxxx/.local/share/nvim/plugged/coc.nvim/build/index.js:12757:12)

## Output channel: translator

please help me.

**Comment by weirongxu** [comment]
What did you do before this error occurred?

**Comment by axrt** [comment]
I have the exact same thing. The easiest way to reproduce would be to open coc-explorer and select a file with "L". If it does not occur the first time, you may try to jump back and forth between the explorer and file panes.
The output chanels are virtually the same as above.
Thanks!
