### ISSUE TITLE
how can i get the most outside indentline like in the figure below

### ISSUE THREAD

**Issue by physicistgeng** [weirongxu/coc-explorer#133]

**Comment by physicistgeng** [comment]
<img width="330" alt="截屏2020-03-17下午11 03 13" src="https://user-images.githubusercontent.com/50125230/76870037-21d8c100-68a4-11ea-8e7f-41147558f34d.png">

**Comment by weirongxu** [comment]
`explorer.file.column.indent.indentLine`

**Comment by physicistgeng** [comment]
actually i have explorer.file.column.indent.indentLine=true in my coc-setting.json. But I still can have the  first level indentline which is marked by red in the figure below.

<img width="830" alt="截屏2020-03-18下午9 57 43" src="https://user-images.githubusercontent.com/50125230/76968291-a0486800-6963-11ea-8926-9edd921a8be1.png">

**Comment by weirongxu** [comment]
This indentline has been removed because it takes up space.

**Comment by physicistgeng** [comment]
okay，thank you
