### ISSUE TITLE
[Feature Request] Please support open coc-explorer in current window.

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#136]
Hello, would you like to add this feature? open coc-explorer in current window just like ranger.vim, thank you very much.
![Peek 2020-03-24 12-16](https://user-images.githubusercontent.com/50551377/77387689-10724600-6dc9-11ea-8ec9-f6d716b5e97a.gif)

**Comment by fgheng** [comment]
or like this
![image](https://user-images.githubusercontent.com/50551377/77388821-25040d80-6dcc-11ea-931f-0cc19b6605ac.png)

**Comment by weirongxu** [comment]
How about to use floating window?

```vim
let g:coc_explorer_global_presets = {
\   'floating': {
\      'position': 'floating',
\   },
\ }

nmap <space>e :CocCommand explorer --preset floating<CR>
```

// settings.json
```json
{
  "explorer.previewAction.strategy": "sourceWindow",
}
```

I have a little busy recently, the border feature has not been implemented yet
https://github.com/weirongxu/coc-explorer/issues/103

**Comment by fgheng** [comment]
yes, thank you very much
