### ISSUE TITLE
Property explorer.file.columns is not allowed

### ISSUE THREAD

**Issue by horseinthesky** [weirongxu/coc-explorer#137]
Haven't check my settings for a while. Now I see I cannot set up a list of desired columns:
![image](https://user-images.githubusercontent.com/19948672/78216899-91b19300-74c3-11ea-9611-7912c4413091.png)

Getting an error of:
```
Property explorer.file.columns is not allowed.  
```

How should I set this up now?

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer#--file-child-template-template

https://github.com/weirongxu/coc-explorer#template-grammar
