### ISSUE TITLE
[Feature Request]: Toggles to show only buffers for this tab or not

### ISSUE THREAD

**Issue by sainnhe** [weirongxu/coc-explorer#14]
When I was thinking about the difference between tab and buffer, I saw this question on stackoverflow: [Why do Vim experts prefer buffers over tabs?](https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs)

Someone said

> "Vim experts" don't prefer buffers over tabs: they use buffers as the file proxies they are and tab pages as the workspaces they are

I love this idea. Because of this, I really need a feature that manages buffers of different tabs separately. So far, I only found that [bufexplorer](https://github.com/jlanzarotta/bufexplorer/blob/162f6031ada3b2d1ad171e02e93f417ee1689176/doc/bufexplorer.txt#L102) can do this.

I really  appreciate this extension, could you add a feature like this?

**Comment by weirongxu** [comment]
I will implement this, but I need to implement the isolated explorer instance first. So maybe I will do this later.

**Comment by sainnhe** [comment]
Thank you!

By the way, is there any plan to support coc-list?

**Comment by weirongxu** [comment]
> By the way, is there any plan to support coc-list?

What do you mean to support coc-list? buffer in the coc-list?

**Comment by sainnhe** [comment]
For example, search files/folders and grep in current node.

**Comment by weirongxu** [comment]
No plans yet, but it seems easy to implement
