### ISSUE TITLE
Neither Nerd Font icons nor vim-devicons are working

### ISSUE THREAD

**Issue by tylerwolf35** [weirongxu/coc-explorer#140]
Hello,

I am trying to get icons working with this plugin and they simply don't appear. I have tried with both nerd font and vim-devicons with no luck. Icons do appear in NerdTree and other plugins/extensions that utilize icons.

**Comment by weirongxu** [comment]
use `explorer.icon.enableNerdfon` in `coc-settings.json`.
This extension cannot check whether nerd font is installed.

**Comment by tylerwolf35** [comment]
Yes I have done that as well as "explorer.icon.enableVimDevicons" and setting it true. Sorry for not including that in the original issue.

**Comment by weirongxu** [comment]
Try mini_vimrc https://github.com/weirongxu/coc-explorer/tree/master/mini_vimrc ?
It seems I can't reproduce this

**Comment by tylerwolf35** [comment]
Didn't work :/

**Comment by tylerwolf35** [comment]
I have since been able to fix this by creating a new coc-settings.json file. I had 2 on my system and it was reading the other one.
