### ISSUE TITLE
icon don't work on dir, work on file

### ISSUE THREAD

**Issue by zdmgmail** [weirongxu/coc-explorer#141]
icon can work in ranger, but coc-explorer only show it on file

coc-explorer:

![04-05_13:17:10](https://user-images.githubusercontent.com/50515839/78467509-2de7ce00-7740-11ea-8540-f518577b1096.png)

ranger:

![04-05_13:19:07](https://user-images.githubusercontent.com/50515839/78467510-3213eb80-7740-11ea-8aef-829c202911e0.png)

---

I have in coc-settings.json
"explorer.icon.enableNerdfont": true,

**Comment by zdmgmail** [comment]
~ » nvim --version                                                                       zdm@ar
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

**Comment by weirongxu** [comment]
@zdmgmail You can use `explorer.icon.customIcons` to custom your folder icon.

https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/child-columns/icons.nerdfont.json
