### ISSUE TITLE
can it support drop?

### ISSUE THREAD

**Issue by Freed-Wu** [weirongxu/coc-explorer#142]
i notice this plugin has provide many functions which other plugins don't have.
but can it support drop? just like defx, drop a file.

it is an enhancement. thanks!

**Comment by weirongxu** [comment]
Use custom keymappings in `coc-settings`
```json
{
  "explorer.keyMappings": {
    "e": "systemExecute",
  }
}
```

**Comment by Freed-Wu** [comment]
in defx
```
		nnoremap <silent><buffer><expr> s
		\ defx#do_action('multi', ['drop', 'split'])
```

if a file has be opened, change cursor to the window of this file, otherwise, split a window to open this file, but systemExecute always open a new gvim instance to open this file, it is not the same?
