### ISSUE TITLE
can it provide a variable to customize '[BUFFER]' and '[FILE]'?

### ISSUE THREAD

**Issue by Freed-Wu** [weirongxu/coc-explorer#144]
![image](https://user-images.githubusercontent.com/32936898/78878244-a58d6400-7a84-11ea-9a06-ef43c125788e.png)

**Comment by pirey** [comment]
have you tried this option?

i use these to customize the label

```
  "explorer.file.root.template": "[icon & 1] PROJECT ([root])",
  "explorer.file.child.template": "[git | 2] [selection | clip | 1] [indent][icon | 1] [diagnosticError & 1][filename omitCenter 1][modified][readonly] [linkIcon & 1][link growRight 1 omitCenter 5]",
```
![image](https://user-images.githubusercontent.com/10344542/92317132-a91f1a00-f027-11ea-8ccb-540898c9c0ca.png)

**Comment by Freed-Wu** [comment]
`"explorer.file.root.template": "[icon & 1] PROJECT ([root])",` looks good!
