### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by khanghoang** [weirongxu/coc-explorer#15]
Hi, this plugin is interesting to me and I want to work on it.
Is there any documentation I can use for local development?

**Comment by weirongxu** [comment]
Check out this wiki first

* https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim#use-chrome-developer-tools
* https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension

Suppose is `vim-plug`, use `yarn dev` or `yarn build -w` to compile this project, then add this configuration into vim 
```vim
Plug 'path/to/coc-explorer'
```

**Comment by khanghoang** [comment]
awesome, I will play around with it.
