### ISSUE TITLE
Vimscript API: How to get the path to the item under current cursor?

### ISSUE THREAD

**Issue by wookayin** [weirongxu/coc-explorer#150]
How to get the path to the item under the current cursor? Is there any vim functions (`coc_explorer#...`) or `CocAction` we can call from a vimscript? 

Or in general, can we access the copy of attributes of a `node` object (under the current cursor) as a dict or something -- to retrieve not only path, but also some metadata, etc.?

All coc.nvim extensions have this sort of problem where a rich set of Vimscript API is lacking, but it would be great to provide some utility functions.

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorergetnodeinfo

Some use cases from my .vim
https://github.com/weirongxu/dotvim/blob/1ca65431690377d98ec5b91b1b81dd55b2b65033/plugins-conf/coc.rc.vim#L152-L167
