### ISSUE TITLE
Feature: Grep in folder

### ISSUE THREAD

**Issue by vufly** [weirongxu/coc-explorer#152]
This feature is similar to "Find in Folder..." of VSCode.
I think what this feature could do is:
1. Execute a "silent cd" to selected folder.
2. Execute a silent grep/rg/ag, this should be configurable.

**Comment by weirongxu** [comment]
I will provide a Vim API to implement this

**Comment by wookayin** [comment]
Coc-explorer will provide is the path of the root node via vim APIs (#150). After that, we should be able to call whatever Grep/Rg plugins given the directory to search. Look forward to this being possible!

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/issues/150#issuecomment-620517122
