### ISSUE TITLE
update buffer on file move/delete

### ISSUE THREAD

**Issue by alex-popov-tech** [weirongxu/coc-explorer#153]
my often scenario - i have a file in current buffer, and i want to move/rename it.
I go to explorer - move the file, open it right away in explorer, switch back to previous buffer, see the errro that file not exist, switch back to new file...

I know that it is a vim thing, but is that possible to update existing buffers when moving file which they relate to, or close buffer if file was deleted?

**Comment by weirongxu** [comment]
Should be supported in latest version

**Comment by weirongxu** [comment]
About updating the existing buffer, I afraid it is difficult to implement in vim
