### ISSUE TITLE
File name display error and code displayed in explorer

### ISSUE THREAD

**Issue by dalu98** [weirongxu/coc-explorer#162]
This is my explorer config.

And I have set `g:indentLine_fileTypeExclude = ['coc-explorer']`

```
    "explorer.icon.enableNerdfont": true,
    "explorer.icon.enableVimDevicons": true,
    "explorer.sources": [
        {
            "name": "buffer",
            "expand": false
        },
        {
            "name": "file",
            "expand": true
        }
    ],
    "explorer.presets": {
        "floating": {
            "position": "floating"
        }
    }
```

And I got this when I run `:CocCommand explorer`

<img width="368" alt="截屏2020-05-02 上午12 44 18" src="https://user-images.githubusercontent.com/25452934/80823380-1f8db480-8c0f-11ea-8b05-8cd726a94bc6.png">

<img width="287" alt="截屏2020-05-02 上午12 48 54" src="https://user-images.githubusercontent.com/25452934/80823250-e3f2ea80-8c0e-11ea-8d39-ecbe126411ab.png">

When my cursor is in the wrong line, the situation will be temporarily fixed. And it will happened if I move the cursor away.

<img width="318" alt="截屏2020-05-02 上午12 54 29" src="https://user-images.githubusercontent.com/25452934/80823578-7bf0d400-8c0f-11ea-95a9-8238eb453458.png">

And it can be particularly severe when opening a directory with many files...

Is there something wrong in my config? How can I do to fix this? Thanks!

**Comment by weirongxu** [comment]
`set ambiwidth=single`

**Comment by dalu98** [comment]
> `set ambiwidth=single`

thanks, it works for me.

And I still have another question:

```
"explorer.icon.enableNerdfont": true,
"explorer.icon.enableVimDevicons": true,
```
Does this two values must be true at the same time?

I have installed `vim-devicons`, but my font is `WenQuanYi` which is not a `NerdFont`.

When I set `"explorer.icon.enableVimDevicons": true` only, the icons in explorer will not be shown. Only when I set `"explorer.icon.enableNerdfont": true`, can the icons be shown in explorer. 

And As long as the value of `explorer.icon.enableVimDevicons` is `true`, whether or not I set `explorer.icon.enableVimDevicons`, the icon will always be displayed in the explorer. I haven't find any difference of the icons when I set or do not set the value of `explorer.icon.enableVimDevicons`.

**Comment by weirongxu** [comment]
> When I set "explorer.icon.enableVimDevicons": true only, the icons in explorer will not be shown. Only when I set "explorer.icon.enableNerdfont": true, can the icons be shown in explorer.

Should be a bug, I will fix it in the next version
