### ISSUE TITLE
Error: Cannot find module 'trash'

### ISSUE THREAD

**Issue by mnnlkml** [weirongxu/coc-explorer#163]
# Problem
when I had trying to install `coc-explorer` almost completely done but suddenly occur this error

# Coc Explorer Error Log

`` 2020-05-02T14:15:40.684 ERROR (pid:18474) [extensions] - Error: Cannot find module 'trash' ``
`` Require stack:``
``- /data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js``
``- /data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js``
    `at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)`
    `at Function.Module._load (internal/modules/cjs/loader.js:840:27)`
   `` at Module.require (internal/modules/cjs/loader.js:1019:19)``
   `` at req
(/data/data/com.termux/files/home/.vim/plugged/coc.nvim/build/index.js:51217:21)``
   `` at Object.<anonymous> (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:272169)``
   `` at n (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:220)``
   `` at Object.<anonymous> (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:255273)``
    ``at n (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:220)``
    ``at Object.<anonymous> (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:2479)``
  ``  at n (/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:220) ``  ``{``
  ``code: 'MODULE_NOT_FOUND',``
  ``requireStack: [``
   `` /data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js',``
    ``'/data/data/com.termux/files/home/.config/coc/extensions/node_modules/coc-explorer/lib/index.js'``
  ]``
}``

## Platform info and versions

vim version: NVIM v0.4.3
node version: v12.16.3
coc.nvim version: 0.0.78-030aef2f6d
term: xterm-256color
platform: android

**Comment by weirongxu** [comment]
`npm cache clean --force` then reinstall `coc-explorer`
