### ISSUE TITLE
Hidden scrolling past top or bottom entry

### ISSUE THREAD

**Issue by Lasall** [weirongxu/coc-explorer#166]
coc-explorer remembers how far I go past the top or bottom.

When I go to the bottom of the file/buffer list and but then keep going down with `j`, I have to go up by pressing `k` same amount I "overscrolled" with `j`. (Same for when I go past the top.) Weird to describe I hope you get the idea. 

Jump motions work as expected except if I jump to the bottom or top where I already am.

**Comment by weirongxu** [comment]
@Lasall Maybe we can solve it by an action that only moved inside the `source`?

Example:
```jsonc
"keyMappings": {
  'j': 'nextNode:insideSource',
}
```

**Comment by Lasall** [comment]
That would work. By looking into the code there is already some check in `gotoLineIndexNotifier` that should catch the problem.

(My knowledge of TS is non-existent otherwise I would hack it myself, but I already struggle to compile the index.js)

**Comment by Lasall** [comment]
Thank you!
