### ISSUE TITLE
Path of buff

### ISSUE THREAD

**Issue by ta-tikoma** [weirongxu/coc-explorer#168]
![image](https://user-images.githubusercontent.com/2934128/81298695-918e4f80-908e-11ea-8d0a-56c04eeb529b.png)

First buff open in NERDTree, 
second buff open in coc-explorer.
How I can switch path to like NERDTree ? Because it correct worked with phpunit plugin.

**Comment by weirongxu** [comment]
Seems NERDTree use relative path to open the file, maybe we should use relative directory by default.

https://github.com/preservim/nerdtree/blob/master/lib/nerdtree/path.vim#L804

**Comment by ta-tikoma** [comment]
Or settings for switch path type.
My project with phpunit in docker. They can't use full path for file because it not correct inside docker.
I would be glad to have setting for this.

**Comment by weirongxu** [comment]
`explorer.openAction.relativePath`

**Comment by ta-tikoma** [comment]
Thanks. you really fast

**Comment by ta-tikoma** [comment]
it does not work again in 0.6.2

**Comment by weirongxu** [comment]
There nothing changes about the `relativePath`
