### ISSUE TITLE
this.floatBuffer.getHeight is not a function

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#169]
hello, when i open coc-explorer, error occured in the message line
![image](https://user-images.githubusercontent.com/50551377/81315885-771f9a80-90bd-11ea-8098-062ad1614b4e.png)

**Comment by weirongxu** [comment]
Seems coc.nvim make a breaking change for FloatBuffer

https://github.com/neoclide/coc.nvim/commit/322c7dfb58138b19fb03eab24f2177e59ba3e66c
