### ISSUE TITLE
center vertically when gotoParent is executed

### ISSUE THREAD

**Issue by Hollow-Glitch** [weirongxu/coc-explorer#170]
Hello :)

Is there anyway to execute the **zz** command when gotoParent is executed?
The reason why I want to do this is because I was in my `~/.config/nvim` directory, and I wanted
to make `~/.config` my current root, hence used my **gotoParent** keybinding.
But since there is a bunch of directories in my `~/.config` dir the `nvim` directory showed up at the bottom. 

![image](https://user-images.githubusercontent.com/33203747/81440251-01283b80-9170-11ea-9601-82049abff63d.png)

So I tried to do the following naive thing :D 

```
// snip
      "H": ["gotoParent", "zz"],
// snip
```

But it didn't help :(

**Comment by weirongxu** [comment]
` "H": ["gotoParent", "normal:zz"],`

**Comment by Hollow-Glitch** [comment]
wow, that was fast, ty :) , did I miss a doc somewhere? :/

**Comment by weirongxu** [comment]
> wow, that was fast, ty :) , did I miss a doc somewhere? :/

No, we still don't have a complete actions doc.

**Comment by Hollow-Glitch** [comment]
I see, ty nonetheless, I was playing arround with it, I created monstrosities like:

```
"H": ["normal:gghjjHkzz"], // didn't work, supposed to go to parent and place the cursor on the last root
```

I resorted to the above gibberish because when I tried to do it like

```
"H": ["normal:gg", "collapse", "nodeNext", "nodeNext", "gotoParent", "nodePrev", "normal:zz"],
```

then it wasn't doing the right thing at all, it seemed as it was not doing them in sequence.

But no problem because

```
    // snip
   "H": ["gotoParent", "normal:zz"], 
    // snip
```

works as intended, except that it leaves that file in focus which was in focus before root change but it is good enough.
Just thought I would write a follow-up on the situation :)
