### ISSUE TITLE
split in any position?

### ISSUE THREAD

**Issue by zdmgmail** [weirongxu/coc-explorer#173]
I want to set 

```
sh
sj
sk
sl
```
to split new window in that position, now seems only can do split, vsplit in `sk , sl` 

Is there any way to do these?

**Comment by zdmgmail** [comment]
```
autocmd FileType coc-explorer map <buffer> sj :set splitbelow<cr> ...  
```
success

```
autocmd FileType coc-explorer map <buffer> sh :set nosplitright<cr> ...
```

failed , still do `sl ` thing

**Comment by weirongxu** [comment]
I think this will increase action complexity. If you want to implement the open action by yourself, use the Vim API to fetch the fullpath. 

`CocAction('runCommand', 'explorer.getNodeInfo', 0)['fullpath']`
https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorergetnodeinfo
