### ISSUE TITLE
Add the ability to fold all.

### ISSUE THREAD

**Issue by yassinebridi** [weirongxu/coc-explorer#176]
VS Code has a nice feature to fold all, in case you are way deep in your file tree and want to get back.
That would be pretty useful for this beautiful plugin.

**Comment by yassinebridi** [comment]
@weirongxu It would be pretty helpful if the collapse all mapping is added to the help menu.
Thanks for this feature

**Comment by weirongxu** [comment]
I have no idea which mapping is more suitable for this action, Now I use `<tab>` then select the `collapse:all`

**Comment by yassinebridi** [comment]
I just checked the new commands, i just mapped it to `ga`, it won't interfere with other mappings

**Comment by npearson72** [comment]
Is there a way to run `collapse:all` before explorer opens?
