### ISSUE TITLE
How to add custom icons for directories?

### ISSUE THREAD

**Issue by hsheikhali** [weirongxu/coc-explorer#177]
Does anyone have any clue how to change the default directory icons?

For example I want the default folder icons to be: 
collapsed:  (Material theme folder icons like in vscode)
exapnded:  (Material theme folder icons like in vscode)

and I want to my node_module file to specifically be:  (Nodejs Icon)

so far I was able to change the default icons for javascript files doing this:

  "explorer.icon.customIcons": {
    "icons": {
      "javascript": {
        "code": ""
      }
    },
    "extensions": {},
    "filenames": {},
    "dirnames": {},
    "patternMatches": {},
    "dirPatternMatches": {}
  }

but what do I do for folders?

**Comment by weirongxu** [comment]
```jsonc
{
  "explorer.icon.customIcons": {
    "icons": {
      "nodejs": {
        "code": "",
        "color": "#000000"
      }
    },
    "extensions": {},
    "filenames": {},
    "dirnames": {
      "node_modules": "nodejs"
    },
    "patternMatches": {},
    "dirPatternMatches": {}
  }
}
```
