### ISSUE TITLE
Help with debugging diagnostics

### ISSUE THREAD

**Issue by maralorn** [weirongxu/coc-explorer#178]
Let me start with emphasizing how much I like this plugin. It‘s really awesome and exactly what I was missing for my vim setup, only much better.

Sadly I can‘t see diagnostic error and warning counts. I tried with different plugins and language servers. The coc diagnostics list contains some errors for different files, the coc statusline says something like `W:1 E:2`, but the errors don‘t get listed in the explorer. I made sure that the `[diagnosticError]` is in the template. Still it seems like to coc-explorer, there are no diagnostics.

I am using `coc-explorer 0.6.2` with `coc-nvim-2020-04-21` on `NVIM v0.4.3` on nixos-20.03.

If it‘s not just a config mistake by me and if needed I will try to contribute a fix, but I‘d very much appreciate if you could help me a bit on how to debug this. explorer.debug = true, didn‘t really help me.

**Comment by maralorn** [comment]
Okay, apparently coc-explorer only loads the diagnostics on an explizit save. Since I have autosave activated in my vim, that got never triggered. Diagnostics are working fine. This is amazing!

**Comment by weirongxu** [comment]
The latest version has used `CocDiagnosticChange` to reload the diagnostics

**Comment by maralorn** [comment]
Wow, it‘s so great, that you implemented this so quickly. Really nice.

Sadly, it seems still buggy to me. I am sorry, but updating to the newest version actually stopped displaying diagnostics at all. So it‘s like when I reported the issue but now saving doesn‘t help.

**Comment by maralorn** [comment]
Did this stop working for others too with version 0.7.0?

Do you have any idea what I can try to debug this?

**Comment by weirongxu** [comment]
Reproduced

**Comment by maralorn** [comment]
Working now. You are awesome!
