### ISSUE TITLE
Ability to ignore files (custom + gitignored) search(f), recursive-search(F) 

### ISSUE THREAD

**Issue by collegeimprovements** [weirongxu/coc-explorer#182]
Is it possible to ignore files that are in `.gitignore` file when we perform the search(f/F) ?
Is it possible to ignore files based on some rc file/settings-file from search?
Is it possible to ignore files based on some rc file/settings-file from explorer itself ? (i.e. hide those files - useful when want to focus on specific folders or ignore certain folders on big project).

**Comment by conradob** [comment]
Yes, would be awesome to have an option to ignore directories and files. Depending on the project, `FUZZY` is a bit laggy.

**Comment by weirongxu** [comment]
Note: This feature requires the [fd](https://github.com/sharkdp/fd) command
