### ISSUE TITLE
[question] is there a way to duplicate file

### ISSUE THREAD

**Issue by vcfvct** [weirongxu/coc-explorer#186]
Thanks for this great extension, much faster than Nerdtree!
I was to duplicate a file in the same directory and rename, is there a way to achieve this? 

I tried `c` then `p` get below options:
```
already exists.
(S)kip, (R)ename, (F)orce replace, (Q)uit:
```

**Comment by weirongxu** [comment]
Press R to choose the `Rename` option

**Comment by vcfvct** [comment]
> Press R to choose the `Rename` option

Oh, got it. I was confused by the `rename` a bit, thought that was to rename the original file without duplicating. 
Thanks! 😃
