### ISSUE TITLE
J/K navigation is laggy

### ISSUE THREAD

**Issue by Akin909** [weirongxu/coc-explorer#187]
Hi 👋, thanks again for this great plugin.
Recently I've noticed that when pressing `j/k` to move up and down in the `coc-explorer` buffer. There seems to be a small delay in registering the move. I normally have `j/k` mapped to 
```vim
nnoremap <expr><silent> j (v:count > 1 ? 'm`' . v:count : '') . 'gj'
```
But have removed these mapping to test things and seems to still be slow. I know that they are mapped to coc explorer actions in that buffer, I'm not sure if some processing is being done under the hood somewhere whenever I move between nodes?

Hopefully this GIF helps explain, if it's not super clear what's happening I'm spamming `J/K` and in a normal vim buffer that would move quite fast but in the coc explorer buffer there's a bit of lag each time.

![laggy_tree](https://user-images.githubusercontent.com/22454918/82115247-7cce4d80-9759-11ea-990d-b88b040f4e2e.gif)

Also my coc explorer config is pretty basic
```json
  // Explorer
  "explorer.width": 30,
  "explorer.file.autoReveal": true,
  "explorer.icon.enableNerdfont": true,
  "explorer.file.showHiddenFiles": false,
  "explorer.previewAction.onHover": false
```
I turned off the preview action not sure if that makes a difference or not :shrug:

**Comment by weirongxu** [comment]
We have two places handle the cursor movement event.

https://github.com/weirongxu/coc-explorer/blob/bb0b047cfe8cebb0b6e8d5cbf4e361ed97b34587/src/explorer.ts#L158-L162

https://github.com/weirongxu/coc-explorer/blob/bb0b047cfe8cebb0b6e8d5cbf4e361ed97b34587/src/explorer.ts#L180-L185

I think the performance impact is very small, but sometimes cursor navigation laggy when the CPU is busy

**Comment by markhagemann** [comment]
I've found that it doesn't lag when I use `floatingLeftside` or `floatingRightside`. It always lags for me on the normal mode though.

**Comment by Akin909** [comment]
@weirongxu :thinking: thanks for explaining. In the case where a user isn't using the hover preview can the first function be disabled somehow? like not registering that callback at all if the setting is off. Not sure what that function does but I assume `hoverPreview` does a few things till it realises the user doesn't have the preview enabled then it stops? maybe it checks the config asynchronously each time?

**Comment by Akin909** [comment]
Re. performance I'm running on a pretty beefy laptop and my CPU monitor doesn't register much activity but the lag is consistent with high and low CPU load

**Comment by Akin909** [comment]
Actually looking at the code it shouldn't be calling the first `onCursorMoved` at all since it checks the config status in the constructor, maybe that isn't working somehow.

Alternatively (granted I'm just guessing at stuff now) maybe the call via the nvim api to get the current line index can be debounced so it only happens when the cursor has settled? although tbh I have no idea how and when that variable is being used so it could break things :sweat_smile:

**Comment by weirongxu** [comment]
> EDIT: I figure if you are moving around the buffer quite a lot which I do when I'm not really sure where I'm going you might end up making that call to nvim like 30 times in a few seconds 🤷

Maybe I can just fetch the cursor position before running the action.

**Comment by Akin909** [comment]
Awesome thanks for fixing that @weirongxu that's much faster :heart:
