### ISSUE TITLE
The Icon not working on WSL2 with Windows Terminal

### ISSUE THREAD

**Issue by Fullstop000** [weirongxu/coc-explorer#190]
I'm using neovim with coc.nvim and coc.explorer in Windows Terminal to operate a WSL2 based Ubuntu 18.04.
It seems icons are not displayed well

![image](https://user-images.githubusercontent.com/12471960/82527145-47b26880-9b68-11ea-858a-cb0f6345a0f0.png)

**Comment by weirongxu** [comment]
I'm also using Microsoft Terminal, are you sure your terminal font is [nerdfont](https://www.nerdfonts.com/)?

**Comment by Fullstop000** [comment]
@weirongxu Do I just need to switch my win10 font to a certain type nerdfont?

**Comment by weirongxu** [comment]
> @weirongxu Do I just need to switch my win10 font to a certain type nerdfont?

You just need to change the font of your Terminal. 
https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md#default-settings

**Comment by Fullstop000** [comment]
I've downloaded the jetbrains mono, installed all of them and config my Windows Terminal with 
```
"defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "fontFace": "JetBrains Mono",
            "fontSize": 14
        },
```
Does feel the fonts changes but the icons are still missing. Did I miss something?

**Comment by weirongxu** [comment]
Should be "JetBrainsMono Nerd Font" or "JetBrainsMono NF"

**Comment by Motingi** [comment]
![p1](https://user-images.githubusercontent.com/79796150/167268585-bddc45c3-fd8f-4f7d-8d42-06f51a4d246f.png)
![p2](https://user-images.githubusercontent.com/79796150/167268587-96e25601-42a7-4ca4-ba75-10c001756073.png)
The suggestion doesn't work for me

**Comment by weirongxu** [comment]
> ![p1](https://user-images.githubusercontent.com/79796150/167268585-bddc45c3-fd8f-4f7d-8d42-06f51a4d246f.png) ![p2](https://user-images.githubusercontent.com/79796150/167268587-96e25601-42a7-4ca4-ba75-10c001756073.png) The suggestion doesn't work for me

@Motingi I suggest using the GUI to configure the font. If you can't find it, it means that you have not yet installed the font
