### ISSUE TITLE
Deprecated: expandOrCollapse

### ISSUE THREAD

**Issue by wookayin** [weirongxu/coc-explorer#191]
I have a config keyMappings like

```
 "<cr>": ["expandable?", "expandOrCollapse", "open"],
```

But recently `expandOrCollapse` has been deprecated. First of all, the warning message needs to be improved: https://github.com/weirongxu/coc-explorer/blob/v0.7.5/src/source/sources/file/fileActions.ts#L330 because it does not tell what was actually being deprecated.

I changed the config as
```
 "<cr>": ["expandable?", ["expanded?", "expand", "collapse"], "open"],
```
but then it does not work. It turns out that
```
 "<cr>": ["expandable?", ["expanded?", "collapse", "expand"], "open"],
```
is correct.

BTW why are you deprecating this? I think the previous command is quite handy..

**Comment by weirongxu** [comment]
Because `expandOrCollapse` cannot use any options, like `expand:compact|uncompact` and `collapse:recursive`. And we have `expanded?` so this action seems a little redundant

**Comment by weirongxu** [comment]
In addition, `expanded?` can be highlighted in help.

![image](https://user-images.githubusercontent.com/1709861/82635189-42b9eb80-9c32-11ea-8e01-f7f1075e1853.png)

**Comment by wookayin** [comment]
Thanks for the clarification!
