### ISSUE TITLE
Mapping: Copy file path/name and paste directly afterwards don't inserts correct selection

### ISSUE THREAD

**Issue by fools-mate** [weirongxu/coc-explorer#192]
If file path/name is copied with a shortcut and then pasted immediately, e.g. on the vim command line, it is not the currently copied path that is pasted, but the one before it.

Example:
`map <leader>t y<ESC>:! <C-R>"`

**Comment by weirongxu** [comment]
Please use the `getNodeInfo` API https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorergetnodeinfo

**Comment by fools-mate** [comment]
Thank you, this works great!

For example I use it to listen to audio files real quick:
`map <leader>t :exec '!afplay ' . CocAction('runCommand', 'explorer.getNodeInfo', 0).fullpath<CR>
`

Any plans to implement a feature that passes the file path to a shell command?

**Comment by weirongxu** [comment]
> Any plans to implement a feature that passes the file path to a shell command?

No plan yet
