### ISSUE TITLE
[coc.nvim] Error: Explorer sources not initialized yet

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#193]
When I start coc-explorer, message like the title always occur at the message line.

![image](https://user-images.githubusercontent.com/50551377/82750102-8e11fc80-9de0-11ea-8690-554989020b92.png)

**Comment by yatli** [comment]
Same error message here, but the plugin does work.

**Comment by jamespotz** [comment]
I also have this error. But the plugin does work fine

**Comment by lee-shun** [comment]
same error

**Comment by yatli** [comment]
@lee-shun could you try update the extension? Should be fixed in the latest version.

**Comment by Daniele122898** [comment]
even with the most up-to-date version i have this error but everything is working

**Comment by dhaiibfiukkiu** [comment]
me too.
v0.13.11 is the last version that doesn't have this error in my environment.
