### ISSUE TITLE
npm 243 error on install

### ISSUE THREAD

**Issue by agilesteel** [weirongxu/coc-explorer#194]
This is not an issue. Just information for someone who stumbles on this.

I had trouble installing `coc-explorer` via `:CocInstall coc-explorer`. I was constantly getting a 243 from npm.

After hours of research the only thing that helped was making sure that npm was NOT installed via snap. After uninstalling the snap version and then installing via [debinstall](https://github.com/nodesource/distributions/blob/master/README.md#debinstall) `:CocInstall coc-explorer` worked like a charm.

I hope this helps someone.

Cheers

**Comment by weirongxu** [comment]
To be honest, I have never used snap, sometimes I will deb / pacman to install nodejs, but generally I will nvm manage my nodejs and npm binary
