### ISSUE TITLE
Is possible to hide the statusline?

### ISSUE THREAD

**Issue by rodrigore** [weirongxu/coc-explorer#195]
I'm migrating from nerdtree where can set a variable to hide the statusline.

I look in the source code that 'CocExplorerSelectUI' can be use to change the highlight instatusline but not sure how to hide it.

**Comment by weirongxu** [comment]
augroup CocExplorerCustom
  autocmd!
  autocmd User CocExplorerOpenPost setl statusline=
augroup END

**Comment by rodrigore** [comment]
Thank you for guide me to find the answer. In case of anyone want this behaviour this is work for me:

``` vim
augroup CocExplorerCustom
  autocmd!
   autocmd User CocExplorerOpenPost setl statusline=%#NonText#
augroup END
```
