### ISSUE TITLE
Explorer icons don't working in MacOS

### ISSUE THREAD

**Issue by ajaymathur** [weirongxu/coc-explorer#199]
First of all, thanks a lot for building this package. I love it. ❤️ 

---

**Description if issue:**

I am using neoVim, on iTerm2. Am I missing any config? 🙂 

My CocConfig:

```
{
 "explorer.width": 30,
 "explorer.icon.enableNerdfont": true,
 "explorer.previewAction.onHover": false,
 "explorer.keyMappings": {
   "<cr>": ["expandable?", "expand", "open"],
   "v": "open:vsplit"
  }
}
```

I do have nerd font installed:

![image](https://user-images.githubusercontent.com/9667784/83482754-70c9e600-a4e4-11ea-9ccb-69fdb761e86d.png)

But the icons don't appear:

![image](https://user-images.githubusercontent.com/9667784/83482831-8c34f100-a4e4-11ea-892c-45c13bae9594.png)

**Comment by weirongxu** [comment]
Please make sure your iterm2 font has been changed to `Nerd Font`

**Comment by ajaymathur** [comment]
Hey @weirongxu , yeah that actually worked. I had to restart my laptop. Thanks a lot for responding. 🙂

**Comment by Phantom-Rehan** [comment]
@weirongxu which nerdfont specifically do i need? This is what I see
![Screenshot from 2020-08-31 12-26-52](https://user-images.githubusercontent.com/57185902/91691494-5657e500-eb85-11ea-973e-fc8f2397deb9.png)
