### ISSUE TITLE
Maximum call stack size exceeded when too many files in directory

### ISSUE THREAD

**Issue by codehz** [weirongxu/coc-explorer#20]
When too many files in directory, I means, 21k files in same directiry
so I think there must has a recursive call to list file?

**Comment by weirongxu** [comment]
Cannot reproduce this, but it may happen when the directory is very deep.

https://github.com/weirongxu/coc-explorer/blob/66b3e65bb415c77ba133bc3f91e917b69174e255/src/source/sources/file/file-source.ts#L650-L680

**Comment by weirongxu** [comment]
Reproduced, when testing 210k files in same directory

**Comment by weirongxu** [comment]
Ummm, this error caused by Math.max(...arr).

But it's still slow when loading so many files, so might want to consider adding paging for this.
