### ISSUE TITLE
Cursor skips files

### ISSUE THREAD

**Issue by NullSense** [weirongxu/coc-explorer#201]
The cursor skips files, but can still select folders. I have the default configuration.

**Comment by weirongxu** [comment]
What is `skips files` mean?

**Comment by NullSense** [comment]
So I am unable to select files, only folders. The cursor just goes to the next folder.

**Comment by NullSense** [comment]
![image](https://user-images.githubusercontent.com/10047484/83529743-0a949180-a4eb-11ea-93f9-e9d01fe571e0.png)
If I go one down with `j`, it selects the folder below.
![image](https://user-images.githubusercontent.com/10047484/83529758-12543600-a4eb-11ea-9d9a-9a5a16238b44.png)

**Comment by weirongxu** [comment]
Okay, I get it, should be that you have defined a global map `gj` to `j`

**Comment by NullSense** [comment]
Ah, yes, that was indeed the case, would it be possible to make this work with a j->gj and k->gk mapping? A lot of people use it to navigate wrapped lines easier.

**Comment by weirongxu** [comment]
You can temporarily avoid this by "explorer.keyMappings", but I should remove the coc-explorer gj and gk by default in the future

```json
{
  "explorer.keyMappings": {
    "j": "nodeNext",
    "k": "nodePrev"
  }
}
```
