### ISSUE TITLE
Icons not colored 

### ISSUE THREAD

**Issue by ravisumit33** [weirongxu/coc-explorer#203]
I have installed coc-explorer and nerdfonts on nvim 0.4.3 on Mac
Everything works fine except icons are all white.

<img width="1792" alt="Screenshot 2020-06-05 at 12 05 59 PM" src="https://user-images.githubusercontent.com/19284116/83844638-fb992380-a724-11ea-8171-b9063dd92e1d.png">

Below is my coc config:
```
{
 "explorer.width": 30,
 "explorer.icon.enableNerdfont": true,
 "explorer.previewAction.onHover": false,
 "explorer.keyMappings": {
   "<cr>": ["expandable?", "expand", "open"],
   "v": "open:vsplit"
  }
}
```

Is there a way to make icons colored as in Readme ?

**Comment by weirongxu** [comment]
try `:set termguicolors`

**Comment by rbhanot4739** [comment]
Exact same issue for me, even with `:set termguicolors` on. All the icons are white.

**Comment by weirongxu** [comment]
@rbhanot4739 https://github.com/weirongxu/coc-explorer/wiki/FAQ#why-my-file-icon-has-not-color
