### ISSUE TITLE
Global presets: file.child.template ignored

### ISSUE THREAD

**Issue by djromero** [weirongxu/coc-explorer#208]
I'm trying to remove the file size from the file nodes. 
A single node is shown like this:
```
<icon> my-filename.rb  <spacing>  9.99 kB
```
I want to remove the file size from all nodes. Even if it's not visible (there is a large indentation) I don't use it at all.

This is my global presets:
```
let g:coc_explorer_global_presets = {
\   'sidebar': {
\      'position': 'left',
\      'file.child.template': '[git | 2] [selection | clip | 1] [indent][icon | 1] [diagnosticError & 1][filename omitCenter 1][modified][readonly] [linkIcon & 1][link growRight 1 omitCenter 5]'
\   }
\ }
```

The `file.child.template` is the default one removing `[size]`. 
It is ignored, the size is always shown.

The global presets is working, for example the `position` is applied correctly.

**Comment by weirongxu** [comment]
Sorry, the template parameter is incorrect in the document.

**Comment by weirongxu** [comment]
Please use `file-child-template` instead of
