### ISSUE TITLE
How To ?

### ISSUE THREAD

**Issue by naveenkrdy** [weirongxu/coc-explorer#212]
I am having hard time trying to figure out on how can i apply these coc-explorer setting directly in .vimrc .

vim version 8.2

{
  "explorer.width": 30,
  "explorer.icon.enableNerdfont": true,
  "explorer.previewAction.onHover": false,
  "explorer.keyMappings": {
    "<cr>": ["expandable?", "expand", "open"],
    "v": "open:vsplit"
}
}

Also how can i keep my buffer section expanded always in coc-explorer .

-Thanks !

**Comment by weirongxu** [comment]
`explorer.sources` or https://github.com/weirongxu/coc-explorer#--sources-sources

**Comment by naveenkrdy** [comment]
@weirongxu hi ! 
thanks for the reply for the second problem.
but how do i apply the above settings from .vimrc ?

**Comment by weirongxu** [comment]
@naveenkrdy `:h g:coc#config()` or `:h g:coc_user_config`
