### ISSUE TITLE
improve behavior

### ISSUE THREAD

**Issue by glepnir** [weirongxu/coc-explorer#213]
Try multi-file directories. The first time coc-explorer opens the window is slower than defx

**Comment by Akin909** [comment]
This is *much* worse in large directories. I work in a very large mono repo and it takes `coc-explorer` like 10seconds to startup. I wonder if the data can be streamed in or load just the first level deep so it's faster and then lazily load the lower layers over time.

**Comment by weirongxu** [comment]
@Akin909 
Will it slow when running `git status --porcelain -u --ignored` in your project? Seems the loading of the git status should be asynchronous, otherwise it will block the first load of the explorer

**Comment by Akin909** [comment]
@weirongxu yep that command is slow in my project, looks like its spending a lot of time printing the contents of nested node modules

**Comment by weirongxu** [comment]
I have avoided git reload on master branch https://github.com/weirongxu/coc-explorer/commit/7364fe286ebb8ec82472fc3b05717bcdf0890207.

**Comment by weirongxu** [comment]
Now git status has been rendered asynchronously, I think it is fast enough
