### ISSUE TITLE
enhance the l behavior

### ISSUE THREAD

**Issue by glepnir** [weirongxu/coc-explorer#214]
I write a function  to check the current position is directory of file, then run open current file, or toggle directory expand/collapse when use defx. Does this behavior can implement in coc-explorer?

**Comment by weirongxu** [comment]
```jsonc
{
  "explorer.keyMappings": {
    "<cr>": [
      "expandable?",
      ["expanded?", "collapse", "expand"],
      "open"
    ]
  }
}
```

Or more dynamic usage https://github.com/weirongxu/coc-explorer/wiki/Vim-API#toc6
