### ISSUE TITLE
sometimes it shows - for a directory while there are files in directory and it's not opened

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#224]

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/86373753-0abbb480-bc84-11ea-9872-a80a3685dd75.png)

**Comment by weirongxu** [comment]
I haven't seen this problem, please provide a way to reproduce it.

**Comment by GopherJ** [comment]
@weirongxu  You can hit enter to go to a directory and hit `backspace` to go out then the directory becomes  `-` which is confusing...

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/86445583-f246ab00-bd12-11ea-9409-06e1df90cd19.png)
