### ISSUE TITLE
Will the support of vim be better

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#226]
I'm moving from old nerdtree to coc-explorer, it's awesome that I can add/delete files/directories as I want, the only issue that I have for now is the performance.

It's slower than nerdtree, but yes there are many more features so it's quite normal. Just wondering if there is still space for performance improvements?

**Comment by weirongxu** [comment]
Which part will be slower than nerdtree? For me, the overall user experience is faster than nerdtree. BTW, the coc-explorer under neovim will be faster than vim

**Comment by GopherJ** [comment]
@weirongxu emm...it seems there is a huge difference while using `vim` and `neovim`. coc-explorer in neovim is much faster.

So my question becomes:

> Will the support of vim be better?

**Comment by weirongxu** [comment]
What version of vim do you use? please provide your `:CocInfo` output.

**Comment by GopherJ** [comment]
Hi, here
![image](https://user-images.githubusercontent.com/33961674/86511675-aa4f8300-bdfb-11ea-8969-c71db4b674dd.png)
