### ISSUE TITLE
[Feature Request]Bookmark support annotation

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#227]
Hello, bookmarks can only display the file name but not the annotation

coc-bookmark can display the annotation
![image](https://user-images.githubusercontent.com/50551377/86510793-8bfe7d00-be25-11ea-8134-7db16b5ee0b1.png)
but coc-explorer can not display
![image](https://user-images.githubusercontent.com/50551377/86510805-a33d6a80-be25-11ea-955c-01c4ef435431.png)

**Comment by weirongxu** [comment]
You can append it to bookmark template, later I'll update it in the default template
```
explorer.bookmark.child.template: "[selection | 1] [filename] [position] - [annotation]"
```

**Comment by fgheng** [comment]
thank you very much
