### ISSUE TITLE
Does coc-explorer support workspace?

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#23]
hello,  does coc-explorer support show a list of workspace that current opened?

**Comment by weirongxu** [comment]
Not supported, but you can describe this feature, I will consider whether to add it

**Comment by fgheng** [comment]
describe this feature here?
---
if we open two files, file1 file2, which file1 belongs to workspace w1 and file2 belongs to workspace w2, coc-explorer will show w1 and w2, if we choose w2, the current work directory will change to w2.

**Comment by fgheng** [comment]
and would you plan to support some interface that users can use to show their own things? like show outline in coc-explorer (It would be better if vim-vista could combine coc-explorer ).

**Comment by weirongxu** [comment]
> and would you plan to support some interface that users can use to show their own things? like show outline in coc-explorer (It would be better if vim-vista could combine coc-explorer ), like show tabs which is a plugin that users write.

There already has some interfaces that can create a source like file-source or buffer-source via js, but I think it is still unstable.

**Comment by fgheng** [comment]
that's great.
I also have a suggestion, could you add a function which support floating preview? just like the plugin vim-vista, when cursor on vista line, there will be a floating window show more info of current line. it would be better to create an floating window interface for users.

**Comment by weirongxu** [comment]
> I also have a suggestion, could you add a function which support floating preview? just like the plugin vim-vista, when cursor on vista line, there will be a floating window show more info of current line. it would be better to create an floating window interface for users.

Display the file content in the floating preview?

**Comment by fgheng** [comment]
I think it's better to display some information of file attribute, such as file size,  type and so on, because we can not see these info unless increase the width of coc-explorer window.

**Comment by weirongxu** [comment]
> I think it's better to display some information of file attribute, such as file size, type and so on, because we can not see these info unless increase the width of coc-explorer window.

Great, I have created a new thread about these two features, #25 #24
