### ISSUE TITLE
How to config the icon colors like github or VSCode ?

### ISSUE THREAD

**Issue by ehyyoj** [weirongxu/coc-explorer#230]
like the github, it's so colorful

![image](https://user-images.githubusercontent.com/9150170/87267171-7f4ee880-c4f9-11ea-8a61-3df9406ff3ff.png)

**Comment by weirongxu** [comment]
You can change the color by `explorer.icon.customIcons`, Reference https://github.com/weirongxu/coc-explorer/blob/master/src/icons.nerdfont.json

**Comment by ehyyoj** [comment]
Excellent! thanks bro!
