### ISSUE TITLE
Better use of space

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#235]
I've had a great time with coc-explorer, I'd like to raise a small question:

![image](https://user-images.githubusercontent.com/33961674/87884869-94ec7280-ca11-11ea-9be4-8b7cc4763ff4.png)

As you can see in the screenshot we had nothing between `git symbol` and real files

I think coc-explorer doesn't make use of this space. I mean there are spaces which can be used so the whole tree can be more `readable` => Like move the whole file tree a little bit more close to left side

Is it possible to optimize this for better usage of space?

**Comment by weirongxu** [comment]
Use `file-child-template`
