### ISSUE TITLE
Strange highlight & overflow with icon

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#236]
![image](https://user-images.githubusercontent.com/33961674/88156872-5241ba80-cc0a-11ea-89a0-1dc3e2ea0364.png)

![image](https://user-images.githubusercontent.com/33961674/88156894-5ec61300-cc0a-11ea-9340-efec8b728d8d.png)

**Comment by weirongxu** [comment]
Should be a problem of your terminal and font
