### ISSUE TITLE
Icon not working

### ISSUE THREAD

**Issue by zhb888999** [weirongxu/coc-explorer#238]
Icon not working! Nerd-fonts have installed. The range is ok. I used archlinux.

**Comment by zhb888999** [comment]
explorer.icon.enableNerdfont: Enable nerdfont. type: boolean
Default:false
Must set true in coc-settings.json,such as and "explorer.icon.enableNerdfont: true".

**Comment by rivalak** [comment]
> explorer.icon.enableNerdfont: Enable nerdfont. type: boolean
> Default:false
> Must set true in coc-settings.json,such as and "explorer.icon.enableNerdfont: true".

Also, one needs to set the `explorer.icon.enableVimDevicons` as true.
