### ISSUE TITLE
How could I close a tab (buffer) when coc-explorer is opening?

### ISSUE THREAD

**Issue by ngocjr7** [weirongxu/coc-explorer#239]
How could I close a buffer (file) when coc-explorer is opening and I am focusing on file? 

The only choice I know is to switch to coc-explorer and go to Buffer and press `d`. Do you know any better options?

When I am working on 2 subwindows, it like
```
|coc-explorer | file-1 | file-2 | 
```

I can quickly close file-2 by `ctrl + w + q`. But if I do it when :
```
|coc-explore | file-1 | 
```

it completely quit neovim. I am looking for the option that allows coc-explorer to open even when the last file is close by `ctrl + w + q`.

**Comment by weirongxu** [comment]
coc-explorer will not quit automatically, it maybe a problem with your script or plugin, please try minimal vimrc.

**Comment by fgheng** [comment]
> I can quickly close file-2 by `ctrl + w + q`. But if I do it when :
> 
> ```
> |coc-explore | file-1 | 
> ```
> 
> it completely quit neovim. I am looking for the option that allows coc-explorer to open even when the last file is close by `ctrl + w + q`.
Hello, How to do that? I want to quit neovim when there are only coc-explorer and one window.

**Comment by ngocjr7** [comment]
@fgheng try this.
```
autocmd BufEnter * if (winnr("$") == 1 && &filetype == 'coc-explorer') | q | endif
```
