### ISSUE TITLE
search file mot working with "Task error : spawn dir"

### ISSUE THREAD

**Issue by grimgort** [weirongxu/coc-explorer#240]
search file not working with "Task error : spawn dir ENOENT"

**Comment by weirongxu** [comment]
It seems that the `dir` command does not work in powershell and windows terminal, you need to install the `fd`. https://github.com/sharkdp/fd

**Comment by grimgort** [comment]
it works. Thank you very much.
This could be added to the documentation. Overall, I find that the coc.nvim extensions are poorly documented and it takes a lot of time for an average user to use them
