### ISSUE TITLE
Floating window has wrong position after scroll

### ISSUE THREAD

**Issue by Ironimus** [weirongxu/coc-explorer#243]
Here's a screen recording illustrating the problem:

![Screen-Recording-2020-07-30-at-1](https://user-images.githubusercontent.com/8076719/88903110-ce1bb280-d25b-11ea-8395-f5000d29245d.gif)

Happened a few days ago, before that worked well

Related question, can I just disable the floating window?

**Comment by weirongxu** [comment]
Fixed on latest
