### ISSUE TITLE
How to change current directory of explorer when changing to different buffer of different directory?

### ISSUE THREAD

**Issue by MuhammadMouradG** [weirongxu/coc-explorer#244]
I want to change the current work directory of explorer each time I navigate between different buffers of different path.

Is there an option or command that provides this feature?

PS: This feature is available only when the opened files are in the same directory by highlighted the current opened file.

**Comment by weirongxu** [comment]
You can use the [Vim API](https://github.com/weirongxu/coc-explorer/wiki/Vim-API) to execute `cd` action to change the directory

**Comment by MuhammadMouradG** [comment]
Thanks for your guidance,
I created the following vim script:
```vim
autocmd BufEnter * silent! let dir = getcwd()
autocmd BufEnter * call CocAction('runCommand', 'explorer.doAction', 'closest', {'name': 'cd', 'args': [dir]})
```
they are working correctly when I call them in command mode (`:`) but when I put them in my `init.vim` the following error is produced after open nvim:
![Screenshot at 2020-07-31 11-08-14](https://user-images.githubusercontent.com/50509521/89019810-6c1b8580-d30d-11ea-8beb-20055e3e746a.png)

**Comment by weirongxu** [comment]
Make sure this script call after `CocNvimInit`

autocmd User CocNvimInit call s:initCoc()

**Comment by MuhammadMouradG** [comment]
This is my script:
```vim
" Sure scripts are called after CocNvimInit
autocmd User CocNvimInit call s:initCoc()

nmap <space>e :CocCommand explorer<CR>
autocmd BufEnter * if (winnr("$") == 1 && &filetype == 'coc-explorer') | q | endif

" Automatically open coc-explorer
autocmd BufEnter * silent! let dir = getcwd()
autocmd VimEnter * if argc() == 1 | exe 'CocCommand explorer --no-focus ' . dir | endif
autocmd VimEnter * if argc() == 0 | Startify | exe 'CocCommand explorer --no-focus ' . dir | endif

autocmd BufEnter * call CocAction('runCommand', 'explorer.doAction', 'closest', {'name': 'cd', 'args': [dir]})
```

**Comment by MuhammadMouradG** [comment]
This is my script:
```vim
" Sure scripts are called after CocNvimInit
autocmd User CocNvimInit call s:initCoc()

nmap <space>e :CocCommand explorer<CR>
autocmd BufEnter * if (winnr("$") == 1 && &filetype == 'coc-explorer') | q | endif

" Automatically open coc-explorer
autocmd BufEnter * silent! let dir = getcwd()
autocmd VimEnter * if argc() == 1 | exe 'CocCommand explorer --no-focus ' . dir | endif
autocmd VimEnter * if argc() == 0 | Startify | exe 'CocCommand explorer --no-focus ' . dir | endif

autocmd BufEnter * call CocAction('runCommand', 'explorer.doAction', 'closest', {'name': 'cd', 'args': [dir]})
```

**Comment by weirongxu** [comment]
`autocmd User CocNvimInit call s:init_coc()`

Declare a coc_init() function, and put your scripts into this function.

**Comment by MuhammadMouradG** [comment]
When I use `CocNvimInit` event the following error is appear:
![Screenshot at 2020-07-31 12-50-34](https://user-images.githubusercontent.com/50509521/89028622-46e24380-d31c-11ea-88fb-7f51907a0afc.png)
So, I use `CocExplorerOpenPost` event instead which is work fine.

@weirongxu Thanks again for your guidance.

For who interested with this behaviour, put the following in the `init.vim` (for NeoVim):
```vim
" Sure the following script is called after CocExplorerOpenPost
function s:explorer_inited()
	autocmd BufEnter * silent! let dir = getcwd()
	autocmd BufEnter * call CocAction('runCommand', 'explorer.doAction', 'closest', {'name': 'cd', 'args': [dir]})
endfunction

autocmd User CocExplorerOpenPost call s:explorer_inited()
```

**Comment by MuhammadMouradG** [comment]
When I use `CocNvimInit` event the following error is appear:
![Screenshot at 2020-07-31 12-50-34](https://user-images.githubusercontent.com/50509521/89028622-46e24380-d31c-11ea-88fb-7f51907a0afc.png)
So, I use `CocExplorerOpenPost` event instead which works fine.

@weirongxu Thanks again for your guidance.

For who interested with this behaviour, put the following in the `init.vim` (for NeoVim):
```vim
" Sure the following script is called after CocExplorerOpenPost
function s:explorer_inited()
	autocmd BufEnter * silent! let dir = getcwd()
	autocmd BufEnter * if (&filetype != 'coc-explorer') | exe 'call CocAction("runCommand", "explorer.doAction", "closest", {"name": "cd", "args": [dir]})'
endfunction

autocmd User CocExplorerOpenPost call s:explorer_inited()
```

**Comment by MuhammadMouradG** [comment]
When I use `CocNvimInit` event the following error is appear:
![Screenshot at 2020-07-31 12-50-34](https://user-images.githubusercontent.com/50509521/89028622-46e24380-d31c-11ea-88fb-7f51907a0afc.png)
So, I use `CocExplorerOpenPost` event instead which works fine.

@weirongxu Thanks again for your guidance.

For who interested with this behaviour, put the following in the `init.vim` (for NeoVim):
```vim
" Sure the following script is called after CocExplorerOpenPost
function s:explorer_inited()
	autocmd BufEnter * if (&filetype != 'coc-explorer') | exe 'silent! let dir = getcwd()'
	autocmd BufEnter * call CocAction("runCommand", "explorer.doAction", "closest", {"name": "cd", "args": [dir]})
endfunction

autocmd User CocExplorerOpenPost call s:explorer_inited()
```

**Comment by MuhammadMouradG** [comment]
Sorry, but when use the previous script all things seem good except when I am trying open file from coc-explorer which leads to the nvim stuck and does not respond to any command. I tried using `BufWinEnter` event instead of `BufEnter`event but that leaded to open the selected file but still nvim stuck and does not respond to any command.

Could you please provide me with probable event or group of event or the solve of the problem?

**Comment by weirongxu** [comment]
Use `CocActionAsync` instead of the `CocAction`, BTW, you should save the previous dir to avoid calling cd duplicity

**Comment by MuhammadMouradG** [comment]
Everything seem working good now! Thanks again for your help.
