### ISSUE TITLE
How to set the background color of floating window transparent?

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#245]
Hello, I want to transparent the background of the floating window and I use this command `hi CocExplorerNormalFloat guibg=None` , but it didn't work.

**Comment by weirongxu** [comment]
```vim
autocmd FileType coc-explorer set winblend=30
autocmd FileType coc-explorer-border set winblend=30
```

**Comment by weirongxu** [comment]
Note: only the latest version of neovim is supported

**Comment by weirongxu** [comment]
I added a hooks `CocExplorerInited`, instead of the `autocmd`, check out https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-hooks
