### ISSUE TITLE
The '--reveal' flag does not work

### ISSUE THREAD

**Issue by linjiX** [weirongxu/coc-explorer#247]
Set `"explorer.file.autoReveal": false,` in `coc-settings.json`

Open coc-explorer with command:
`CocCommand explorer --reveal expand("%")`
The cursor should located at the current buffer, which does not happen.

(according to my memory, it works before 0.7.22)

**Comment by weirongxu** [comment]
This is expected, because `--reveal` is only working when opened.

The correct command is `CocCommand explorer --reveal revealFilepath expand("%")`, we should add a new option named `--auto-reveal` and `--no-auto-reveal`

**Comment by linjiX** [comment]
It is possible to reveal a file when user want it to be revealed? Not reveal the file everytime current file changes?
In other words, could you please provide a command to reveal the file when `explorer.file.autoReveal": false`

**Comment by weirongxu** [comment]
https://github.com/weirongxu/dotvim/blob/master/plugins-conf/coc.rc.vim#L132

**Comment by weirongxu** [comment]
Some API detail in here https://github.com/weirongxu/coc-explorer/wiki/Vim-API

**Comment by linjiX** [comment]
Thanks~
command: `call CocAction('runCommand', 'explorer.doAction', 'closest', ['reveal:0'], [['relative', 0, 'file']])`
solved my problem
