### ISSUE TITLE
ENOENT git error on git diff and when closing Twiggy

### ISSUE THREAD

**Issue by jmolero** [weirongxu/coc-explorer#248]
I get the following error when the explorer is open and I'm browsing the git diff or when closing the Twiggy's window:

```
[coc.nvim]: Uncaught exception: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Doesn't happen if doing the same with the explorer is closed.

Here's the link for Twiggy: https://github.com/sodapopcan/vim-twiggy

Let me know if I can give help gathering more info about this.

Thank you!

**Comment by weirongxu** [comment]
I can't reproduce it, please provide more detailed steps.

**Comment by jmolero** [comment]
Thanks for your reply. 

Seems it started happening with coc-explorer open and when using the vim-workspace plugin, which I tried for a while but I don't use anymore.
