### ISSUE TITLE
coc-explorer doesn't change rootPath after transition from file which have root pattern to file which doesn't have one

### ISSUE THREAD

**Issue by artofnothingness** [weirongxu/coc-explorer#252]
I open some project with project-pattern inside and coc-explorer works fine, but then if i open some file which doesn't have any root patterns up the directories coc-explorer just stays at the same project root. 
I have this inside my config: autocmd BufEnter * silent! :lcd%:p:h.
In NERDTree NERDTreeToggleVCS command does change it in such situation.

**Comment by weirongxu** [comment]
Explorer reveal will automatically select a root path from root-strategies
https://github.com/weirongxu/coc-explorer#--root-strategies-root-strategies
