### ISSUE TITLE
Add possibility to use user-config values for "number" and "relativenumber"

### ISSUE THREAD

**Issue by krnik** [weirongxu/coc-explorer#253]
Currently I'm missing the ability to display number bar in the coc-explorer buffers. I use them a lot and would like to use the same movement flow regardless of the buffer type (file-explorer or not).

What I do is I just apply a patch after every install on every machine (gets tiring) to `autoload/coc_explorer/init.vim`
```vim
if !exists('g:coc_explorer_use_number_settings')
    let g:coc_explorer_use_number_settings = 0
endif
````
`lines 20,21`
```vim
call setbufvar(a:bufnr, '&number', g:coc_eplorer_use_number_settings)
call setbufvar(a:bufnr, '&relativenumber', g:coc_explorer_use_number_settings)
```

1) Is there any easier way to do it than patching?
2) Could such option to support this behavior  (displaying line numbers) be implemented directly in `coc-explorer`?

**Comment by weirongxu** [comment]
Use CocExplorerInited
Some examples https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-hooks

**Comment by krnik** [comment]
Sorry, missed the obvious.
