### ISSUE TITLE
Automatically focus opened file 

### ISSUE THREAD

**Issue by semanser** [weirongxu/coc-explorer#254]
Let's say I have several files opened and I'm opening a new one with `E` or `s` key.
Is there any way to automatically focus opened file?

**Comment by weirongxu** [comment]
You can try the `drop` action

**Comment by semanser** [comment]
@weirongxu I can't find it in the docs. What do you mean?

**Comment by weirongxu** [comment]
> @weirongxu I can't find it in the docs. What do you mean?

@semanser Press `?` in file source, you could get the docs for actions, and you can press <tab> to list all actions for current source.

So you should be able to use keyMappings to change the `E` or `s`.

**Comment by semanser** [comment]
@weirongxu Thanks a lot for your response! It seems like the `drop` command opens the file in the same window as `coc-explorer`  (just replacing it).

<img width="363" alt="Screenshot 2020-09-05 at 16 14 11" src="https://user-images.githubusercontent.com/4020045/92305756-d7064f00-ef92-11ea-8696-ab1b9deb08f8.png">

**Comment by weirongxu** [comment]
OK, it looks like I need to implement a new `drop` feature

**Comment by weirongxu** [comment]
Moved #401
