### ISSUE TITLE
How change background color when open with --preset floating

### ISSUE THREAD

**Issue by mitzukodavis** [weirongxu/coc-explorer#255]
Hello, is possible change the background when open file with preset floating

![Screen Shot 2020-09-05 at 11 04 10 AM](https://user-images.githubusercontent.com/13607376/92309753-e45d1280-ef6d-11ea-8b4e-4195edd5ca07.png)
![Screen Shot 2020-09-05 at 11 49 56 AM](https://user-images.githubusercontent.com/13607376/92309794-1b332880-ef6e-11ea-97a5-500166cdd771.png)

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/wiki/Highlight#floating-window
