### ISSUE TITLE
check if coc-explorer window is open

### ISSUE THREAD

**Issue by pirey** [weirongxu/coc-explorer#259]
is there a way to know if there is current coc-explorer window buffer opened?

right now i'm using this method:

```
let g:coc_explorer_open = 0

function! s:coc_explorer_is_open() abort
    return get(g:, 'coc_explorer_open', 0)
endfunction

function! s:coc_explorer_state(s) abort
    echom 'state ' . a:s
    let g:coc_explorer_open = a:s
endfunction

autocmd BufEnter *coc-explorer* call s:coc_explorer_state(1)
autocmd BufHidden *coc-explorer* call s:coc_explorer_state(0)
```

but it rather hacky.

i'm just wondering if it has already this feature built-in to coc-explorer

**Comment by weirongxu** [comment]
You can use `let opened = CocAction('runCommand','explorer.getNodeInfo','closest') is v:null`, more information see this https://github.com/weirongxu/coc-explorer/wiki/Vim-API

**Comment by pirey** [comment]
i got this error on initial load neovim

![image](https://user-images.githubusercontent.com/10344542/92329388-5ed28300-f091-11ea-8f07-bce983b06cf9.png)

the error only happen on initial load. 
the code works after that.

it seems that my code is running before runComman is ready, i'm not really sure.
what do you think?

i'm calling this function in lightline component, which i suppose is called everytime lightline is updated.

here's an excerpt.

```vim
let g:lightline = {
" ...
\   'tabline': {
\     'left': [['explorer_pad', 'buffers']]
\   }
\   'component_function': {
\     'explorer_pad': 'LightlineCocExplorerLeftpad',
" ...
\   },
" ...
\}

function! LightlineCocExplorerLeftpad() abort
    if &co < 86
        return ''
    endif

    if CocAction('runCommand', 'explorer.getNodeInfo', 'closest') isnot# v:null
        return printf('%-29s', '') . '⎟'
    endif

    return ''
endfunction

```

**Comment by weirongxu** [comment]
`h CocNvimInit`

**Comment by pirey** [comment]
Ok.
so there is no direct means to check if coc has already started.

for anyone looking at similar issue later, what i do is to set custom variable to indicate coc has initialized.

```vim
function! s:on_coc_init()
    let g:coc_ready = 1
endfunction

autocmd User CocNvimInit call s:on_coc_init()
```

then i can use it in lightline function

```vim
    if get(g:, 'coc_ready', 0)
        if CocAction('runCommand', 'explorer.getNodeInfo', 'closest') isnot# v:null
            return printf('%-29s', '') . '⎟'
        endif
    endif
```

thanks @weirongxu

**Comment by alps2006** [comment]
It is not working when having multiple windows by `explorer.getNodeInfo`.

I use the code below.
```
    let l:winnrs = filter(range(1, winnr('$')), 'getwinvar(v:val, "&ft") == "coc-explorer"')
    let l:opened  = len(l:winnrs) > 0
    if l:opened
        ......
    else
        ......
    endif

```
