### ISSUE TITLE
Is there a way to hide some of these elements?

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#260]
<img width="340" alt="Screen Shot 2020-09-06 at 4 36 31 PM" src="https://user-images.githubusercontent.com/1323414/92327023-53fefa80-f05f-11ea-9629-df9f81cc8ac1.png">

I'd like to hide the `[FILE]` and just start the top of my node without it.

Also, I've turned on nerdfonts, and see now lines that indicate hierarchy of the folders. Is there a way to hide these?

**Comment by weirongxu** [comment]
`explorer.file.root.template` & `explorer.file.column.indent.indentLine`

**Comment by npearson72** [comment]
Thank you

**Comment by npearson72** [comment]
BTW, amazing plugin!
