### ISSUE TITLE
Add icon for .gd file type 

### ISSUE THREAD

**Issue by Hamzailer** [weirongxu/coc-explorer#261]
It would be nice if there was a icon for .gd files

**Comment by weirongxu** [comment]
What is a gd extension? If we want to support it, we must first found a suitable icon from nerdfont, https://www.nerdfonts.com/cheat-sheet

**Comment by Hamzailer** [comment]
Ah i thought you could manually add icons but the gd file extension is for the godot scripting language sorry for bothering
