### ISSUE TITLE
[Bug] Open file will crash neovim

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#262]
Hello, my neovim version information is as below:
```
NVIM v0.5.0-671-gc1d395a6d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-2a561221-6e55-4c4d-85ba-531ef9ac3f0a
```

and today, Whether you use coc-explorer to open a file or close coc-explorer, neovim will crash. Just like as below
![Peek 2020-09-07 15-20](https://user-images.githubusercontent.com/50551377/92359364-b1f21780-f11d-11ea-9b6c-be48cebe922b.gif)

**Comment by weirongxu** [comment]
I am releasing a new version, you can try it

**Comment by fgheng** [comment]
sorry, I use command `CocUpdate` to update all coc plugins just now, but the problem still exists.

How to check coc-explorer's version?

**Comment by fgheng** [comment]
![image](https://user-images.githubusercontent.com/50551377/92360454-68a2c780-f11f-11ea-8809-b33ddfcd73b2.png)
current version is 0.7.30, is this right?

**Comment by weirongxu** [comment]
Okay, I reproduced the problem in the latest neovim

**Comment by fgheng** [comment]
Is that neovim's problem?

**Comment by weirongxu** [comment]
The problem appears after this commit(https://github.com/neovim/neovim/commit/54ce1010e86cbb29067aabfc332dab59b5a88edb)
I need to find out which feature cause this problem

**Comment by fgheng** [comment]
Looking forward to your working, thank you

**Comment by jessun2017** [comment]
Same problem after I updated my neovim-nightly. It seems that defx.nvim also has this problem.

**Comment by weirongxu** [comment]
Move to https://github.com/neovim/neovim/issues/12873
