### ISSUE TITLE
CocCommand explorer unexpectedly changes root in coc-explorer

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#265]

**Comment by npearson72** [comment]
Turned out to be a problem with my mappings. Closing.

**Comment by npearson72** [comment]
Actually, this is still continuing. Sometimes when I open explorer it changes root to parent of the directory from which vim was opened.

Example...

If I open vim in: `~/a/my_projects/project_1`

Then I open explorer: `:CocCommand explorerfile<cr>`

Most times explorer opens everything under `project_1`.

Some times for some reason explorer opens everything under `my_projects` (the parent of `project_1`).

It's not consistent. Is there a way to log when this behavior happens?

**Comment by weirongxu** [comment]
This may be expected (behavior)[https://github.com/weirongxu/coc-explorer#root-uri], because the `workspace.rootPath` of `coc.nvim` will only be triggered when the current buffer supports the [`rootPatterns`](https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers) setting of `lsp`. Otherwise it may use vim cwd

**Comment by weirongxu** [comment]
Maybe we should let coc.nvim support fix a `workspace.rootPath` directory like vscode? Maybe it can be fixed in the directory when we start vim. I'm not sure if this will have a better experience or not.

**Comment by npearson72** [comment]
I wasn't familiar with the `worskpace.rootPath` and didn't understand that this came from `coc.nvim`.

Given your helpful feedback, I was able to realize that my problem is that I have multiple projects under a single `git` repository, example:

```
- dev/
  ├── big_project/
  │   ├── .git/
  │   ├── sub_project_1/
  │   ├── sub_project_2/
  │   │   ├── dist/
  │   │   ├── src/
  │   │   ├── README.md
  │   │   ├── package.json (see notes below)
  │   │   ├── yarn.lock
  │   ├── sub_project_3/
```

When PWD is `dev/big_project/sub_project_2` and I open vim (example: `vim .`) I start with an empty buffer.

I then open explorer and select `dev/big_project/sub_project_2/package.json`. Now `package.json` is in the buffer.

I then open explorer and instead of showing only everything under the `sub_project_2` directory, explorer goes up with where `.git` is located and expands everything there.

Based on your feedback, I have added the following to my `coc-settings.json`:

```
{
   "coc.preferences.rootPatterns": ["yarn.lock", "package.json", ".env", ".git"]
}
```

And this seems to have solved my problem.

**Comment by weirongxu** [comment]
> What do you think? Is this a reasonable and stable fix to the problem or is there a better approach?

For me, it's enough, but you can also use your own `root-uri` [option](https://github.com/weirongxu/coc-explorer#root-uri)

**Comment by npearson72** [comment]
How can I defined `root-uri` to be the PWD when I open vim?

**Comment by weirongxu** [comment]
```vim
let g:coc_explorer_global_presets = {
\   'pwd': {
\     'root-uri': getcwd(),
\   },
\ }

:CocCommand explorer --preset pwd<CR>
```

**Comment by npearson72** [comment]
Oh, this is much better! Thank you.
