### ISSUE TITLE
Displays wrong icon for files without extension

### ISSUE THREAD

**Issue by ivan-preocanin** [weirongxu/coc-explorer#266]
I'm on Arch, I've installed [ttf-nerd-fonts-symbols](https://www.archlinux.org/packages/community/x86_64/ttf-nerd-fonts-symbols/) so I can have file icons. Everything works well except icons for files without extensions, where it displays some Tibetan letter.
![2020-09-10-114954_309x138_scrot](https://user-images.githubusercontent.com/20935129/92714533-9fb1ec80-f35c-11ea-9444-1788bb97add1.png)

**Comment by weirongxu** [comment]
Maybe the issue of your font, try to change your font or use  https://aur.archlinux.org/packages/nerd-fonts-complete/
