### ISSUE TITLE
Can't install coc-explore in wsl2 ubuntu20.04

### ISSUE THREAD

**Issue by applejwjcat** [weirongxu/coc-explorer#269]
I try 10+ times and update npm to the lastest version, but I can't install coc-explore properly! All other coc extensiosn can be installed correctly!

**Comment by weirongxu** [comment]
The extension name is coc-explorer not coc-explore

**Comment by applejwjcat** [comment]
> The extension name is coc-explorer not coc-explore

I am sorry, but in my vimrc I write coc-explorer, correctly, It didn't work!

**Comment by weirongxu** [comment]
Please provide the error message

**Comment by applejwjcat** [comment]
![屏幕截图 2020-09-16 093852](https://user-images.githubusercontent.com/45581427/93282254-91524d80-f800-11ea-9b6f-f135940f7a8f.png)
I am sorry to bother you, but I know little of nodejs, Can't you tell me what's wrong above?

**Comment by weirongxu** [comment]
Try to clean cache (`npm cache clean --force`), and then reinstall coc-explorer.

**Comment by applejwjcat** [comment]
It works!! Thank you!
