### ISSUE TITLE
Delete a file with trash fails

### ISSUE THREAD

**Issue by andys8** [weirongxu/coc-explorer#270]
Delete (move to trash) action fails with:

```
## Output channel: explorer

Error: ENOENT: no such file or directory, mkdir
```

Delete forever is working.

Could it be that [`trash`](https://github.com/weirongxu/coc-explorer/blob/29ae0c4c07d735e27b780b48e7a1f12a8bcb1aa4/package.json#L774) and [`trash-cli`](https://github.com/andreafrancia/trash-cli) are incompatible? Or is it not working anyway?

```
coc-explorer
0.8.0

trash --version
trash 0.17.1.14 (andreafrancia)

node --version
v12.15.0
```

**Comment by weirongxu** [comment]
Explorer uses [nodejs package](https://github.com/sindresorhus/trash) to delete files, but I can’t reproduce this problem.
What is your system environment?
I can consider supporting this python trash-cli command by a new option

**Comment by andys8** [comment]
Maybe if one can configure a command to delete / move to trash?

**Comment by weirongxu** [comment]
I should add an option to disable the built-in trash, and then once disabled, use trash-put or send2trash instead of it

**Comment by weirongxu** [comment]
```jsonc
{
  "explorer.trash.command": "trash-put %l"
}
{
  "explorer.trash.command": "mv --backup=t %l ~/.trash/"
}
```
