### ISSUE TITLE
How to remap `<Tab>` so that it brings me to the next buffer (i.e. `<C-w>w`)

### ISSUE THREAD

**Issue by macintacos** [weirongxu/coc-explorer#271]
I unmapped `tab` in coc-explorer because I use `tab` while in `NORMAL` mode to quickly switch to the next buffer by executing `<C-w>w`. I can't seem to get that to work with `coc-explorer`; it doesn't seem to do anything. It works when I bring up that buffer's help text though (when hitting `?`). Any chance this could be added?

I can't seem to figure out the `doAction` syntax in the API wiki section to make this a reality https://github.com/weirongxu/coc-explorer/wiki/Vim-API

**Comment by weirongxu** [comment]
```
"explorer.keyMappings": {
    "<Tab>": false, // cancel default mapkey
}
```

**Comment by macintacos** [comment]
Thanks, that worked! I was setting it to an empty string; didn't realize it could just accept a boolean value.
