### ISSUE TITLE
cannot work together with minimap.vim

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#277]
After installing https://github.com/wfxr/minimap.vim, I found it can be difficult to make it co-work with coc-explorer, because coc-explorer consider it as a window and we need to choose

**Comment by GopherJ** [comment]
See also: https://github.com/wfxr/minimap.vim/issues/17

**Comment by GopherJ** [comment]
BTW, while pressing `A` and `B` it doesn't work, I mean the letters have actually never worked for me. Any ideas?

**Comment by weirongxu** [comment]
You can use the `explorer.openAction.select.filter` options to filter the windows

**Comment by GopherJ** [comment]
@weirongxu Cool sorry I'm not aware of it. I'll test and let you know

**Comment by GopherJ** [comment]
@weirongxu it works!
