### ISSUE TITLE
Switch to previous or some other buffer after deleting an active one

### ISSUE THREAD

**Issue by osenvosem** [weirongxu/coc-explorer#279]
After deletion of an active buffer coc-explorer buffer becomes full-width instead of switching to another existing buffer. I think it should switch to the previous buffer or at least some other existing buffer and if the buffer being deleted is the last one the explorer buffer shouldn't last alone.

![Screenshot 2020-09-29 at 20 32 20](https://user-images.githubusercontent.com/6762673/94595505-98af3780-0293-11eb-9046-88a5897a8699.jpg)

**Comment by weirongxu** [comment]
I think we can keep an empty buffer, but I'm not sure this is easy or not

**Comment by osenvosem** [comment]
@weirongxu what about the issues on the picture, not switching to the previous buffer when the active buffer is deleted?

**Comment by weirongxu** [comment]
Ok, I think it can be switched to the previous buffer.
and when it delete the last one buffer, we should keep an empty buffer, otherwise close the current vim tab like #121.

**Comment by decafff** [comment]
Agreed, it can also cause sizing issues when another buffer is opened afterwards, forcing you to close and re-open the explorer.
And using :quit does't remove the buffer from the explorer :(

Example:
[![Example](https://i.imgur.com/Nu1Xji5.gif)](https://i.imgur.com/Nu1Xji5.mp4)
