### ISSUE TITLE
No highlight for single file

### ISSUE THREAD

**Issue by jidibinlin** [weirongxu/coc-explorer#28]
I don`t why highlight dosen`t work for single file (only single file can`t be highlighted)

**Comment by weirongxu** [comment]
What is a `single file` mean? please provide a screenshot

**Comment by jidibinlin** [comment]
![2019-10-31_18-32](https://user-images.githubusercontent.com/38578679/67939592-de3f2c80-fc0c-11e9-8083-5b4862eded1f.png)

**Comment by weirongxu** [comment]
Icon highlight only support in gui colors

try this command
```
TERM="xterm-256color" vim -c 'set termguicolors | set background=dark'
```

**Comment by jidibinlin** [comment]
Thankyou It`s work for me when i add set termuicolors to my .vimrc
