### ISSUE TITLE
git.icon.ignored is not displayed the first time coc-explorer is displayed

### ISSUE THREAD

**Issue by bwright1558** [weirongxu/coc-explorer#282]
When I open a file with nvim inside a git project and open coc-explorer, the git ignore symbol (`!`) is not shown next to ignored files. But if I toggle coc-explorer off and then back on, or if I refresh coc-explorer, then the git ignore symbols suddenly appear.

Here is my `coc-settings.json` file:
```json
{
  "explorer.previewAction.onHover": false,
  "explorer.file.column.git.showIgnored": true,
  "explorer.file.hiddenRules": {
    "patternMatches": [
      "^\\.git$"
    ]
  }
}

**Comment by weirongxu** [comment]
Should be fixed in latest
