### ISSUE TITLE
cant delete items to trash

### ISSUE THREAD

**Issue by joe23rep** [weirongxu/coc-explorer#283]
when i want to delete an item to the trash folder i get this error:

Error: EACCES: permission denied, mkdir  /run/timeshift/backup/.Trash-1000 

i went threw the documentation but havent found an option to manually set the trash path. it somehow wants to create a trash folder in my timeshift backup directory.

is it possible that i can set the path manually where the trashed files should be moved too in my coc.json file?

**Comment by weirongxu** [comment]
This is based on trash (https://github.com/sindresorhus/trash), but we can consider using move file instead of trash. There are related issues #270, I may implement together.

**Comment by weirongxu** [comment]
```jsonc
{
  "explorer.trash.command": "trash-put %l"
}
{
  "explorer.trash.command": "mv --backup=t %l ~/.trash/"
}
```
