### ISSUE TITLE
Expand/open directory/file with single leftmouse-click

### ISSUE THREAD

**Issue by astier** [weirongxu/coc-explorer#285]
Hi. I like this plugin. Thank you. Is it possible to expand/open a directory/file with a single mouseclick? Right now it is only possible with `<2-leftmouse>`.

**Comment by weirongxu** [comment]
You can add `<LeftMouse>` to `explorer.keyMappings`. but as far as I know, <LeftMouse> can't get the click position, so does not use here

**Comment by astier** [comment]
> You can add LeftMouse to explorer.keyMappings

I already tried defining:

```
"<LeftMouse>": [
      "expandable?",
      ["expanded?", "collapse", "expand"],
      "open"
]
```

However, then the position of the cursor doesn't change if I click on a different node then the one which is currently selected.

> but as far as I know, can't get the click position, so does not use here

Sorry. I dont understand.

> weirongxu closed this issue

So there is no solution?

**Comment by weirongxu** [comment]
> However, then the position of the cursor doesn't change if I click on a different node then the one which is currently selected.
> So there is no solution?

Yes, I don't know any way to get the mouse position when `<LeftMouse>`, if you have any solution, you can let me know.

**Comment by astier** [comment]
I dont have a solution. I now that nerdtree is able to do it somehow.

**Comment by weirongxu** [comment]
Okay, I found that nerdtree uses `<LeftRelease>` instead of `<LeftMouse>`

**Comment by weirongxu** [comment]
I may consider supporting `<LeftRelease>` by default, but I need to consider what is different with `<2-LeftMouse>`

**Comment by astier** [comment]
Using leftrelease works for me. Thank you.
