### ISSUE TITLE
not working after update

### ISSUE THREAD

**Issue by pirey** [weirongxu/coc-explorer#287]
i got [coc.nvim] Command: explorer not found error after updating.
![image](https://user-images.githubusercontent.com/10344542/96109764-35ffa200-0f09-11eb-8833-79cf695525a4.png)

how should i troubleshoot this?

and i also got this message randomly after a while using nvim, i thought maybe it is related so i included it here.
![image](https://user-images.githubusercontent.com/10344542/96109682-19636a00-0f09-11eb-8473-33e9eb12b48d.png)

**Comment by pirey** [comment]
i tried to remove the plugin locally, and re-install it, but still got the same error message, and the explorer is not showing.

**Comment by pirey** [comment]
i'm installing the plugin as separate vim-plug plugin, instead of calling CocInstall directly

like this:
`Plug 'weirongxu/coc-explorer', {'do': 'yarn install --frozen-lockfile'}`
i wonder if this is the issue, because previously i have no problem using this method.

**Comment by weirongxu** [comment]
Thanks for your issue, fixed in the latest.
