### ISSUE TITLE
Is it possible to collapse all other directories when entering coc-explorer?

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#288]
I have the following mapping to open coc-explorer:

```
nnoremap <leader>e :CocCommand explorer<cr>
```

It works great when the buffer is empty (right after starting vim) and when I have a file in the buffer. In the latter case, it opens coc-explorer and drills down to the file in the buffer. Exactly what I want.

However, typically when I have coc-explorer open, I may browse and expand other directories and find other files. This leaves a bunch of expanded folders. So each time I open coc-explorer in a given session, I have to collapse all these folders manually as I find them distracting.

Is there a way to always collapse all folders except the folder that my file in buffer is in?

**Comment by weirongxu** [comment]
Maybe we can add a configuration option to cancel node expanded state store

```
"explorer.expandStore": true | ["!file"] | false,
```

**Comment by npearson72** [comment]
That would be great. What is the `["!file"]` option for?

Also, is this not possible to do using a `CocExplorerOpenPre` hook?

**Comment by weirongxu** [comment]
> That would be great. What is the ["!file"] option for?

['!file'] means that only file-source is excluded from expandStore

> Also, is this not possible to do using a CocExplorerOpenPre hook?

I think `CocExplorerOpenPre` can't support `autoExpandOptions` and `collapse:all` at the same time

**Comment by weirongxu** [comment]
I added a new option to disable the folder stores.
```
{
  "explorer.expandStores": false
}
```

**Comment by npearson72** [comment]
Hey, awesome! Thank you for this @weirongxu! Love using coc-exporer!
