### ISSUE TITLE
Unable to Toggle Close Help Menu

### ISSUE THREAD

**Issue by gregorywaynepower** [weirongxu/coc-explorer#292]
Hey there,

For some reason I am to toggle open the coc-explorer help menu with the ? key, but I am unable to close it with the ? key once it is open. Do you need me to provide my coc.nvim or init.vim config files?

Thank you

**Comment by gregorywaynepower** [comment]
Thanks for the added feature! Realized that I am having an issue E31 error due to this.

**Comment by weirongxu** [comment]
Actually, this feature is still in develop branch, I will merge and release later.
