### ISSUE TITLE
[Feature] Colored filenames based on errors + git status?

### ISSUE THREAD

**Issue by MonliH** [weirongxu/coc-explorer#293]
| Currently, the status bar looks like this | It could look more like this |
|---|---|
| <img width=300 src="https://user-images.githubusercontent.com/30177086/97081910-2234f980-15f5-11eb-8c23-4cf0e56e1c02.png"></img> | ![image](https://user-images.githubusercontent.com/30177086/97081941-62947780-15f5-11eb-8714-8c6df12855da.png) |

The second screenshot was taken from vscode. Notice the coloring of different filenames. As vscode does, I would create a order of colors too, for example, give the error color higher priority over the git `M` color.

**Comment by weirongxu** [comment]
Good idea, I may need to consider an option to control whether to highlight the directory name or filename

**Comment by MonliH** [comment]
How difficult would it be to implement this? I'm not familiar with the codebase, although if you gave me a few pointers, I would be happy to help!

**Comment by weirongxu** [comment]
Might not be difficult, you need to modify the code of `filename` column, you also need to modify `GitManager` and `DiagnosticManager`.

https://github.com/weirongxu/coc-explorer/blob/4a8c35abe0ff129247c1b4f649e5643df9b925aa/src/source/sources/file/child-columns/filename.ts#L18
https://github.com/weirongxu/coc-explorer/blob/4a8c35abe0ff129247c1b4f649e5643df9b925aa/src/git/manager.ts
https://github.com/weirongxu/coc-explorer/blob/4a8c35abe0ff129247c1b4f649e5643df9b925aa/src/diagnosticManager.ts

**Comment by MonliH** [comment]
Great, I'll look into it.

**Comment by MonliH** [comment]
Currently, I've gotten error highlights to work. The red really glaring:
![image](https://user-images.githubusercontent.com/30177086/97115437-a28b5580-16ee-11eb-9135-62743a0c3488.png)

Maybe we should make the highlight for the filename lighter?

**Comment by weirongxu** [comment]
In fact, this color is inherited from `CocErrorSign`, but can change CocExplorerFileDiagnosticError or CocErrorSign by himself

https://github.com/weirongxu/coc-explorer/wiki/Highlight
https://github.com/sainnhe/sonokai/blob/master/colors/sonokai.vim#L323

**Comment by MonliH** [comment]
Oh, so are you suggesting the user should change the color themselves?

**Comment by weirongxu** [comment]
I thought about it carefully, This is still not user friendly enough.
I think our options should be designed like this.

```jsonc
{
  "explorer.file.filename.colored.schema": {
    "type": "object",
    "properties": {
      "diagnosticError": {
        "type": "string"
      },
      "diagnosticWarning": {
        "type": "string"
      },
      "gitStaged": {
        "type": "string"
      },
      "gitUnstage": {
        "type": "string"
      }
    },
    "default": {
      "diagnosticError": "...",
      "diagnosticWarning": "...",
      "gitStaged": "...",
      "gitUnstage": "..."
    }
  },
  "explorer.file.filename.colored.enable": {
    "anyOf": [
      {
        "type": "boolean"
      },
      {
        "type": "object",
        "properties": {
          "diagnosticError": {
            "type": "boolean"
          },
          "diagnosticWarning": {
            "type": "boolean"
          },
          "gitStaged": {
            "type": "boolean"
          },
          "gitUnstage": {
            "type": "boolean"
          }
        }
      }
    ],
    "default": false
  }
}
```

Once we are `enable` is true, we should use `scheme` instead of CocErrorSign / CocWarningSign

**Comment by MonliH** [comment]
Yes, that configuration looks good to me!
Just to make sure, if `explorer.file.filename.colored.enable` is set to false, the colour for the files and folders should just be normal, right? and if `explorer.file.filename.colored.enable` is `{"diagnosticError": true}`, it would only color errors red (not warnings, etc.)? 

By the way, why just `gitStaged` and `gitUnstaged`? Aren't there more than just those?

**Comment by weirongxu** [comment]
> Just to make sure, if `explorer.file.filename.colored.enable` is set to false, the colour for the files and folders should just be normal, right? and if `explorer.file.filename.colored.enable` is `{"diagnosticError": true}`, it would only colour errors red (not warnings, etc.)?

Yes.


> By the way, why just `gitStaged` and `gitUnstaged`? Aren't there more than just those? Or should we just have one colour for all git related statuses?

Sorry, I didn't notice that the `modified` and `added`, `renamed` are different colors in vscode.


> EDIT: is `gitStaged` just the highlight color I should use for git based statuses? for some reason, it looks gray for me:
> ![image](https://user-images.githubusercontent.com/30177086/97119857-fb68e700-170a-11eb-905e-6822f2684846.png)

Indeed, it is based on the `Comment` highlight. For colored filename, we can abandon `gitUnstaged` and `gitStaged`, we should define some highlights, E.g `FileFilenameDiagnosticError`, `FileFilenameDiagnosticWarning`, `GitModified`, `GitRenamed`, `GitAdded`... that also need to modify the highlight of git column https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/child-columns/git.ts#L49

Then in the future, we can use `GitModified`, `GitRenamed`, etc in [root git column](https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/root-columns/git.ts) or `git source`

My suggestion is to change the settings to this
```jsonc
{
  "explorer.file.filename.colored.enable": {
    "anyOf": [
      {
        "type": "boolean"
      },
      {
        "type": "object",
        "properties": {
          "diagnosticError": {
            "type": "boolean"
          },
          "diagnosticWarning": {
            "type": "boolean"
          },
          "git": {
            "type": "boolean"
          }
        }
      }
    ],
    "default": false
  }
}
```

As for highlights, we can use `hlGroupManager.linkGroup` and `hlGroupManager.group` to define in the code. no longer need to inherit `diagnosticError`, `gitUnstaged`, etc.

**Comment by MonliH** [comment]
> Indeed, it is based on the `Comment` highlight. For colored filename, we can abandon `gitUnstaged` and `gitStaged`, we should define some highlights, E.g `FileFilenameDiagnosticError`, `FileFilenameDiagnosticWarning`, `GitModified`, `GitRenamed`, `GitAdded`... that also need to modify the highlight of git column https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/child-columns/git.ts#L49 Then in the future, we can use `GitModified`, `GitRenamed`, etc in [root git column](https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/root-columns/git.ts) or `git source`

Thanks, this cleared a lot up! And yep, I will make the git indicators different colors, too.

> My suggestion is to change the settings to this
> 
> ```js
> {
>   "explorer.file.filename.colored.enable": {
>     "anyOf": [
>       {
>         "type": "boolean"
>       },
>       {
>         "type": "object",
>         "properties": {
>           "diagnosticError": {
>             "type": "boolean"
>           },
>           "diagnosticWarning": {
>             "type": "boolean"
>           },
>           "git": {
>             "type": "boolean"
>           }
>         }
>       }
>     ],
>     "default": false
>   }
> }
> ```

I agree. It's probably better to only allow uers to toggle `git` highlights as a whole. It would be tedious to do toggle each one anyways.

> As for highlights, we can use `hlGroupManager.linkGroup` and `hlGroupManager.group` to define in the code. no longer need to inherit `diagnosticError`, `gitUnstaged`, etc.

I would add these new highlights (like `FileFilenameDiagnosticError`) to the javascript object here, right?
https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/fileSource.ts#L46

**Comment by weirongxu** [comment]
> I would add these new highlights (like FileFilenameDiagnosticError) to the javascript object here, right?
https://github.com/weirongxu/coc-explorer/blob/master/src/source/sources/file/fileSource.ts#L46

Yes, and highlights of git should be added to src/git/highlights.ts

**Comment by MonliH** [comment]
By the way, what should I make `GitMixed`, `GitAdded`, etc. inherit from? Would `Operator` be good? ideally the user should be able to specify the colour through the config, but another way we could do this is to make our own `CocExplorerGitAddedColor` variable, which `GitMixed` inherits from. This way, themes can change the `CocExplorerGitAddedColor`. For example, like this:
```typescript
export const gitHighlights = {
    gitMixed: hl('GitAdded', 'CocExplorerGitAdded'),
};
```

**Comment by weirongxu** [comment]
I don't think it is necessary to inherit `Operator`, and `:h hl-DiffChange` is not very accurate.  We have two options. One option is that we can extract `guibg` from `DiffChange`, another option is to set the color ourselves, then `CocExplorerGitMixed` inherits from `CocExplorerGitChnaged`

```typescript
import convert from 'color-convert';
import { RGB } from 'color-convert/conversions';

const hl = hlGroupManager.linkGroup.bind(hlGroupManager);
const gitChangedColor: RGB = [200, 200, 200];
const gitChanged = hlGroupManager.group(
  'GitChanged',
  `ctermfg=${convert.rgb.ansi256(gitChangedColor)} guifg=${gitChangedColor}`,
);

export const gitHighlights = {
  gitAdded: hl('GitAdded', gitChanged.group),
  gitChanged: hl('GitChanged', gitChanged.group),
};
```

**Comment by MonliH** [comment]
Alright, I'll try to get a PR up and running in the next week. Thanks for taking the time to clarify everything for me!

> another option is to set the color ourselves, then then `CocExplorerGitMixed` inherits from `CocExplorerGitChnaged`

I prefer this option. To be clear, `CocExploereGitMixed` would be the only highlight that inherits from another one (inherit from `CocExplorerGitChnaged`), right? and the other statuses we define ourselfs? If so, any suggestions on the colors to use?

**Comment by MonliH** [comment]
I got it working, for the most part. This is what it looks like:
<img alt="Screenshot" src="https://user-images.githubusercontent.com/30177086/97364458-01420200-189c-11eb-975b-12ffaa069b6a.png" width=350></img>

Currently, that's just with one colour for all git related statuses. I also still need to implement the configuration reading.

**Comment by weirongxu** [comment]
> I prefer this option. To be clear, CocExploereGitMixed would be the only highlight that inherits from another one (inherit from CocExplorerGitChnaged), right? and the other statuses we define ourselves? If so, any suggestions on the colours to use?

Yes.

According to vscode.

- `renamed, added, copied, untracked` is the same green, this means a change of the path.
- `mixed, modified` are both yellow, means a change of content.
- `deleted` is red.
- `ignored` is gray.

I don’t know if `ctermfg=green`, `ctermfg=yellow`, `ctermfg=gray` are suitable for us, these `ctermfg` colors should be based on the user terminal theme

**Comment by MonliH** [comment]
Yes, `ctermfg=green`, `ctermfg=yellow`, etc, may not be the best choice, although what else would we do about it? Currently, theme maintainers could change the git status color by adding a `hi GitPathChange ctermfg=123` I think.

This is how I've layed the highlights out (on my fork): https://github.com/MonliH/coc-explorer/blob/master/src/git/highlights.ts

**Comment by weirongxu** [comment]
Should be enough.

In addition, because `hlGroupManager` will automatically add a prefix, so the highlight name is `hi! CocExplorerGitPathChange ...`.

And users can also define highlights in vimrc https://github.com/weirongxu/dotvim/blob/b08b61964ee56aebf60291b0f0dc98add21cf6da/plugins-conf/coc.rc.vim#L80-L86

**Comment by MonliH** [comment]
> In addition, because `hlGroupManager` will automatically add a prefix, so the highlight name is `hi! CocExplorerGitPathChange ...`.

Yep, I noticed that, that's what I meant. 

> And users can also define highlights in vimrc https://github.com/weirongxu/dotvim/blob/b08b61964ee56aebf60291b0f0dc98add21cf6da/plugins-conf/coc.rc.vim#L80-L86

We should also document this [on the highlight wiki](https://github.com/weirongxu/coc-explorer/wiki/Highlight). I might also add in the FAQ how to change the highlight color in more detail.

**Comment by MonliH** [comment]
Also, should this feature be enabled by default of left as a configuration option? I prefer the first option, although what do you think?

**Comment by weirongxu** [comment]
I don’t recommend enabled by default now. Later I will adjust the highlights compatibility with `GitSource`, and then set it enabled by default together with explorer.file.column.git.showIgnored

**Comment by MonliH** [comment]
Closed via #299.

**Comment by alex-popov-tech** [comment]
thanks guys @MonliH @weirongxu , can't wait to see that in npm to start using :)

**Comment by MonliH** [comment]
FYI, it's on the npm version now :).

Btw, I added the docs for these hightlights added with this feature, [here](https://github.com/weirongxu/coc-explorer/wiki/Highlight#git-filename-colors). @weirongxu Let me know if you see something that's off there.

**Comment by zeitchef** [comment]
@MonliH Thanks for your work on this! Is there somewhere in the docs that explains in detail how to set this up? I see only the list of highlight groups used, but nothing that explains how best to change these in a vimrc. I'm also interested in linking other highlight groups for my needs. For example, in my vimrc I have something like this:
```
autocmd ColorScheme *
  \ hi link CocExplorerGitDeleted DiffRemoved
  \ | hi link CocExplorerGitModified jsBuiltIns
  \ | hi link CocExplorerGitAdded DiffAdded
  \ | hi link CocExplorerGitCopied DiffAdded
  \ | hi link CocExplorerGitRenamed DiffAdded
  \ | hi link CocExplorerGitIgnored Comment
```
However, this doesn't quite give me the results I'm after (and I've confirmed these highlights are set). Many thanks!

**Comment by MonliH** [comment]
Hey @zeitchef, thanks for reaching out! What are you currently seeing that's unexpected? (i.e., how's coc-explorer highlighting the files with that config you sent)?

**Comment by MonliH** [comment]
btw, this is how I've set up my highlighting, which seems to work fine for me: 
```vim
autocmd ColorScheme *
    \ highlight! link CocExplorerGitPathChange gitcommitUnmerged
    \| highlight! link CocExplorerGitContentChange Debug
    \| highlight! link CocExplorerGitDeleted gitcommitDiscardedFile
    \| highlight! link CocExplorerGitIgnored Comment
    \| highlight! link CocWarningSign Type
```

[and in my dotfiles](https://github.com/MonliH/dotfiles/blob/master/nvim/init.vim#L109)

**Comment by zeitchef** [comment]
@MonliH Thanks for your quick response! Part of the issue was that the config wasn't initially loading - after a couple of times reopening NeoVim, the configs took affect and I was seeing what I expected. So, problem solved :)
