### ISSUE TITLE
coc-settings are ignored?

### ISSUE THREAD

**Issue by alex-popov-tech** [weirongxu/coc-explorer#296]
hello!
here is part of my coc-settings config:
```
  "explorer.quitOnOpen": true,
  "explorer.file.showHiddenFiles": true,
  "explorer.file.column.git.icon.added": "✚",
  "explorer.file.column.git.icon.deleted": "✖",
  "explorer.file.column.git.icon.renamed": "➜",
  "explorer.file.column.git.icon.unmerged": "═",
  "explorer.file.column.git.icon.untracked": "?",
  "explorer.file.column.git.icon.modified": "✹",
  "explorer.file.column.git.icon.ignored": "☒",
  "explorer.icon.enableNerdfont": true,
  "explorer.floating.position": "center",
  "explorer.position": "floating",
  "explorer.openAction.for.directory": "expandOrCollapse",
```
and here is screenshot of `CocCommand explorer`
![image](https://user-images.githubusercontent.com/21224705/97223878-0ab66600-17d9-11eb-959e-61d293fab272.png)
so it seems like all my settings are ignored ( hidden files, icons, position, etc. )

why?

**Comment by weirongxu** [comment]
I can't reproduce this, did you configure an option like following

```jsonc
{
  "explorer": {}
}
```

In addition, your coc-explorer is not up to date

**Comment by alex-popov-tech** [comment]
@weirongxu thanks for the response!
Sorry, i did not get your point, but here is mine 
coc-settings - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/coc-settings.json

**Comment by weirongxu** [comment]
Are your `CocConfig` and `CocLocalConfig` command can find the location of `coc-settings.json` correctly?

**Comment by alex-popov-tech** [comment]
oops...sorry @weirongxu , i forgot to link coc-settings from dotfiles to actual location :/ 
all works now, thank you!
