### ISSUE TITLE
weird mapping

### ISSUE THREAD

**Issue by stdiopt** [weirongxu/coc-explorer#298]
There's a weird mapping since version 0.8.4 (version 0.8.3 is ok)

On explorer window
:verbose map s 
![image](https://user-images.githubusercontent.com/1675748/97318852-0fb3fd80-184b-11eb-94a8-812d8acb0e5d.png)

which causes a small delay on the regular `s` since it is expecting further key combination

**Comment by stdiopt** [comment]
Thanks for tackling the issue, and overall work on this

but something still seem to be off, now there is a "sources" binding, (I'm using release branch of coc.nvim)
![image](https://user-images.githubusercontent.com/1675748/97630359-3ec69c80-1a0e-11eb-8e14-04e4ae77a301.png)

**Comment by weirongxu** [comment]
Fixed in v0.9.1
