### ISSUE TITLE
Slowness when used in $HOME as git repo with status.showUntrackedFiles set no

### ISSUE THREAD

**Issue by hajdamak** [weirongxu/coc-explorer#302]
I am keeping my $HOME as git repo to keep track of my dotfiles.
In order for non config files to not show up in git commands listings I have following git option set:
`git  config status.showUntrackedFiles no`
This causes coc-explorer to be  slow when opened in $HOME or any of it's subdirectories. When opened in git directory of regular project it gets fast.

**Comment by hajdamak** [comment]
BTW Is there a way to disable git statuses?

**Comment by weirongxu** [comment]
> BTW Is there a way to disable git statuses?

You can edit `template` and remove git

**Comment by hajdamak** [comment]
> You can edit template and remove git

Unfortunately this does not removes slowness.
Only initial scanning is very slow and it is there regardless whether git statuses are removed from template or not.

**Comment by weirongxu** [comment]
'explorer.file.root.template', 'explorer.file.child.template', 'explorer.file.root.labelingTemplate' have git column, I will try to avoid this slowness and add a git option.

**Comment by hajdamak** [comment]
Thank you very much, now opening is fast. I see that now git statuses are
received asynchronously and show up after some time. I was wondering whether it
would be possible for explorer to respect `status.showUntrackedFiles` config the
same as git commands do? So that untraced files do not show ? sign.
BTW What causes
slowness of this status retrieval? Git commands seem to receive status very fast.

**Comment by weirongxu** [comment]
> Thank you very much, now opening is fast. I see that now git statuses are
received asynchronously and show up after some time. I was wondering whether it
would be possible for explorer to respect status.showUntrackedFiles config the
same as git commands do? So that untraced files do not show ? sign.
> BTW What causes
> slowness of this status retrieval? Git commands seem to receive status very fast.

Yes, the slowness may be the reason for the `-u` parameter, I will remove the `-u` and respect `status.showUntrackedFiles` config

**Comment by hajdamak** [comment]
> Yes, the slowness may be the reason for the -u parameter, I will remove the -u and respect status.showUntrackedFiles config

Yeah, I see now in `command.ts`, this must be it.
