### ISSUE TITLE
Explorer cannot display nerd font icons

### ISSUE THREAD

**Issue by ntta** [weirongxu/coc-explorer#305]
I'm using Ubuntu and I've set the terminal font to be Fira Code Nerd Font. It works fine on my Mac but don't know why it displays like this in Ubuntu. Encoding is already UTF-8

Neither with Nerd Font and Devicons

![Screenshot from 2020-11-07 21-28-23](https://user-images.githubusercontent.com/16453529/98438773-8b158900-2140-11eb-9a75-b99ecbff0161.png)

**Comment by weirongxu** [comment]
I'm no idea, try others terminal emulator and nerd font
