### ISSUE TITLE
[question] 使用 Startify 打开文件，icon 无法显示

### ISSUE THREAD

**Issue by SLin0218** [weirongxu/coc-explorer#307]
环境如下
```
NVIM v0.5.0-812-gd17e50879
iterm2 
macOS 10.15.7
coc 和 coc-explorer 为最新安装
```

根据 `https://github.com/fgheng/vime`
配置修改，在修 `coc-settings.json` 文件的时候，会出现图标无法显示的情况。
加多一个换行都能复现问题。
```
{
  "coc.preferences.extensionUpdateCheck": "daily",

  "suggest.acceptSuggestionOnCommitCharacter": true,
  "suggest.timeout": 5000,
  "suggest.noselect": true,
  "suggest.snippetIndicator": "  ❄",
  "suggest.completionItemKindLabels": {
    "class": "",
    "color": "",
    "constant": "",
    "default": "",
    "enum": "",
    "enumMember": "",
    "event": "鬒",
    "field": "m",
    "file": "",
    "folder": "",
    "function": "F",
    "interface": "",
    "keyword": "",
    "method": "f",
    "module": "",
    "operator": "Ψ",
    "property": "",
    "reference": "r",
    "snippet": "",
    "struct": "פּ",
    "text": "",
    "typeParameter": "",
    "unit": "",
    "value": "",
    "variable": ""
  },

  "diagnostic.signOffset": 9999,
  "diagnostic.errorSign": "■",
  "diagnostic.warningSign": "▲",
  "diagnostic.infoSign": "●",
  "diagnostic.hintSign": "●",
  "diagnostic.displayByAle": false,
  "diagnostic.maxWindowHeight": 10,

  "languageserver": {}
}
```

操作如下
1. `vim` 打开一个空 `buffer`，默认打开 `Startify`，根据序号打开一个文件
2. 如果是打开配置文件夹 (`~/.config/nvim/`) 中的文件则会出现图标无法显示，其他则不会
3. 如果在 `Startify buffer` 激活 `coc-explorer`，然后再打开配置文件目录下文件，则不会出现问题。

错误的
![image](https://user-images.githubusercontent.com/23139501/98571562-9bb83180-22ef-11eb-88d8-fcedaa5bc8c0.png)

正常的
![image](https://user-images.githubusercontent.com/23139501/98571791-db7f1900-22ef-11eb-9504-e478fcb65321.png)

**Comment by weirongxu** [comment]
> 如果是打开配置文件夹 (~/.config/nvim/) 中的文件则会出现图标无法显示，其他则不会

在这里用 `:CocLocalConfig` 能够定位到什么？

**Comment by SLin0218** [comment]
@weirongxu 不能 只能用 `CocConfig` 定位

**Comment by SLin0218** [comment]
@weirongxu  在 `~/.config/nvim` 目录，`:CocLocalConfig` 定位到
```
~/.config/nvim/.vim/coc-settings.json
{
  "python.linting.pylintEnabled": true,
  "python.linting.enabled": true
}
```

**Comment by weirongxu** [comment]
> @weirongxu 在 `~/.config/nvim` 目录，`:CocLocalConfig` 定位到
> 
> ```
> ~/.config/nvim/.vim/coc-settings.json
> {
>   "python.linting.pylintEnabled": true,
>   "python.linting.enabled": true
> }
> ```

这里没有 `explorer.icon.enableNerdfont` 选项，应该不会有影响。

可能是 coc#config 的 coc-settings.json 之间有冲突。

https://github.com/fgheng/vime/blob/b930e7704830cf092b632cd92b6025513c3860f8/config/plugins/coc.nvim.vim#L396

官方建议是不要两者同时用的，不过也不确定是不是 coc 的 bug

https://github.com/neoclide/coc.nvim/blob/df839e641b927c9424e33f8eb70d009feb1c01b3/doc/coc.txt#L1538-L1539

**Comment by SLin0218** [comment]
谢谢您，能够抽空解答。
我已经移除了 `coc-settings.json` ，统一使用 `coc#config` 。

**Comment by weirongxu** [comment]
https://github.com/neoclide/coc.nvim/issues/2597
