### ISSUE TITLE
q doesn't quit coc-explorer when there is a diagnostic error

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#316]
![image](https://user-images.githubusercontent.com/33961674/99468223-63909e80-2940-11eb-9e38-7aac218da418.png)

if I hit `enter` on a file, coc-explorer changes it's position which looks strange

![image](https://user-images.githubusercontent.com/33961674/99468284-828f3080-2940-11eb-98a2-ffc2049c7d0c.png)

**Comment by GopherJ** [comment]
basically I would like to fix:

https://github.com/weirongxu/coc-explorer/issues/121#issuecomment-593746323

which sometimes doesn't work.

if there is no error diagnostic, it works fine, but if there is then it cannot close coc-explorer correctly

**Comment by GopherJ** [comment]
Also I'm able to reproduce https://github.com/weirongxu/coc-explorer/issues/316#issue-745199670 only in some cases not always.

**Comment by weirongxu** [comment]
> if I hit enter on a file, coc-explorer changes it's position which looks strange
Currently this is the expected result, maybe you need `set splitright`

> if there is no error diagnostic, it works fine, but if there is then it cannot close coc-explorer correctly
I have tried this, but coc-explorer exited correctly
```
autocmd BufEnter * if (winnr("$") == 1 && &filetype == 'coc-explorer') | q | endif
```

**Comment by weirongxu** [comment]
If you mean that explorer cannot be closed when there are other floating windows, then this is a feature of neovim, you must use your script to close the floating window first
