### ISSUE TITLE
Possible to support 'exec' in addition / instead of 'normal'?

### ISSUE THREAD

**Issue by timhwang21** [weirongxu/coc-explorer#318]
`src/explorer.ts:335` implies that the `'normal'` global action uses `:exe "normal ..."` but this doesn't seem to be the case. My use case is that I want to bind commands including ctrl to coc-explorer shortcuts, and I cannot do that with the existing `normal`; e.g. `normal:<C-u>` does not work.

(Would it be as simple as changing the call to `await this.nvim.command('execute "normal ' + args[0] + '"');`? I'd be happy to work on this, but I'm unsure how to set up a local development environment to test.)

Thank you!

From docs:

```
			An alternative is to use |:execute|, which uses an
			expression as argument.  This allows the use of
			printable characters to represent special characters.

			Example: >
				:exe "normal \<c-w>\<c-w>"
```

**Comment by weirongxu** [comment]
The local development environment is very simple, you just need to specify the repo local path with vim-plug, and use yarn to install dependencies

**Comment by timhwang21** [comment]
Thanks, unfortunately this still doesn't work due to how `JSON.parse()` handles single backslashes. I managed to find a workaround for my use case regardless but will think about this more.

**Comment by weirongxu** [comment]
You can use double backslash in JSON string.

**Comment by timhwang21** [comment]
The target value I want after parse is `"\<C-u>"`. `JSON.parse('{ "<C-u>": "\<C-u>" }')` gives `{ '<C-u>': '<C-u>' }`. 2 and 3 backslashes fail to parse. 4 backslashes gives `{ '<C-u>': '\\<C-u>' }`. And trying to serialize the target string `JSON.stringify({ "<C-u>": "\<C-u>"})` gives `'{"<C-u>":"<C-u>"}'`.

**Comment by weirongxu** [comment]
I don't quite understand what you mean, why map `<c-u>` to `<c-u>`?

I tried this and it works.
```
{
   "w": "normal:\\<c-w>\\<c-w>"
}
```

**Comment by timhwang21** [comment]
HMM. I think I'm mistaken. When I was first setting up, it seemed like `<C-U>` did not map to pageup in the treeview. But apparently, now it works, so I don't need a binding at all. Thanks for answering my questions! :)
