### ISSUE TITLE
Random characters in explorer

### ISSUE THREAD

**Issue by jrock2004** [weirongxu/coc-explorer#32]
I have my dotfiles directory and when I open the explorer I see the following

<img width="806" alt="image" src="https://user-images.githubusercontent.com/655716/68097346-94607b80-fe84-11e9-919d-98aa3a27bf9a.png">

I ran :CocCommand workspace.showOutput and nothing shows up when I open the explorer. So not sure why its doing it.

**Comment by weirongxu** [comment]
Provide the vim version, and `:CocOpenLog` output

**Comment by jrock2004** [comment]
Well it looks like I closed neovim and opened it again. This time it shows me the output. Sorry, going to close
