### ISSUE TITLE
Is there a shortcut key that displays the details?

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#320]
Hello, Is there a shortcut key that displays the details rather than automatically? I don't want it to automatically display the float window, It would be nice if there were shortcuts that could be temporarily displayed the detail info in float window.
![image](https://user-images.githubusercontent.com/50551377/100430411-b81ae300-30d1-11eb-8767-a1ed580ae834.png)

**Comment by weirongxu** [comment]
I'm refactoring the preview feature, I will add this.

**Comment by fgheng** [comment]
thank you.

**Comment by weirongxu** [comment]
Use <kbd>il</kbd> or <kbd>ic</kbd> to open the content preview or labeling preview
