### ISSUE TITLE
Can I make it transparent when float but not change PMenu

### ISSUE THREAD

**Issue by zdmgmail** [weirongxu/coc-explorer#321]
Hope it transparent when I set explorer.floating.position

I find set `'highlight  PMenu          guibg=NONE   gui=NONE       ctermfg=255   ctermbg=239   cterm=NONE'` can do this 

but PMenu need use for other so can't set `guibg=NONE`

Is there any way to do this?

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

**Comment by zdmgmail** [comment]
> https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

sorry I'm not understand, I try `set winblend=100` but that transparent not I want ..

**Comment by zdmgmail** [comment]
> https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

solved, thanks `set winblend=30`

**Comment by weirongxu** [comment]
try `autocmd FileType coc-explorer-border set winblend=30`?

**Comment by zdmgmail** [comment]
> try `autocmd FileType coc-explorer-border set winblend=30`?

better, but this transparent will relative to vim , show some character, not like `guibg=NONE` relative to other window

**Comment by weirongxu** [comment]
try to change the background highlight, https://github.com/weirongxu/coc-explorer/wiki/Highlight#custom-highlight-example
