### ISSUE TITLE
Custom git status color?

### ISSUE THREAD

**Issue by lygamac** [weirongxu/coc-explorer#322]
I see that the git icon can be configured but the color does not.

The modified status uses highlighted yellow and it's illegible with a light theme.

![image](https://user-images.githubusercontent.com/49118209/100551669-78dfc400-3282-11eb-9c38-0cfa734f38d0.png)

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/wiki/Highlight

**Comment by lygamac** [comment]
Thanks for pointing, I didn't find that in the built-in highlight list :)
