### ISSUE TITLE
E119: Not enough arguments for function: <lambda>5

### ISSUE THREAD

**Issue by roschaefer** [weirongxu/coc-explorer#326]
When I want to abort a file rename with `Ctrl-c` (should behave the same like ESC) then I see:
```
Error detected while processing function <lambda>4[1]..<SNR>16_Cb:
line    5:
E119: Not enough arguments for function: <lambda>3
```
And from then I my coc-explorer seems broken and unresponsive, ie. I cannot open directories or navigate. Only closing neovim and restarting helps. The file information popup still shows up, though.

![2020-12-05_14-19](https://user-images.githubusercontent.com/2110676/101244125-e0739480-3704-11eb-94ba-5840417e4a40.png)

**Steps to reproduce**
Here is m `~/.config/nvim/init.vim` file:

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Initialize plugin system
call plug#end()

let mapleader=" "
nmap <leader>e :CocCommand explorer<CR>
```

Here is the output of `:CocList extensions`:
```
  * coc-explorer 0.11.4 ~/.config/coc/extensions/node_modules/coc-explorer
  + coc-tsserver 1.6.1 ~/.config/coc/extensions/node_modules/coc-tsserver
  + coc-json 1.3.2 ~/.config/coc/extensions/node_modules/coc-json
```

@issue-label-bot this is a bug

**Comment by weirongxu** [comment]
Fixed in latest coc.nvim

**Comment by roschaefer** [comment]
![2020-12-07_14-31](https://user-images.githubusercontent.com/2110676/101356769-df736c00-3898-11eb-8a2f-2d0bf6a0bac1.png)


Hey @weirongxu thank you a lot for helping me debugging this issue. I should have tried out that myself. :smile:

**Comment by weirongxu** [comment]
> Hey @weirongxu thank you a lot for helping me debugging this issue. I should have tried out that myself.

Actually, I sent a patch to coc.nvim after you report this bug.

**Comment by roschaefer** [comment]
Ah, I didn't see https://github.com/neoclide/coc.nvim/pull/2682

I'm impressed how quickly you resolved this issue :astonished: 

I discovered `coc.nvim` a couple of days ago and I like it a lot. If I wanted to contribute myself, what could be a good starting point for someone who has experience in JavaScript but never wrote vim script?

**Comment by weirongxu** [comment]
Not very easy, you need to be familiar with the basic features of vim, and know how to write **Vim script**. Because most of the `coc.nvim` code use the channel to communicate with vim. A small part of the `coc.nvim` code is logic related to LSP, but you also need to know how to write the **Typescript**
