### ISSUE TITLE
Statusline relative path not respected

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#328]
Coc-explorer changes the behavior of `set statusline=%f` from default vim.

Assuming I have the following directory structure:

```
nathan@gemini in /Users/nathan/Desktop/temp
➜ tree .
.
└── src
    └── components
        ├── hello.js
        └── world.js
````

When I open vim from the `temp` directory level, I would expect that opening the files in `src/components` would render a statusline with the following:

`src/components/hello.js` or `src/components/world.js` respectively

If I use native vim file explorer, this works correctly. When I use coc-explorer, the statusline renders the following:

`components/hello.js` or `components/world.js` respectively

It does not include the `src` segment in the path.

I've attached a `mini.vim` and a directory structure with these files in it to help reproduce:

[files.zip](https://github.com/weirongxu/coc-explorer/files/5659381/files.zip)

Also, I've added these videos to demonstrate:

### Native vim file explorer

![vim-file-explorer](https://user-images.githubusercontent.com/1323414/101487052-41e66e00-3966-11eb-94d2-c715b66c446b.gif)

### Coc-explorer

![coc-explorer](https://user-images.githubusercontent.com/1323414/101487072-490d7c00-3966-11eb-9de9-7c03f7b7ba5e.gif)

**Comment by weirongxu** [comment]
Use `"explorer.file.tabCD": false` option to change the default behavior

**Comment by npearson72** [comment]
Doesn't seem to work. It now shows the full relative path:

`~/Desktop/temp/src/components/hello.js`

It should only show:

`src/components/hello.js`

This is all I have in `coc-settings.json`:

```
{
  "explorer.file.tabCD": false
}
```

**Comment by weirongxu** [comment]
I think you also need to use relative path for open action `'explorer.openAction.relativePath': true`

**Comment by npearson72** [comment]
Yes, that did it. Thank you!
