### ISSUE TITLE
Is there a way to align git template block right?

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#329]
I would like the git markings to be justified to the right edge of the explorer window. Is this possible?

Example:

<img width="404" alt="Screen Shot 2020-12-09 at 12 05 32 AM" src="https://user-images.githubusercontent.com/1323414/101547541-1473e180-39b3-11eb-99b2-a0cb244279c9.png">

**Comment by weirongxu** [comment]
`"explorer.contentWidthType": "win-width"` and change the `explorer.file.child.template`

**Comment by npearson72** [comment]
It's very close. But for some reason the items are pushed a little too far off screen.

Here are my settings:

```
  "explorer.contentWidthType": "win-width",
  "explorer.file.child.template": "[selection | clip | 1] [indent][icon | 1] [diagnosticError & 1][filename growRight 1] [git]",
```

![Kapture 2020-12-09 at 14 00 30](https://user-images.githubusercontent.com/1323414/101627700-69513f80-3a27-11eb-93a2-feed0c45bbe2.gif)

Any ideas?

**Comment by weirongxu** [comment]
This feature will conflict with `set number`, because vim has no easy way to get the width of `number` column

**Comment by npearson72** [comment]
That was the problem. Thank you!
