### ISSUE TITLE
icon was rendered as strange character, too

### ISSUE THREAD

**Issue by yuzhen1024** [weirongxu/coc-explorer#331]
Like https://github.com/weirongxu/coc-explorer/issues/234 
![2020-12-10 20-34-00](https://user-images.githubusercontent.com/47154428/101773861-507c8300-3b28-11eb-9e5b-c8f50e300375.png)

**Comment by weirongxu** [comment]
This is a problem with your terminal or font, I can't do anything

**Comment by yuzhen1024** [comment]
> This is a problem with your terminal or font, I can't do anything

I found the cause of the problem.
I need to completely change to the nerd-fonts (in terminal option) , just install it will not fully working. 
Is this the rule of the fonts? so not a way to keep the original fonts and normally display icon?

**Comment by weirongxu** [comment]
> Is this the rule of the fonts? so not a way to keep the original fonts and normally display icon?
Yes, and a terminal only supports one font.

**Comment by jay101-STAR** [comment]
> > This is a problem with your terminal or font, I can't do anything
> 
> I found the cause of the problem. I need to completely change to the nerd-fonts (in terminal option) , just install it will not fully working. Is this the rule of the fonts? so not a way to keep the original fonts and normally display icon?

how dit you fix it?

**Comment by jay101-STAR** [comment]
> > This is a problem with your terminal or font, I can't do anything
> 
> I found the cause of the problem. I need to completely change to the nerd-fonts (in terminal option) , just install it will not fully working. Is this the rule of the fonts? so not a way to keep the original fonts and normally display icon?

I also meet with the same problem ,how did you fix it
