### ISSUE TITLE
resumeNotification not called within same tick: Error

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#334]
![image](https://user-images.githubusercontent.com/33961674/101913992-0812a300-3bc4-11eb-9a2e-015c92463999.png)

I got many errors like this while checking `:CocOpenLog`, any idea on this?

**Comment by deepak-kapoor** [comment]
![image](https://user-images.githubusercontent.com/917512/102571000-a9f23c80-413c-11eb-9475-cbf6c4622379.png)

Facing a similar issue

**Comment by iwfan** [comment]
I also encountered the same problem：

![image](https://user-images.githubusercontent.com/28853200/102624776-771d6800-417f-11eb-98da-d283d8cc7dc9.png)

**Comment by weirongxu** [comment]
Try to upgrade `coc.nvim`, Seems difficult to reproduce this issue

**Comment by GopherJ** [comment]
@weirongxu it happens on latest coc.nvim, i'll try to provide more info

**Comment by GopherJ** [comment]
![Peek 2020-12-19 16-00](https://user-images.githubusercontent.com/33961674/102692433-71716200-4213-11eb-9415-db3d55f0daec.gif)

**Comment by GopherJ** [comment]
If I go to the column `296138` I can see something like:

```
f=null!=a?a:async t=>{c.pauseNotification(),c.command(t+"wincmd w",!0),
```

and I can rigprep some lines in the code:

```
![image](https://user-images.githubusercontent.com/33961674/102692559-6a971f00-4214-11eb-88f5-fb8b94b7ecd8.png)

```
