### ISSUE TITLE
indexNext:git doesn't jump directly to modified + unstashed file/directory

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#337]
Sometimes we would like to do modifications and stash those changes while we are sure. So it's important to be able to jump directly to next `modified + unstashed` file so that we can spend more time to improve those changes which need improvements and stash them finally.

However, currently coc-explorer will also jump to stashed file/directory, sometimes we need to jump multiple times to be able to arrive at our target.

Is it possible to add mappings for jumping to next `modified + unstashed` file/directory?

**Comment by GopherJ** [comment]
Also is it possible to add symbol `S` instead of two `M` ? currently it looks like this:

![image](https://user-images.githubusercontent.com/33961674/102227432-d9f5d180-3ee9-11eb-8663-497ebff507ae.png)

when a directory is modified and has stashed + unstashed changes.

but two `M` looks strange, can we have another symbol like `S`?

**Comment by GopherJ** [comment]
also I feel the color of `modified + unstashed` file should be grey and `modified + stashed` should be yellow. I'm not sure if someone else think the same way with me

**Comment by weirongxu** [comment]
Do you mean staged / unstaged?

> also I feel the color of `modified + unstashed` file should be grey and `modified + stashed` should be yellow. I'm not sure if someone else think the same way with me

I think the user should pay more attention to unstaged stages, so unstaged should be more colorful

**Comment by weirongxu** [comment]
> Also is it possible to add symbol `S` instead of two `M` ? currently it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/33961674/102227432-d9f5d180-3ee9-11eb-8663-497ebff507ae.png)
> 
> when a directory is modified and has stashed + unstashed changes.
> 
> but two `M` looks strange, can we have another symbol like `S`?

This is not only `M`, it maybe `A (added)` or `R (renamed)` etc.

**Comment by GopherJ** [comment]
@weirongxu just tried it works perfectly, thanks! If it can jump to `file + unstaged` that's even better, but now it's already much better
