### ISSUE TITLE
[enhancement] first launch can be very slow

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#339]
![Peek 2020-12-19 19-16](https://user-images.githubusercontent.com/33961674/102696463-d9817180-422e-11eb-9b42-8b79e7499ca6.gif)

as you can see from the gif, the first launch of coc-explorer can be very slow. Let's say 4 ~ 6 seconds, I'm not sure if it's because that coc-explorer needs to wait coc.nvim? can things be async?

thanks

**Comment by weirongxu** [comment]
Yes, coc-explorer needs to wait for coc.nvim, there is no solution. #268
