### ISSUE TITLE
[Feature Request]: vim-webdevicons support

### ISSUE THREAD

**Issue by adelarsq** [weirongxu/coc-explorer#34]
[vim-webdevicons](https://github.com/ryanoasis/vim-webdevicons) allow to subscribe default icons with customized. So coc-explorer can get these custom icons by filetype and use instead of nerdfont directely.

**Comment by weirongxu** [comment]
Because `vim-devicons` doesn't support color, I still use `coc-explorer` built-in color

https://github.com/ryanoasis/vim-devicons/issues/158
