### ISSUE TITLE
is there a confige can display all file size in file name row Align right(not in single float window)?

### ISSUE THREAD

**Issue by WillDawnlll** [weirongxu/coc-explorer#342]
i want to use this to replace far manager , but can see all size .....

**Comment by weirongxu** [comment]
Use the template https://github.com/weirongxu/coc-explorer#template-grammar

**Comment by WillDawnlll** [comment]
thanks a lot , i skip these 2 description place ...not understandd  2 config work for....i will read it again....

**Comment by WillDawnlll** [comment]
...another question.....now i figure out  about set new  action and keymap ,thank u again , can i use  file size info to re sort all file in one foler node....(not understand use coc list to get file info  display rows)

**Comment by weirongxu** [comment]
> ...another question.....now i figure out about set new action and keymap ,thank u again , can i use file size info to re sort all file in one foler node....(not understand use coc list to get file info display rows)

Not support yet, there is the related issue, https://github.com/weirongxu/coc-explorer/issues/94

**Comment by WillDawnlll** [comment]
gotit，thanks for ur plug and  answers
