### ISSUE TITLE
is this  can show a  user custom menu (or  create new action about custom shell command in coc-setting.json)?

### ISSUE THREAD

**Issue by WillDawnlll** [weirongxu/coc-explorer#343]
like vscode mouse right button menu, every one  can put some custom  command in there ...
i`m not family about coc devlop , maybe you guys have some suggestion about learn it ....so i can write code by myself....thanks...

**Comment by WillDawnlll** [comment]
sorry , forget ask about custom action and  map, in  custom mappings (coc-setting.json), can i  post some shell command in a new action  , and  create new keymapping ?

**Comment by weirongxu** [comment]
> sorry , forget ask about custom action and map, in custom mappings (coc-setting.json), can i post some shell command in a new action , then create new keymapping ?

https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

> like vscode mouse right button menu, every one can put some custom command in there ...
> i`m not family about coc devlop , maybe you guys have some suggestion about learn it ....so i can write code by myself....thanks...

Try use <kbd>&lt;tab&gt;</kbd> to open the actionMenu

**Comment by WillDawnlll** [comment]
thanks...

**Comment by WillDawnlll** [comment]
...frequently use actionMenu, but is there any way  allow  create new action?(to display in actionMenu)...i search about coc action , but just get a extension , and coc.nvim help file  said actions provide by extension , and some fixed command...

**Comment by WillDawnlll** [comment]
...if no method to do it , may u list some url (or just key word i will do search )about coc  and vim float windows api (list preview tab window in coc-explorer) , i want to try a plug about it.....thank u ...

**Comment by weirongxu** [comment]
https://github.com/kizza/actionmenu.nvim
https://github.com/skywind3000/quickmenu.vim
https://github.com/weirongxu/coc-explorer/wiki

**Comment by WillDawnlll** [comment]
thanks， I used quickmenu  but  not  another,   will  try it work with  explorer.....

**Comment by weirongxu** [comment]
Seems quickmenu is very old, maybe you need the https://github.com/skywind3000/vim-quickui

**Comment by WillDawnlll** [comment]
yes!!!this plug is the one!! tnanks for these recomend !!
