### ISSUE TITLE
Two version of explorer active?

### ISSUE THREAD

**Issue by AdamBD** [weirongxu/coc-explorer#344]
I seem to have two versions of coc-explorer. Anyone can tell me how this might have happened and whats best to do here? Also what does `RTP` mean?

![image](https://user-images.githubusercontent.com/1134525/103016730-32147f80-454b-11eb-9a94-75a31e63ab79.png)

**Comment by weirongxu** [comment]
Pay attention to RTP, means it is installed to `runtimepath` by plugin manager (e.g. vim-plug).

**Comment by AdamBD** [comment]
Interesting I only installed coc.nvim itself via vim-plug and all extensions via Coc commands directly...

**Comment by weirongxu** [comment]
Oooh sorry, I didn’t notice that it come from the same directory, then I think this maybe a bug of `coc.nvim`

**Comment by AdamBD** [comment]
should this issue be re-opened or it will be caught now with the tag you added?

**Comment by weirongxu** [comment]
I think you can create issue on coc.nvim, because coc-snippets has the same problem
