### ISSUE TITLE
Doesn't behave well with vim sessions.

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [weirongxu/coc-explorer#347]
Hi!

Thanks for the amazing plugin, I really like it and have been using it almost since birth :)

I wanted some help with the behaviour that happens when re-opening a session that includes coc-explorer open.

Currently when opening a session the files are opened correctly but coc-explorer is a blank panel and when reopening coc-explorer it doesn't respect the explorer settings in vimrc e.g. it has numbers.

Cheers!

**Comment by weirongxu** [comment]
Duplicate of #297
