### ISSUE TITLE
Use root directory name as tab page label

### ISSUE THREAD

**Issue by vatosarmat** [weirongxu/coc-explorer#348]
If project opened with this command `cnoreabbrev cop tabe \| CocCommand explorer` then its tab has label `[coc-explorer]-1`, next is `[coc-explorer]-2`, `[coc-explorer]-3`, and so on. How to make project tab page to have its rood directory name as the label?

**Comment by weirongxu** [comment]
Because vim `tabline` displays the title based on the `bufname`, this feature will have a large change in the coc-explorer. It needs to save the explorer in different buffers by directories. I don't know there is a better solution or not.

**Comment by vatosarmat** [comment]
Better solution is to use the .git directory instead of the coc-explorer root directory as the project root marker. I apologize for the noise and share my solution here in case another vim newbie accustomed to "Open project" action in IDE's wants to ask a similar question

```vim
function! MyTabLabel(n) abort
  let buflist = tabpagebuflist(a:n)
  for bid in buflist
    let btp = getbufvar(bid,'&buftype')
    if btp == ""
      let bname = bufname(bid)
      if filereadable(bname)
        let gitDir = FugitiveExtractGitDir(bname)
        return fnamemodify(gitDir, ':h:t')
      endif
    endif
  endfor
  let winnr = tabpagewinnr(a:n)
  return bufname(buflist[winnr - 1])
endfunction

function! MyTabLine() abort
  let s = ''
  for i in range(tabpagenr('$'))
    " select the highlighting
    if i + 1 == tabpagenr()
      let s .= '%#TabLineSel#'
    else
      let s .= '%#TabLine#'
    endif

    " set the tab page number (for mouse clicks)
    let s .= '%' . (i + 1) . 'T'

    " the label is made by MyTabLabel()
    let s .= ' %{MyTabLabel(' . (i + 1) . ')} '
  endfor

  " after the last tab fill with TabLineFill and reset tab page nr
  let s .= '%#TabLineFill#%T'

  " right-align the label to close the current tab page
  if tabpagenr('$') > 1
    let s .= '%=%#TabLine#%999Xclose'
  endif

  return s
endfunction

set tabline=%!MyTabLine()

```
