### ISSUE TITLE
addFile keybinding delay

### ISSUE THREAD

**Issue by vyorkin** [weirongxu/coc-explorer#350]
Hi! I'm trying to use coc-explorer instead of NERDTree and I've noticed one small issue.
Currently, it seems that if I press `a` in coc-explorer then vim/neovim by default will wait for a `ttimeoutlen` number of milliseconds for a second key (`i` or `l` according to the default keybindings). So for example, if I quickly press `a` and then immediately start typing a filename then I'll get the first (few) character(s) missing.

```
:verbose nnoremap a
```

```
n al @<Plug>(coc-explorer-key-n-al)
Last set from ~/.config/coc/extensions/node_modules/coc-explorer/autoload/coc_explorer/mappings.vim line 13

n ai @<Plug>(coc-explorer-key-n-ai)
Last set from ~/.config/coc/extensions/node_modules/coc-explorer/autoload/coc_explorer/mappings.vim line 13

n a @<Plug>(coc-explorer-key-n-a)
Last set from ~/.config/coc/extensions/node_modules/coc-explorer/autoload/coc_explorer/mappings.vim line 13
```

Is it possible to override this (disable `al` and `ai` in my config) somehow?

**Comment by vyorkin** [comment]
I've figured it out. It is possible to set `explorer.keyMappings.global` and set `"explorer.keyMappingMode": "none"`

**Comment by weirongxu** [comment]
Fixed
