### ISSUE TITLE
Failed to install on windows

### ISSUE THREAD

**Issue by dianlujitao** [weirongxu/coc-explorer#351]
The error looks pretty weird to me
```
npm ERR! code ERESOLVE 
npm ERR! Cannot destructure property 'name' of 'node' as it is null.
```
Installs fine on Linux with the same npm/node version
[full logs](http://fars.ee/gDk7)

**Comment by weirongxu** [comment]
I also use the same version of npm / node in windows, but can't reproduce. You should try using `npm cache clean --force` to clear the cache. If still doesn’t work, you can clear `node_modules` and try `yarn` or `pnpm` as alternatives.

**Comment by weirongxu** [comment]
https://github.com/neoclide/coc.nvim/issues/2622#issuecomment-730247732
Note: maybe node v15 doesn't support `https-proxy-agent`

**Comment by dianlujitao** [comment]
But I'm not using an http proxy...

**Comment by weirongxu** [comment]
Clear the cache, or change the version of npm, may help?

**Comment by dianlujitao** [comment]
`npm cache clean --force` didn't help but downgrading node to v14.15.3 and npm to 6.14.9 resolved the issue.

**Comment by weirongxu** [comment]
Ok, after I cleared the cache, I can reproduce the problem, but seems it's a bug of npm
