### ISSUE TITLE
floating preview report error , look like path wrong....

### ISSUE THREAD

**Issue by WillDawnlll** [weirongxu/coc-explorer#352]
![图片](https://user-images.githubusercontent.com/28567110/103396960-fa23c280-4b70-11eb-85df-1d93b65a3be9.png)

bug operat:
open gvim , cd file's folder , e file_path, CocCommmand coc-explorer , Ic or ic
yp, or  `CocAction('runCommand', 'explorer.getNodeInfo', 0)['fullpath']`  work  good...

**Comment by weirongxu** [comment]
Are you using the latest version of coc-explorer? I cannot reproduce.
