### ISSUE TITLE
resourceOperation edits didn't redraw coc-explorer node

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#353]
While testing [this feature](https://github.com/rust-analyzer/rust-analyzer/pull/6746) of rust-analyzer, I find that `workspace.applyEdit(CreateNewFile)` in coc-rust-analyzer didn't make coc-explorer redrawing the new file.

**Comment by GopherJ** [comment]
![Peek 2020-12-31 22-12](https://user-images.githubusercontent.com/33961674/103425839-60323900-4bb5-11eb-9bca-3a1c36618ee2.gif)

**Comment by weirongxu** [comment]
I think it should be duplicated with #161
