### ISSUE TITLE
markPrev:diagnosticWarning doesn't work

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#355]
Hi, is it normal that `makrPrev:diagnosticWarning` doesn't work, I need it because I've binded:

![image](https://user-images.githubusercontent.com/33961674/103523770-aa007500-4e7c-11eb-9bb1-35a1ffdd9933.png)

I do it like this so that I can focus on `erros` most of the time and solve `warnings` at last

but `<leader>J/K` doesn't work yet

**Comment by weirongxu** [comment]
It only works when the `diagnosticWarning` exists in the `template` string.
But I think we should improve this feature
