### ISSUE TITLE
Is there a way to auto refresh the explorer?

### ISSUE THREAD

**Issue by svanharmelen** [weirongxu/coc-explorer#356]
First of all thanks for this plugin! It's super useful and I really enjoy it 😃

As for my question, I'm thinking of something like `autocmd File coc-explorer %refresh_cmd%`? I know `R` allows you to do this manually when in the explorer buffer, but it would be great if it can be automated as that would also allow something like `autocmd Cursorhold * %refresh_cmd%`.

Thanks!

**Comment by weirongxu** [comment]
You can use vim API https://github.com/weirongxu/coc-explorer/wiki/Vim-API (`refresh` action), but a better way is to implement fswatcher API #161

**Comment by svanharmelen** [comment]
This command seems to work, but it triggers an error when vim starts (after that it works fine):

`autocmd FocusGained,BufEnter,CursorHold * call CocAction('runCommand', 'explorer.doAction', 'closest', ['refresh'])`

<img width="584" alt="image" src="https://user-images.githubusercontent.com/4171547/103750373-fecff700-5006-11eb-94f2-52500be727f2.png">

Any way to prevent the error when opening vim?

**Comment by svanharmelen** [comment]
Adding this to my config instead, seems to work correctly:

```
autocmd User CocDiagnosticChange,CocGitStatusChange
    \ call CocAction('runCommand', 'explorer.doAction', 'closest', ['refresh'])
```

**Comment by weirongxu** [comment]
> This command seems to work, but it triggers an error when vim starts (after that it works fine):
> 
> `autocmd FocusGained,BufEnter,CursorHold * call CocAction('runCommand', 'explorer.doAction', 'closest', ['refresh'])`
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/4171547/103750373-fecff700-5006-11eb-94f2-52500be727f2.png">
> 
> Any way to prevent the error when opening vim?

:h CocNvimInit

**Comment by svanharmelen** [comment]
I now see these errors every now an then:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/4171547/103760011-cc2cfb00-5014-11eb-8435-ea15d6bfb80a.png">

Should I tweak anything for that? Or am I hitting a bug?

**Comment by svanharmelen** [comment]
Ah, think I solved it by using `CocActionAsync` instead:

```
autocmd User CocDiagnosticChange,CocGitStatusChange
    \ call CocActionAsync('runCommand', 'explorer.doAction', 'closest', ['refresh'])
```

**Comment by svanharmelen** [comment]
It seems this stopped working... When I now have a couple of files with errors and go to one file to fix the errors in that file and save the file, all diagnostic info disappears from the explorer. If I then do a manual `refresh` in the explorer window, they all show up again.

Any idea what could be the cause of this? Let me know if you need more info/details...

**Comment by weirongxu** [comment]
> It seems this stopped working... When I now have a couple of files with errors and go to one file to fix the errors in that file and save the file, all diagnostic info disappears from the explorer. If I then do a manual `refresh` in the explorer window, they all show up again.
> 
> Any idea what could be the cause of this? Let me know if you need more info/details...

I can’t reproduce it. and when the `CocDiagnosticChange` and `CocGitStatusChange` events triggered, the explorer will update itself, so we don't need to write scripts to update git and diagnostic.

**Comment by svanharmelen** [comment]
Ok... So I don't actually need to add this lie then?

```
autocmd User CocDiagnosticChange,CocGitStatusChange
    \ call CocActionAsync('runCommand', 'explorer.doAction', 'closest', ['refresh'])
```

I'll remove the line and test with it again today. Will let you know the result... Thanks!
