### ISSUE TITLE
Is there a way to update the git and diagnostic info other then saving a file?

### ISSUE THREAD

**Issue by svanharmelen** [weirongxu/coc-explorer#357]
It would be super nice if this could be updated by a custom command or function so it can be part of a autocmd or keymap. Having to save the file even if a git action outside of vim already executed feels nasty...

**Comment by weirongxu** [comment]
You can manually trigger the vim user event `CocGitStatusChange`

**Comment by svanharmelen** [comment]
I'm now using this config:

```
autocmd User CocDiagnosticChange,CocGitStatusChange
    \ call CocAction('runCommand', 'explorer.doAction', 'closest', ['refresh'])
```

When making a change that triggers a diagnostic warning this shows instantly! So that is very nice 👍🏻 

Yet git changes aren't updated without saving the file first. The gutter (using `airblade/vim-gitgutter`) is properly updated without saving, so is it possible for the explorer to do the same? Or does it require the file to be saved first for git changes?

Thanks!

**Comment by weirongxu** [comment]
> Yet git changes aren't updated without saving the file first. The gutter (using `airblade/vim-gitgutter`) is properly updated without saving, so is it possible for the explorer to do the same? Or does it require the file to be saved first for git changes?

Currently explorer does not support it.

**Comment by svanharmelen** [comment]
Check... Well it works pretty well now, so all good. Thanks!
