### ISSUE TITLE
Version 0.13.11 stealing focus

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#359]
When I'm switching between the coc-explorer window and a window with an open file, coc-explorer jumps to the file location in coc-explorer. This is a very disruptive user experience.

**Comment by npearson72** [comment]
Is there a way to disable it?

**Comment by npearson72** [comment]
Seems `"explorer.file.autoReveal": false` does the trick.

**Comment by weirongxu** [comment]
I plan to disable this feature by default in the future, and let user trigger it manually using Vim API

**Comment by npearson72** [comment]
Hmm, I just realized that `"explorer.file.autoReveal": false` completely disables focusing the file when using `:CocCommand explorer --focus`

Prior to this release things were working perfectly. I could focus a file if I wanted by calling `:CocCommand explorer --focus` but if I simply changed windows from a file to coc-explorer, I would get focused.

Is there a short-term way to get things to work as they did prior to this release?

I tried this from https://github.com/weirongxu/coc-explorer/issues/360

```
nmap <Leader>er :call CocAction('runCommand','explorer.doAction','closest', ['reveal:0'], [['relative', 0,'file']])<CR>
```

But it doesn't open explorer at all.

**Comment by weirongxu** [comment]
You should use `--reveal <filepath>` to let explorer automatically expand to files when explorer opened.

`<Leader>er` use to reveal current buffer in an opened coc-explorer

**Comment by npearson72** [comment]
I've tried `CocCommand explorer --reveal expand('%:p')` but it doesn't work. Is there a trick to this?

**Comment by npearson72** [comment]
Oh, never mind. I got it to work like this:

`nnoremap <silent><leader>e :call CocAction('runCommand', 'explorer', '--reveal',  expand('%:p'))<cr>`

Thanks for your help!

**Comment by npearson72** [comment]
I got it to work like so:

`"explorer.file.autoReveal": false`

+

`nnoremap <silent><leader>e :call CocAction('runCommand', 'explorer', '--reveal',  expand('%:p'))<cr>`
