### ISSUE TITLE
[Feature Request] Open in split

### ISSUE THREAD

**Issue by Tebro** [weirongxu/coc-explorer#36]
Would be nice if there was a way to open in a normal "horizontal" split.

**Comment by xiaomabetter** [comment]
I also have this need ！  like  action  defx#do_action('open', 'botright split')   in defx.nvim

**Comment by weirongxu** [comment]
> I also have this need ！ like action defx#do_action('open', 'botright split') in defx.nvim

I tested `defx#do_action('botright split')`, but doesn't seem work very well.

defx
![image](https://user-images.githubusercontent.com/1709861/72869266-9c131c00-3d1f-11ea-8894-70a8629da13a.png)

I feel that split under the buffer is better, like this
![image](https://user-images.githubusercontent.com/1709861/72869469-586ce200-3d20-11ea-955c-0a05fa6b612a.png)

Do you think so? @xiaomabetter @Tebro

**Comment by Tebro** [comment]
I agree that the second picture is the better result.

**Comment by kuntau** [comment]
Hi maybe you're implementing this but this is what current split looks like..

![Screenshot 2020-03-03 11 28 07](https://user-images.githubusercontent.com/327489/75740437-9e1ac280-5d42-11ea-9dc0-5987aa8db6c9.png)

It's splitting the explorer pane 😅

**Comment by weirongxu** [comment]
Yes, I need to reimplement this, so i didn't close this issue yet
