### ISSUE TITLE
turning modifiable off

### ISSUE THREAD

**Issue by douglas86** [weirongxu/coc-explorer#362]
why, does coc-explorer turn modifiable off? How do you get it start with it on.

**Comment by weirongxu** [comment]
Sorry I don't quite understand what you mean. does your `modifiable` mean buffer or something else?

**Comment by douglas86** [comment]
When I try to delete a file inside of coc-explorer, vim spits out modifiable is off. in other words I can't seem to delete or edit a file in coc-explorer. So it just seems to be that buffer that is off.

**Comment by weirongxu** [comment]
I'm not sure how did you delete and edit files, please use the <kbd>?</kbd> to see the mapping help

**Comment by douglas86** [comment]
I tried that, I don't think that the problem is there. It has got something to do with the settings in coc-explorer. which I don't now how to alter. I have already tried the ?

**Comment by zweck** [comment]
> I tried that, I don't think that the problem is there. It has got something to do with the settings in coc-explorer. which I don't now how to alter. I have already tried the ?

Did you figure this out? I have the same issue

**Comment by douglas86** [comment]
No, I am still having the same issue.

**Comment by weirongxu** [comment]
Move to #363
