### ISSUE TITLE
Git status doesn't work

### ISSUE THREAD

**Issue by lbavendanos** [weirongxu/coc-explorer#364]
Hi, I just installed coc-explorer with minimal configuration but I still can't find a way to get git status to work.

My coc-settings.json
```json
{
  "explorer.icon.enableNerdfont": true,
  "explorer.icon.enableVimDevicons": false,
  "explorer.file.showHiddenFiles": true
}
```
- `neovim` version: 0.5.0-dev+nightly
- `coc-explorer` version: 0.13.11

I've been testing the older versions to see if any of them work for me. And the version that worked was `0.10.0`.

I would like you to tell me what configuration I have to perform for this feature to work, since in the documentation they indicate that this is activated by default. Thank you.

**Comment by weirongxu** [comment]
what is your git config? can you try to set the `explorer.file.git.showUntrackedFiles` to `true`?

**Comment by lbavendanos** [comment]
I had a very old version of git, so I had to update for this to work. Thanks a lot.

**Comment by ranelpadon** [comment]
@lbavendanos I have similar issue. What is your Git version now?

**Comment by ranelpadon** [comment]
You are right, my Git earlier was `2.14.3` (turned out it was released on Aug 2017!), and when I updated it to the latest (`2.31.0`), it's working indeed! Kinda unexpected since they are just minor version numbers, but the release date difference is huge. 🤦 Thanks!
