### ISSUE TITLE
Floating window leaves highlighting

### ISSUE THREAD

**Issue by VisaJE** [weirongxu/coc-explorer#366]
Splitting into new windows often leaves the appearing window highlighted in the same way as the floating window itself.
This happens with only coc-explorer installed. That is, even with the default colorscheme regardless of the video. My nvim version is 0.4.4. The highlight does not appear to the original file, even if the buffer is hidden and opened again.

https://user-images.githubusercontent.com/33459334/104358270-1840d980-5506-11eb-9cc4-e19fe5bfe4be.mp4

> runtime! archlinux.vim
> 
> call plug#begin('~/.config/nvim/plugged2')
> 
> Plug 'neoclide/coc.nvim', {'branch': 'release'}
> 
> call plug#end()
> 
> let g:python3_host_prog = "~/.envim/bin/python"
> 
> let g:coc_explorer_global_presets = {
> \   'floating': {
> \     'position': 'floating',
> \     'open-action-strategy': 'sourceWindow',
> \   },
> \ }
> 
> let mapleader =" "
> nmap <leader>nt :CocCommand explorer --preset floating<CR>

**Comment by weirongxu** [comment]
Upgrade coc-explorer and coc.nvim

**Comment by VisaJE** [comment]
Did not fix it for me. Coc-explorer 0.14.0 and coc.nvim 0.0.80-7c70fbf971 initialized with node: v15.5.1.

**Comment by weirongxu** [comment]
Could you provide a reproducible step? also, the highlighting I saw in the video seems to be correct?

**Comment by VisaJE** [comment]
Just reproduced with the given init.vim, reinstalled all coc packages, this time nightly nvim. Python is 3.9.
It seems like an almost empty folder does not cause the problem, so I used the coc installation folder. Hopefully the default colorscheme shows the error better. For me the problem has occurred on multiple computers.

https://user-images.githubusercontent.com/33459334/104463375-9904e180-55a9-11eb-894f-9e3d1c3f5097.mp4
