### ISSUE TITLE
[Question] What's the difference between dd and dD?

### ISSUE THREAD

**Issue by againxx** [weirongxu/coc-explorer#368]
Thanks for this great plugin!
I have played it around for a while, but was a little confused by the difference between `dd` - cutFile() and `dD` - cutFile(replace).
It seems that there are three modes for cutFile, i.e. toggle / append / replace. So what's the default mode for `dd` and which situation should each one be used?

Appreciate if there are some insightful explanations!

**Comment by weirongxu** [comment]
The default mode is toggle.

1. toggle: add or remove a mark
2. append: add a mark
3. replace: remove other marks then add a mark
