### ISSUE TITLE
[Feature Request] execute support

### ISSUE THREAD

**Issue by adelarsq** [weirongxu/coc-explorer#37]
Would be nice a feature to execute the system default application for file or directory, something like [nerdtree-execute](https://github.com/adelarsq/nerdtree-execute) does.

**Comment by weirongxu** [comment]
We already have `systemExecute` action to do this

**Comment by adelarsq** [comment]
Nice! Didn't know. I did a new map for this:

```
"explorer.keyMappings": {
    "gx": "systemExecute"
}
```

**Comment by fgheng** [comment]
would you like to add a function, this function displays a list of apps that execute the file rather than use defalut system app
