### ISSUE TITLE
Add wiki to readme

### ISSUE THREAD

**Issue by MonliH** [weirongxu/coc-explorer#370]
I was wondering whether a [wiki](https://github.com/weirongxu/coc-explorer/wiki) link could be added to the README file. When I first found this project, I couldn't figure out how to use it. Maybe a link to the [quickstart](https://github.com/weirongxu/coc-explorer/wiki/quickstart) could help.

**Comment by weirongxu** [comment]
Yes, but we need to add some presets declaration and description in the quickstart.
