### ISSUE TITLE
[Feature] Please support new file template

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#372]
Please support the file template.
Using hpp file as an example.
If I create a new hpp file such list.hpp, the new file will create by the template:
```
#ifndef __${filename}__
#define __${filename}__

#endif
```
open list.hpp, it will show
```
#ifndef __LIST__
#define __LIST__

#endif
```

**Comment by weirongxu** [comment]
Why not use other plugins? like vim-template, it maybe beyond the scope of coc-explorer.

**Comment by fgheng** [comment]
Thank you, I will try this plugin
