### ISSUE TITLE
How to use dot key to toggle the hidden file?

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#374]
Hello, I config coc-explorer by using `call coc#config()`.
I want to use the dot key to toggle the hidden file, I write as below, but it not works.

![image](https://user-images.githubusercontent.com/50551377/105575716-9031be00-5da8-11eb-82b2-5f30b2b35144.png)

**Comment by weirongxu** [comment]
I think you can use `.` directly
```
'.': 'toggleHidden'
```

**Comment by fgheng** [comment]
It does not work if I use `.` directly,
An error occurs.
![image](https://user-images.githubusercontent.com/50551377/105619528-5e633a80-5e2e-11eb-9f9d-da0857b8d82f.png)
I write this config in a `.vim` file rather than `coc-settings.json`

**Comment by weirongxu** [comment]
Looks like coc will parse `.` into object chain

**Comment by weirongxu** [comment]
maybe we should let coc.nvim support the escaped `\.`

**Comment by weirongxu** [comment]
use <dot> instead of `.
