### ISSUE TITLE
How to stop opening files with "L" key - Use for expand ONLY

### ISSUE THREAD

**Issue by vschaitu** [weirongxu/coc-explorer#376]
The default behavior of "l" seems to open file if the last item can not expand further, I don't want to open a file in the buffer. Is there a way to stop opening the file and do nothing , if "l" is no more expandable?

**Comment by weirongxu** [comment]
custom L mapping, https://github.com/weirongxu/coc-explorer#custom-mappings-example

**Comment by vschaitu** [comment]
Thanks , got the mapping! Great plugin enjoying so far
