### ISSUE TITLE
Files aren't being highlighted for diagnostic errors

### ISSUE THREAD

**Issue by daedsidog** [weirongxu/coc-explorer#377]
I'm using the default template and have the following diagnostic error:

![image](https://user-images.githubusercontent.com/41439659/106024578-97223e80-60d0-11eb-883a-0e3630bf4231.png)
![image](https://user-images.githubusercontent.com/41439659/106024646-a6a18780-60d0-11eb-82a3-7ad472d18ee1.png)

However, the explorer only highlights the git status and completely disregards the diagnostic status:

![image](https://user-images.githubusercontent.com/41439659/106024809-d18bdb80-60d0-11eb-86e9-8881d0ceaf93.png)

After reading about [highlights](https://github.com/weirongxu/coc-explorer/wiki/Highlight#git-filename-colors), my first thought was that maybe the orange `CocExplorerFileDiagnosticError` and `CocExplorerFilenameDiagnosticError` highlights (I'm not sure what the difference is) inherit the orange colour from my theme, so I tried setting them to red manually, but it was still orange. Only when I set `CocExplorerGitModified` did it actually change, so it's definitely the git status and not the diagnostics status. I even tried using different themes, but the problem is always the same.

I'm using Vim on a Windows machine, here is some part of the `.vimrc` which I think may be relevant:

```
set number
set spell spelllang=en_gb
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
set guioptions=i
set encoding=utf-8
set nocompatible
" If hidden is not set, TextEdit might fail.
set hidden
" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup
" Better display for messages.
set cmdheight=2
" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=250
" Don't give |ins-completion-menu| messages.
set shortmess+=c
" Always show signcolumns.
set signcolumn=yes
set t_Co=256
```

I also tried disabling all plugins except for `nvim.coc` and the issue still prevailed. I even tried using it on Neovim.
Here is another example with `CocInfo`:

![image](https://user-images.githubusercontent.com/41439659/106323399-0d18d800-6280-11eb-84d5-6a80bbfed8c6.png)

![image](https://user-images.githubusercontent.com/41439659/106323518-39345900-6280-11eb-8279-0efc51a4b890.png)

**Comment by weirongxu** [comment]
`CocExplorerFileDiagnosticError` is the highlight of the diagnostic count, and `CocExplorerFilenameDiagnosticError` is the highlight of the filename

What is the value of your `explorer.file.child.template`?

**Comment by daedsidog** [comment]
```
{
	"coc.preferences.snippets.enable": false,
	"coc.preferences.extensionUpdateCheck": "never",

	"explorer.file.showHiddenFiles": true,
	"explorer.file.autoReveal": false,
	"explorer.file.child.template": "[git | 2][selection | clip | 1] [indent][icon | 1] [diagnosticError & 1][filename omitCenter 1][modified][readonly] [linkIcon & 1][link growRight 1 omitCenter 5]",
	"explorer.file.root.template": "[icon & 1] ([root])",
	"explorer.diagnostic.enableSubscriptNumber": true,

	"suggest.autoTrigger": "always",

	"clangd.disableCompletion": true,

	"tabnine.triggers": [" ", "-", "_"]
}

```

Default settings don't work either.

**Comment by weirongxu** [comment]
I noticed that your diagnostic count is not working anymore. It maybe a bug on windows. I will check it on windows later.

**Comment by daedsidog** [comment]
Built the latest version for Windows and nothing new.
