### ISSUE TITLE
Using `l` or `enter` key on file opens select window UI

### ISSUE THREAD

**Issue by bogdan0083** [weirongxu/coc-explorer#38]
Hello! Thank you for such an awesome plugin! :heart:

When using `l` or `Enter` key on directory everything works fine, folder opens as intented.
But when I try to open a file with `l` or `Enter` it shows the select window UI. Here's the screenshot:
<img src="https://image.prntscr.com/image/fVaSuPQuQoCIotFMc0do1w.png" />

How can I figure out what breaks the default `l` and `Enter` in `coc-explorer` buffer? Thanks!

**Comment by bogdan0083** [comment]
Here's the mappings I have for l and Enter inside `coc-explorer`:
```
> l                                   <Plug>(coc-explorer-action-n-l)   194
> <CR>                                <Plug>(coc-explorer-action-n-[cr])   194
```

**Comment by weirongxu** [comment]
This is the default behavior, means you need to press A, B, C select a window to open the file. Or you can use `explorer.openAction.strategy` to change the behavior of `open` action.

**Comment by bogdan0083** [comment]
Whoops, now I got it. Thanks!
