### ISSUE TITLE
Using <c-m> doesn't work...

### ISSUE THREAD

**Issue by svanharmelen** [weirongxu/coc-explorer#383]
I'm trying to use:

```
  "explorer.keyMappings.global": {
    "<c-m>": ["wait", "markNext:diagnosticError:diagnosticWarning"],
    "<c-n>": ["wait", "markPrev:diagnosticError:diagnosticWarning"],
  }
```

And while `<c-n>` works as expected `<c-m>` functions as an `enter` and opens de current file or directory. The funny thing is that I have also mapped `<c-n> and `<c-m>` in vim:

```
nnoremap <silent> <C-m> :call CocActionAsync('diagnosticNext')<CR>
nnoremap <silent> <C-n> :call CocActionAsync('diagnosticPrevious')<CR>

```

And those mappings works as expected. Any clue what is going on here?

**Comment by weirongxu** [comment]
> ```
> nnoremap <silent> <C-m> :call CocActionAsync('diagnosticNext')<CR>
> nnoremap <silent> <C-n> :call CocActionAsync('diagnosticPrevious')<CR>
> ```
> 
> And those mappings works as expected. Any clue what is going on here?

If you `nmap <cr> :call CocActionAsync('diagnosticNext')<CR>`
Your `<c-m>` also works, it is the way nvim works, please check `:h <cr>`

**Comment by svanharmelen** [comment]
I'm sorry, but it doesn't... I now have these mappings:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/4171547/106780214-0e634f80-6648-11eb-8efa-0ea2a86522ba.png">

And of course:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/4171547/106780265-1ae7a800-6648-11eb-9003-28d2ea7853c9.png">

And `<C-n>` works as expected in both a normal buffer and the explorer, but `<c-m>` still only works in a normal buffer and behaves as an `<CR>` in the explorer.

**Comment by weirongxu** [comment]
I mean you use `nnoremap <silent> <cr> :call CocActionAsync('diagnosticNext')<CR>` instead of the `nnoremap <silent> <Cm> :call CocActionAsync('diagnosticNext')<CR>`, `<c-m>` is also triggering `<cr>`, if you want to use `<c-m>` you should `unmap <cr>`, like this:

```
"explorer.keyMappings.global": {"<cr>": false}
```

**Comment by svanharmelen** [comment]
I get it! Thanks for the explanation!
