### ISSUE TITLE
Cannot delete file. "modifiable is off"

### ISSUE THREAD

**Issue by Tloe** [weirongxu/coc-explorer#384]
I'm trying delete a file, but getting "E21: Cannot make changes, 'modifiable' is off" if I set the buffer to modifiable with :set modifiable it says "W10: Warning: Changing a readonly file" I have full access to the folder that I am in..

**Comment by weirongxu** [comment]
Make sure you use the delete key is correct, because `d` has been changed to `df`, https://github.com/weirongxu/coc-explorer/issues/134

**Comment by Tloe** [comment]
Ah that was it. My bad.
