### ISSUE TITLE
Keybindings broken

### ISSUE THREAD

**Issue by ntrp** [weirongxu/coc-explorer#386]
I am having issues, after updating, with my keybindings.

Some of them work like for example:
`s` - open split
`a` - add file
`A` - add dir

But when I try to delete a file with `df` or `dF` I get a waiting cursor like when I am in normal buffers, it is waiting for the character to delete to instead of triggering the coc-explorer delete command.
Same for `dd`, I get "E21: Cannot make changes, 'modifiable' is off"

Versions:
- NVIM: 0.4.4
- CoC: 0.0.80-6e5a2aaeb5
- CoC.explorer: 0.15.5

p.s. I have several plugins installed, is there a way I could debug what might be causing this?

**Comment by weirongxu** [comment]
First, use `?` key or `:nmap` command to check your mapping information

**Comment by ntrp** [comment]
The mapping information is correct, this is where I found that I should use `df` and `dF`. Before I was simply using `d`.
```
n  df           @<Plug>(coc-explorer-key-n-df)
n  dd           @<Plug>(coc-explorer-key-n-dd)
n  dF           @<Plug>(coc-explorer-key-n-dF)
n  dD           @<Plug>(coc-explorer-key-n-dD)
```

**Comment by weirongxu** [comment]
What is the result of `?` ?

**Comment by ntrp** [comment]
I get the menu and the keybindings are the same:
![2021-02-04-121523_5119x2778_scrot](https://user-images.githubusercontent.com/720492/106885335-bf1e2d00-66e2-11eb-9f92-003072a3f760.png)

Some commands work, `a` for example prompts for a new file name and creates a file.

**Comment by weirongxu** [comment]
> The mapping information is correct, this is where I found that I should use `df` and `dF`. Before I was simply using `d`.
> 
> ```
> n  df           @<Plug>(coc-explorer-key-n-df)
> n  dd           @<Plug>(coc-explorer-key-n-dd)
> n  dF           @<Plug>(coc-explorer-key-n-dF)
> n  dD           @<Plug>(coc-explorer-key-n-dD)
> ```

Are these the results of `:nmap d`? no other plugin `nmap df` anymore?

**Comment by ntrp** [comment]
Only surround
```
n  df           @<Plug>(coc-explorer-key-n-df)
n  dd           @<Plug>(coc-explorer-key-n-dd)
n  dF           @<Plug>(coc-explorer-key-n-dF)
n  dD           @<Plug>(coc-explorer-key-n-dD)
n  ds            <Plug>Dsurround
```
But it's binding only `ds`

**Comment by weirongxu** [comment]
Did you set the 'timeoutlen' or 'tm' option?

**Comment by ntrp** [comment]
Currently I have it set to 100

**Comment by weirongxu** [comment]
Ok.. Looks like this can't be reproduced.

Try mini_vimrc and help me find a simple way to reproduce
```
git clone git@github.com:weirongxu/coc-explorer.git
npm install -g yarn
yarn
cd coc-exploer/mini_vimrc
nvim -u mini.vim
```

**Comment by ntrp** [comment]
It works with the minimal installation, must be some clashing with another plugin. How can I find out which one since the keybindings seem not to clash?

p.s. I needed to clone also coc-vim and run a :CocInstall coc-explorer before being able to test it.

**Comment by weirongxu** [comment]
You can use binary search on plugins and options via comments
