### ISSUE TITLE
[Feature Request] Separate file and folder actions for <cr>

### ISSUE THREAD

**Issue by jason0x43** [weirongxu/coc-explorer#39]
In at least some other tree plugins (ones that have apparently formed a strong muscle memory for me 😄), hitting `cr` on a file opens it, and hitting `cr` on a folder will expand or collapse it. It would be nice if coc-explorer had an option to enable that behavior; maybe separate file and folder actions for `cr`, or an option to change what "open" does by default with folders.

**Comment by weirongxu** [comment]
I don't want to add too many action, Maybe I can support some `logical action` into mappings.
Like this?
```
{
  "<cr>": [
    "isExpandable",
    "expandOrShrink", // is directory
    "open" // is file
  ]
}
```

**Comment by jason0x43** [comment]
So the value of `"<cr>"` would mean something like `[ test, action-if-true, action-if-false ]`? That would probably work.

What about adding another config property that would modify the behavior of the `open` action on directories? Something like `file.toggleDirectoryOnOpen`, which when set to true would cause the `open` action to open files, and to expand or shrink directories? That wouldn't require any new mappings or actions.

**Comment by weirongxu** [comment]
OK, I will add a similar config property `explorer.openAction.changeDirectory`, you can set it to `false` to implement your feature.
