### ISSUE TITLE
Feature Request: Run a custom command on a folder or a file.

### ISSUE THREAD

**Issue by yassinebridi** [weirongxu/coc-explorer#391]
It would be cool to have an option to execute a certain command or a script for a particular file or folder, an example usage would be:
- Open the current selected folder in a new tmux window.
- Open the current selected file in a particular program.

**Comment by weirongxu** [comment]
You can consider using Vim API, see here https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks
