### ISSUE TITLE
`autocmd ColorScheme * hi CocExplorerIndentLine cterm=NONE gui=NONE` not working

### ISSUE THREAD

**Issue by Congee** [weirongxu/coc-explorer#393]
Manually execute `hi CocExplorerIndentLine cterm=NONE gui=NONE` in the left file list panel works for me. But adding it to ~/.nvimrc does nothing.

The output of `:hi CocExplorerIndentLine` is always `CocExplorerIndentLine xxx links to Comment ` unless I manually execute the `:hi` call to change it.

To give you more context, I am trying to clear the italic style somehow appear with Alacritty. The Gnome Terminal app does not show italic indent lines.

coc-explorer version 0.15.6

Can anyone please help to override the default `CocExplorerIndentLine`?

**Comment by Congee** [comment]
Adding some color make it work, like to guifg.

`hi CocExplorerIndentLine cterm=NONE guifg=#303030`

Note there is no `autocmd ColorScheme *`

**Comment by weirongxu** [comment]
This is how vim works, because your theme plugin executed the `:hi clear`.

Please use `autocmd ColorScheme *`

**Comment by Congee** [comment]
Ummm, I simply couldn't get it working with `autocmd ColorScheme *`

**Comment by weirongxu** [comment]
What is your whole commdn? Looks like your command has a typo.

autocmd ColorScheme * hi CocExplorerIndentLine cterm=NONE _**gui**_=NONE

**Comment by weirongxu** [comment]
After my test

```
autocmd ColorScheme * hi CocExplorerIndentLine guifg=NONE
```
Does not work, because this will be overwritten by `hi default CocExplorerIndentLine ...`

but
```
autocmd ColorScheme * hi CocExplorerIndentLine guifg=#321
```
Will not be overwritten

**Comment by Congee** [comment]
In general I don't think this is a big issue and believe it's a corner case due to my environment. So, I just posted an issue for others who come from a search engine.

The original problem is those indent lines in CocExplorer are italic. So I want to change vim style settings for them.

`autocmd ColorScheme * hi CocExplorerIndentLine guifg=#321` does not work for me due to `autocmd ColorScheme *`
`autocmd ColorScheme * hi CocExplorerIndentLine guifg=None` does notwork due to `guifg=None`
`hi CocExplorerIndentLine guifg=#321` works for me.

My environment is Ubuntu 20.04, Alacritty 0.7.2, neovim 0.4.3

Like I mentioned before, Gnome Terminal does not have the italic issue at all. Alacritty on windows does not have this issue either. So, no wonder you cannot reproduce it.

Alacritty is known to have some issues with fonts like font fallback configuration is unavailable now. I'm not sure if it's related.

Finally, I don't expect any fix. Maybe some documentation or wiki could help others.

**Comment by Congee** [comment]
Thank you for the amazing plugin!
