### ISSUE TITLE
Refreshing explorer if files were added/deleted externally

### ISSUE THREAD

**Issue by daedsidog** [weirongxu/coc-explorer#395]
Currently if I add files to the workspace manually using shell, `coc-explorer` will not recognise them until I refresh manually.

This is despite having `autocmd User CocDiagnosticChange,CocGitStatusChange call CocActionAsync('runCommand', 'explorer.doAction', 'closest', ['refresh'])
` in my `.vimrc`.

**Comment by weirongxu** [comment]
Duplicate of #161
