### ISSUE TITLE
Hide files/directories according to wildignore

### ISSUE THREAD

**Issue by wavded** [weirongxu/coc-explorer#396]
Great plugin!  One thing I noticed coming from NerdTree is `coc-explorer` doesn't seem to respect the `wildignore` setting in vim to ignore those entries from the directory listing.  Possible to add?

**Comment by weirongxu** [comment]
This is possible. But we don’t give priority to implementation, and we might add new options to `explorer.file.hiddenRules`

**Comment by zejr** [comment]
hot to use `explorer.file.hiddenRules` ?

**Comment by weirongxu** [comment]
> how to use `explorer.file.hiddenRules` ?
> 
> I'm having a hard time hiding file folders, python's `__pycache__` is an example, can someone help me?

FYI https://github.com/weirongxu/coc-explorer/blob/develop/.vim/coc-settings.json#L4

**Comment by wavded** [comment]
@weirongxu I have

```
  "explorer.file.hiddenRules": {
    "filenames": ["node_modules", ".git"]
  },
```

In my global `coc-settings.json` file and I still see them show up in my explorer.  Using the latest version.

<img width="211" alt="Screen Shot 2021-03-16 at 1 17 29 PM" src="https://user-images.githubusercontent.com/26638/111359822-fe348c00-8659-11eb-8c9d-d95f83b7cc1a.png">

Am I doing something wrong?

**Comment by weirongxu** [comment]
@wavded Check out your `explorer.file.showHiddenFiles` setting

**Comment by wavded** [comment]
@weirongxu that was it, thank you!  Note, I had to set `patternMatches: []` to show the hidden files I wanted to see.

**Comment by wavded** [comment]
This workaround has been great, closing.
