### ISSUE TITLE
[Bug]: Explorer dies when buffer is deleted or coc is restarted

### ISSUE THREAD

**Issue by escorponox** [weirongxu/coc-explorer#40]
If I close the explorer buffer with `:bd` the explorer dies and I need to `:CocRestart`:

![image](https://user-images.githubusercontent.com/5127194/68463631-60cc7b00-020f-11ea-83f9-62ebae662ca6.png)

And if I restart coc with `:CocRestart` and explorer is open it gets duplicated when I open a new one:

![image](https://user-images.githubusercontent.com/5127194/68463961-f7993780-020f-11ea-98f9-8e43acee9087.png)

**Comment by ovidius72** [comment]
I see a similar issue when you source the nvim init file. The explerer gets messed up with weird characters. Doing a CocRestart rebuild the explorer.

![image](https://user-images.githubusercontent.com/3592928/68623005-bafd6280-04d3-11ea-8d2d-fdc2983f5dbb.png)

**Comment by weirongxu** [comment]
I have noticed some similar issues, highlight not work, or the buffer is deleted. 
After I finished the code refactor #27, I will spend some time to look at these issues.
