### ISSUE TITLE
gitStage doesn't work anymore

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#400]
Hi, recently it seems that gitStage stopped working, am I the only one who had this issue?

**Comment by weirongxu** [comment]
I tested on the latest version of coc.nvim and explorer, but cannot be reproduced

**Comment by GopherJ** [comment]
@weirongxu I tested again and it seems you are right, it's caused by my `>>>` `<<<` mappings in `.vimrc`
