### ISSUE TITLE
How to move node or directory 

### ISSUE THREAD

**Issue by amrbenattia** [weirongxu/coc-explorer#402]
I looked for command to move node or directory to another directory or level. I could not find such thing. 
is there a solution for that? 

thanks

**Comment by MagicDuck** [comment]
you can do try the following:
`dd` on the file/dir you want to cut
go to new parent dir
`p` to paste

You can see these commands if you press `?`

**Comment by weirongxu** [comment]
Press `r` to use the `rename` action, or as @MagicDuck said, use `dd` and `p`.
