### ISSUE TITLE
Cannot disable tabCD using setting

### ISSUE THREAD

**Issue by Yeboster** [weirongxu/coc-explorer#404]
I am trying to disable pwd changes when selecting a folder with `<cr>`.
I've removed not related coc-settings and leaved only:
```json
{
  "explorer.file.tabCD": false
}
```
Note: I have restarted the Coc after I changed the settings.

Here is a demo:

https://user-images.githubusercontent.com/23556525/112003453-35ef7800-8b21-11eb-9bed-d0db73e1e44a.mov

I have also tried to change the `explorer.keyMappings.global` by removing the option `cd` from the setting `"<cr>": ["wait", "expandable?", "cd", "open"],` but still no luck.

**Comment by weirongxu** [comment]
This is the expected, when tabCD is turned on, `coc-explorer` will use `:tcd`, otherwise use `:cd`

**Comment by Yeboster** [comment]
Is there a way to disable cd changes at all ? I'd like to use fzf on the project path and then change the folder in coc-explorer but  instead of expanding the tree, opening the folder (so the tree is less nested). 
I'll check if using tabCD I can still extract the project path so fzf search are independent
