### ISSUE TITLE
[feature or bug?] dev icon color

### ISSUE THREAD

**Issue by amit777** [weirongxu/coc-explorer#407]
I have
```json
{
 "explorer.icon.enableVimDevicons": true,
  "explorer.icon.enableNerdfont": true
}
```
https://github.com/weirongxu/coc-explorer/wiki/Screenshot seems to show custom colors for files even with Dev Icons.  I saw a ticket that says coc-explorer doesn't support color with dev icons, but that screenshot looks like it does?

https://github.com/weirongxu/coc-explorer/issues/34
https://github.com/weirongxu/coc-explorer/issues/203
https://github.com/weirongxu/coc-explorer/wiki/FAQ#why-my-file-icon-has-not-color

**Comment by weirongxu** [comment]
https://github.com/ryanoasis/vim-devicons has no built-in colors support, so if you use devicons, it doesn't support colors

**Comment by weirongxu** [comment]
Explorer uses own icon and color, but it cannot match with devicons.

https://github.com/weirongxu/coc-explorer/blob/master/src/icon/icons.nerdfont.json

**Comment by Frederick888** [comment]
Just wanna drop a note for devicons users: there is https://github.com/lambdalisue/glyph-palette.vim

```vim
augroup my-glyph-palette
  autocmd!
  autocmd FileType nerdtree,fern,startify,coc-explorer call glyph_palette#apply()
augroup end
```
