### ISSUE TITLE
[question] How to use search to find exact match?

### ISSUE THREAD

**Issue by amit777** [weirongxu/coc-explorer#408]
Is it possible to limit the fuzzy search to exact match?

**Comment by weirongxu** [comment]
Do you mean `search` action?

**Comment by amit777** [comment]
yes, exactly.

**Comment by weirongxu** [comment]
I've rewrite the `search` action, examples for exact match:

`search:strict`
`search:strict:recursive`

**Comment by amit777** [comment]
hi, I changed my coc-settings.json with this:
```
    "F": "search:strict", // was f
    "f": "search:strict:recursive", // F
```

The problem is f does not do recursive search.  it seems to just be doing search:strict.

**Comment by weirongxu** [comment]
> hi, I changed my coc-settings.json with this:
> 
> ```
>     "F": "search:strict", // was f
>     "f": "search:strict:recursive", // F
> ```
> 
> The problem is f does not do recursive search. it seems to just be doing search:strict.

Sorry, should be `search:strict|recursive`
