### ISSUE TITLE
[question]  How to customize the status line in

### ISSUE THREAD

**Issue by amit777** [weirongxu/coc-explorer#409]
Currently it says "Coc-Explorer".  Would it be possible to display some metadata about the file/directory that the cursor is above?  similar to the information in the hover label preview.   Maybe just filesize, and last modified.

**Comment by weirongxu** [comment]
use the Vim API, https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorergetnodeinfo, or `preview` action
