### ISSUE TITLE
Set setting in .vimrc rather than coc-settings.json file

### ISSUE THREAD

**Issue by mrded** [weirongxu/coc-explorer#41]
I have `vim` and `coc` settings, [very nicely split up by multiple files per extension](https://github.com/mrded/dotfiles/tree/master/.vim/plugin_settings).  I don't really like an idea of keeping everything in a one file, [which I cannot even move into a directory I like](https://github.com/neoclide/coc.nvim/issues/762).

I would prefer a possibility to write settings, which are currently in `coc-settings.json`, right in `.vimrc`, so I can break it up as I like.

If that is not currently possible, can I propose a feature request? Thanks.

**Comment by weirongxu** [comment]
I think you can split it by yourself.

```vim
" common.vim
let g:coc_common = {
      \   "coc.preferences.currentFunctionSymbolAutoUpdate": v:true,
      \   "coc.source.ultisnips.priority": 10,
      \   "coc.source.buffer.priority": 5,
      \   "coc.source.word.priority": 1,
      \ }
" explorer.vim
let g:coc_explorer = {
      \   "explorer.icon.enableNerdfont": v:true,
      \   "explorer.keyMappings": {
      \     "<space>": "normal:j"
      \   },
      \ }

let g:coc_user_config = extend(g:coc_common, g:coc_explorer)
```
