### ISSUE TITLE
Custom keyMappings merge instead of replace.

### ISSUE THREAD

**Issue by luisdavim** [weirongxu/coc-explorer#412]
Maybe I'm doing something wrong but I just wanted to override just a subset of the default key mappings so I set something like this in my `coc-settings.json`

```json
{
  "explorer.keyMappings.global": {
    "v": "open:vsplit",
  }
}
```

but once I did that all the other key mappings stopped working, I'm guessing that this overwrites the whole object instead of merging it with the default key mappings, is there a way to achieve what I'm looking for?

**Comment by weirongxu** [comment]
I tested this option, but the other keys didn't stop working.

**Comment by weirongxu** [comment]
Check `explorer.keyMappingMode` option, or update `coc.nvim` and `coc-explorer` to the latest version and pprovide output of `CocInfo` and `CocOpenLog` and mini-vimrc

**Comment by luisdavim** [comment]
I guess it was the version I had, updating did the trick, thanks.
