### ISSUE TITLE
guidelines break when I open a folder

### ISSUE THREAD

**Issue by the-spanish-guy** [weirongxu/coc-explorer#413]
When I open a folder the guidelines are not in the right direction
![coc explorer](https://user-images.githubusercontent.com/32144508/113524157-46710b00-9583-11eb-9c86-e27f9d78bb53.png)

I use alacritty

**Comment by weirongxu** [comment]
This should be your vim theme will change the comment highlight group into italics. I suggest you change `CocExplorerIndentLine` to a custom option

```vim
autocmd ColorScheme *
  \ hi CocExplorerIndentLine guifg=#aaaaaa
```

**Comment by the-spanish-guy** [comment]
It worked! tks
