### ISSUE TITLE
file tree is weirdly presented

### ISSUE THREAD

**Issue by BIKA-C** [weirongxu/coc-explorer#416]
The file tree's indent line and folder icon are weirdly presented.  They look like they've been cut in half. I have tried using other indent char, but they did not work. The file encoding is UTF-8 and nerdfont is working properly. 
![image](https://user-images.githubusercontent.com/50717946/114291762-e7663700-9a57-11eb-94ca-0ca5265488e5.png)

**Comment by weirongxu** [comment]
Should be fixed in the latest version v0.17.1

**Comment by BIKA-C** [comment]
Thanks! The line is fixed, but the folder icons are still sadly in half  (or are they? They don't look right to me )😢.

**Comment by weirongxu** [comment]
That should be the font rendering problem of terminal, try change font or terminal

**Comment by BIKA-C** [comment]
I guess I will stick with it. I love my terminal and font🤣

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/issues/200

**Comment by BIKA-C** [comment]
Nah, mine is kind of weird. Only the folder icons are partially rendered.  I tried all commented methods, except changing the font, they did not work out for me. I am fine with it since only the folder icons are a little weird.

**Comment by BIKA-C** [comment]
Magically fixed. I changed a color scheme. Now only the selected line has the problem. 
![image](https://user-images.githubusercontent.com/50717946/114464776-32955c80-9bb4-11eb-817c-698375750959.png)

**Comment by BIKA-C** [comment]
I think this has to do with highlighting. What highlight group is used for folders?

**Comment by weirongxu** [comment]
- CocExplorerFileDirectoryExpanded
- CocExplorerFileDirectoryCollapsed

https://github.com/weirongxu/coc-explorer/wiki/Highlight#file
