### ISSUE TITLE
[question] open with current buffer path as root

### ISSUE THREAD

**Issue by escorponox** [weirongxu/coc-explorer#42]
I'm trying to open the explorer with the current buffer as root path.

I first tried the NerdTree wat with no luck on `%`:

`nnoremap ,, :CocCommand explorer --toggle --sources=buffer+,file+ --file-columns=git,selection,clip,indent,filename %<CR>`

Now trying this, also with no luck:
```
function! ExploreCurrentBufferHead()
  return ':CocCommand explorer --sources=buffer+,file+ --file-columns=git,selection,clip,indent,filename ' . expand('%:h')
endfunction

nnoremap <expr> ,, ExploreCurrentBufferHead() <CR>

```

Could you help me please?

**Comment by escorponox** [comment]
I did it!!!

```
function! ExploreCurrentBufferHead()
  return ":CocCommand explorer --sources=buffer+,file+ --file-columns=git,selection,clip,indent,filename " . expand('%:h')
endfunction
nnoremap <expr> ,, ExploreCurrentBufferHead() . "\<CR>"
```
Maybe you could implement the `%` trick... :pray:

**Comment by weirongxu** [comment]
Maybe we should support the vim expressions, like `defx.nvim`

```vim
nnoremap ,, :CocCommand explorer `expand('%:h')`<CR>
```

**Comment by weirongxu** [comment]
move to #146
