### ISSUE TITLE
Auto start coc-explorer when vim is started with a folder/directory

### ISSUE THREAD

**Issue by gerazov** [weirongxu/coc-explorer#420]
Just moved to `coc-explorer` from `NerdTree` - awesome work! :sunglasses: 

One thing I found useful was to have the file explorer autostart if vim was started with a directory, i.e. `vim .`. This can be done with the following code (adapted to `coc-explorer`:

```vim
" " have vim start coc-explorer if vim started with folder
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'CocCommand explorer' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
```

This could be added to the Wiki or README.md.

**Comment by weirongxu** [comment]
Thank you for your suggestion, there is duplicate issue here https://github.com/weirongxu/coc-explorer/issues/123

**Comment by gerazov** [comment]
Ok my bad - searched for it but didn't find it :slightly_smiling_face:
