### ISSUE TITLE
Ignoring Tagbar or Vista windows when opening files

### ISSUE THREAD

**Issue by gerazov** [weirongxu/coc-explorer#422]
Great plugin! :fireworks: 

It would be nice if coc-explorer ignored the [Tagbar](https://github.com/preservim/tagbar) or Vista windows for opening new files. Atm if only a single window with a buffer is open and Tagbar is present it asks where to open the file (A or B).

**Comment by weirongxu** [comment]
Hi @gerazov
You can use `explorer.openAction.select.filte` option to ignored the `TagBar`.

**Comment by gerazov** [comment]
Thanks for the tip. I don't know how to set this option.

I tried adding `TagBar` and `Tagbar` in the `CocConfig` but it doesn't do the trick:

```json
    "explorer.openAction.select.filter": {
        "properties": {
            "buftypes": [
                "TagBar",
            ],
            "filetypes": [
                "TagBar",
            ],
          },
        "default": {
            "buftypes": [
                "Tagbar",
                "terminal"
            ],
            "filetypes": [
              "vista_kind",
              "Tagbar",
              "qf"
            ],
        },
    },
```

**Comment by weirongxu** [comment]
You should install `coc-json`, it will guide you on how to write the coc-setting.

```
"explorer.openAction.select.filter": {
	  "buftypes": [
		    "Tagbar",
		    "terminal"
	  ],
	  "filetypes": [
		    "vista_kind",
		    "Tagbar",
		    "qf"
	  ],
},
```

**Comment by gerazov** [comment]
Thanks for the reply, but it still doesn't work. This should be in CocConfig right?

**Comment by weirongxu** [comment]
It should be the lowercase type name `tagbar`

**Comment by gerazov** [comment]
Ok great! :partying_face: 

Thanks for your help! Maybe put it in the Readme for future users :+1:

**Comment by weirongxu** [comment]
I will consider add this into the default `explorer.openAction.select.filter` option

**Comment by gerazov** [comment]
Yeah makes sense - I see you already have added Vista there :+1:

**Comment by durd07** [comment]
You'd better add `vista` beside `vista_kind` into filter.
