### ISSUE TITLE
Not showing open buffers

### ISSUE THREAD

**Issue by robertdefilippi** [weirongxu/coc-explorer#423]
Hello,

I'm trying to make coc-explorer show the current my currently open buffers, however it is just showing the files in the current directory. I cannot open the `[BUFFER]` node but I can with other nodes in the directory.

What I'm getting:
![image](https://user-images.githubusercontent.com/9288605/115890725-3d0ced00-a423-11eb-87ff-4939c5885568.png)

Showing my buffers are open:
![image](https://user-images.githubusercontent.com/9288605/115890867-6c235e80-a423-11eb-862d-f288105761c4.png)

Settings in my `coc.vim`:
![image](https://user-images.githubusercontent.com/9288605/115890915-79d8e400-a423-11eb-8f51-d3adca63894c.png)

Any suggestions on what I'm doing wrong?

Thanks,

**Comment by weirongxu** [comment]
Use `'sources': [{'name': 'buffer', 'expand': v:true}, {'name': 'file'}]` instead of `buffer` field
