### ISSUE TITLE
Update imports after moving or renaming a file

### ISSUE THREAD

**Issue by gabrielbeauchemin** [weirongxu/coc-explorer#424]
When moving or renaming a file, I would like to update all the imports of the project referencing this file.

Eg. If I move file directoryA/fileA to directoryB/fileA, and that fileB is importing fileA: import { ... } from "directoryA/fileA", I would like the import to be renamed: import {...} from "directoryB/fileA".

Is there a way to accomplish that?  I think it is a very important feature, because if a file needs to be moved/renamed and that means that 15 imports need to be changed manually, it is a huge waste of time.

Thank you very much!

**Comment by weirongxu** [comment]
coc.nvim using `watchman` to detect file change, https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#optional-install-watchman-for-file-watching

**Comment by gabrielbeauchemin** [comment]
Thank you, I have seen on coc-explorer doc that file renaming won't be supported.

I cannot find how to rename a file with only Coc with watchman. Is it that if I rename the file from outside the buffers, all the imports will automatically be updated using watchman? If not, can you provide a link please that shows how it works. I tried to understand with the link you provided without success.

Thank you very much.

**Comment by weirongxu** [comment]
it seems that only coc-tsserver has an explanation. coc.nvim use watchman to trigger a file changed  event, and then pass it to the LSP, then LSP alter the import name.

https://github.com/neoclide/coc-tsserver#features

**Comment by gabrielbeauchemin** [comment]
Thank you very much for your time!
