### ISSUE TITLE
Unexpected behaviour with openAction.strategy previousBuffer

### ISSUE THREAD

**Issue by svanharmelen** [weirongxu/coc-explorer#425]
I think the recording says it all... I would expect opening the file would use the already existing empty buffer instead of opening a new one:
https://user-images.githubusercontent.com/4171547/115986873-b9820600-a5b2-11eb-8498-2b77d786502a.mov

Funny enough when choosing the `select` strategy with only one open buffer actually does this correctly:
https://user-images.githubusercontent.com/4171547/115986827-69a33f00-a5b2-11eb-8ff2-8181b07355ef.mov

So this one was able to select the expected buffer...

**Comment by svanharmelen** [comment]
That was quick! Thanks @weirongxu, really appreciate your work!

**Comment by timtyrrell** [comment]
Awesome! Thanks for opening this issue and thank you for the quick fix! This was my biggest annoyance with the plugin 🙌

I did notice one caveat, but either way, so much improved. If you have the same file opened in two different splits, it will open the new file in the first match (as the code says). A lot of times I will do a split to create a place where I want the new file. I will start using `:new` and `vnew` instead.
