### ISSUE TITLE
Copy relative path of a file

### ISSUE THREAD

**Issue by ddiegosr** [weirongxu/coc-explorer#426]
Is there a way to copy the relative path of a file?

**Comment by weirongxu** [comment]
Not supported yet, you can use API to implement it.
https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorergetnodeinfo

**Comment by ddiegosr** [comment]
I don't how exactly use this command, do you have some example?

**Comment by ranelpadon** [comment]
I would like to have this feature as well, since most of the time while coding, relative/project paths are more relevant. Thanks

**Comment by ranelpadon** [comment]
My work around currently, for others who might be interested as well:

1. Set the path mode to be relative in `coc-settings.json`:
```json
"explorer.openAction.relativePath": true,
```

2. Set the mapping for copying the relative path of the active buffer to clipboard (current focus should be in the buffer window not in `coc-explorer` window:
```vim
nnoremap <leader>yr :let @*=expand("%")<CR>
```

The copied relative path could now be pasted.
