### ISSUE TITLE
Which Vim event to set cursorline for floating coc-explorer

### ISSUE THREAD

**Issue by fanliver** [weirongxu/coc-explorer#427]
Currently, I am using below autocmds to highlight the current line in the current window and clear the highlight in other windows.
```
au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
au WinLeave * setlocal nocursorline
```

It works well for normal windows. 
However, for floating coc-explorer, it does not work smoothly.

`cursorline` is set when opening coc-explorer floating window for the first time.
However, close coc-explorer and open it again, `cursorline` is no longer set because it was unset by the above autocmd on `WinLeave` event.

BufWinEnter does not fired when opening floating coc-explorer and WinEnter seems to be fired before the current buffer is set to `coc-explorer`, so when opening coc-explorer floating window again, `cursorline` is not set for the floating window.

Below is my test:
I opened a file, let's say `~/abc.txt`.
I tried to print out the current buffer name on `WinEnter` event:
```
au WinEnter * echom 'WinEnter: ' . expand("%")
```
Then opened coc-explorer floating window, then typed some commands as below:
```
:messages
WinEnter: <my_home>/abc.txt

:echo expand("%") 
coc-explorer-1
```

It seems that the event `WinEnter` is fired before the current buffer is changed to `coc-explorer`.

Do you have any solution for this issue?

**Comment by weirongxu** [comment]
Have you tried using filetype event? there are some example, https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

**Comment by fanliver** [comment]
I have just tried it.
```
augroup coc-explorer-test
    au!
    autocmd FileType coc-explorer setlocal cursorline
    autocmd FileType coc-explorer echom 'Event filetype coc-explorer. Current buffer is ' . expand("%")
augroup END
```
Everything worked well at the first time I opened coc-explorer floating window but not for the next times. The message `Event filetype coc-explorer. Current buffer is...` was not shown and `cursorline` is not set when I opened the floating window **again** even the `filetype` was changed to `coc-explorer`.

However, when the floating window is opened, I run command `:set filetype=coc-explorer` then it works, `cursorline` is set, the current line is highlighted and the message is shown.

**Comment by weirongxu** [comment]
I think you don't need to `set nocursorline` on WinLeave, and coc-explorer already set the `cursorline` for floating window by default...

**Comment by fanliver** [comment]
I need it because I want to highlight the line in current window only and not for other windows.

**Comment by weirongxu** [comment]
Ok, This bug caused by `nvim_open_win()`, because when you use `nvim_open_win` to open a new floating window, `WinEnter` will trigger on the previous buf, which causes a bug.

```vim
call nvim_open_win(4, v:true, {'relative': 'win', 'row': 3, 'col': 3, 'width': 12, 'height': 3})
```

Maybe we need to create an issue to neovim

**Comment by weirongxu** [comment]
And currently you can use
`au User CocExplorerOpenPost echom'CocExplorerOpenPost: '. expand("%")` to implement your feature

**Comment by fanliver** [comment]
Thank you. Let me try it and let you know the result later, after my working time. :)

**Comment by fanliver** [comment]
@weirongxu 
```
au User CocExplorerOpenPost echom 'CocExplorerOpenPost: '. expand("%")
```
This event works perfectly for me.
Thank you very much.
