### ISSUE TITLE
When icons enabled, webpack.config.js file breaks loyout.

### ISSUE THREAD

**Issue by mput** [weirongxu/coc-explorer#43]
![image](https://user-images.githubusercontent.com/1230663/68858573-6128b280-06f6-11ea-9954-cf97c95716ca.png)

I have such a bug with the layout. It's only happening with webpack.config.js for now, and if I disable icons than everything works fine. Can it be fixed somehow?

P.S. Thank you so much for this extension, I really love it!

**Comment by weirongxu** [comment]
No idea, what is your vim version?

**Comment by mput** [comment]
Seems like it's problem with fonts on windows machine.  I tried on Mac and everything was all right.
