### ISSUE TITLE
"explorer.previewAction.onHover": "content" or "labeling" will cause "explorer sources not initialized yet"

### ISSUE THREAD

**Issue by quafoo** [weirongxu/coc-explorer#432]
`"explorer.previewAction.onHover": false` works.
`"explorer.previewAction.onHover": "content"` or `"explorer.previewAction.onHover": "labeling"` will cause an error `explorer sources not initialized yet` when I tried to open coc-explorer.

**Comment by weirongxu** [comment]
Fixed
