### ISSUE TITLE
Remap `k` to `n` and `j` to `t` for navigation

### ISSUE THREAD

**Issue by Wmbat** [weirongxu/coc-explorer#439]
Hello, 

I use a dvorak keyboard layout and I was wondering if it was possible to remap the up & down navigation through `j` and `k` to some other keys like `t` and `n`? I couldn't find anything on the wiki or the readme about it.

thanks

**Comment by weirongxu** [comment]
Add your custom mappings to `s:init_explorer` https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks, or use `explorer.keyMappings.global` to change the mappings

**Comment by Wmbat** [comment]
Where can I find a list of the actions so that I can remap? Because to remap the keys, i'd need the name of the action related with navigating up or down?

Thanks

**Comment by weirongxu** [comment]
You can press `?` to show the help.
