### ISSUE TITLE
Alignment issue with git icons

### ISSUE THREAD

**Issue by hlidotbe** [weirongxu/coc-explorer#44]
Hi,

I have a weird alignment issue when files have a git status different than "nothing":

![image](https://user-images.githubusercontent.com/193949/68951138-c1365c00-07bd-11ea-967f-beffc6070ede.png)

This is the same with or without nerdfonts enabled.

My config:

```
  "explorer.quitOnOpen": true,
  "explorer.file.autoReveal": true,
  "explorer.icon.enableNerdfont": true,
  "explorer.file.column.indent.topLevel": false,
```

I tried to set the unmodified icon to a single space to force alignment but it didn't change anything.

Latest neovim on ubuntu 19.10 and kitty

**Comment by weirongxu** [comment]
It should be your some plugins that changed `conceallevel` to 1, `coc-explorer` use the conceal feature, and the `conceallevel` must be 3

**Comment by weirongxu** [comment]
If you use indentLine, please add `coc-explorer` to `g:indentLine_fileTypeExclude`

**Comment by hlidotbe** [comment]
That was indeed indentLine, thanks!
