### ISSUE TITLE
Is there a way to use nvim-web-devicons?

### ISSUE THREAD

**Issue by cjnucette** [weirongxu/coc-explorer#448]
Hi, The options  I can see are to enable either vimDevicons or NerdFont. Can nvim-web-devicons be used somehow?

**Comment by weirongxu** [comment]
Not yet, but it's not difficult to support, I'll see how to add it to `coc-explorer` later

**Comment by cjnucette** [comment]
Thanks. 👍️

**Comment by weirongxu** [comment]
```
""explorer.icon.source": "nvim-web-devicons"
```

**Comment by cjnucette** [comment]
Thanks, that was quick! 👍️

**Comment by cjnucette** [comment]
Hi, I think there is something wrong with the icons.
![Screenshot from 2021-07-08 20-51-16](https://user-images.githubusercontent.com/2278326/125007587-8d611780-e02e-11eb-8c8c-91cfa0405174.png)
`src` is a directory but gets the default icon, both `css` and `js` are subdirectories of `src` but somehow the got the filetype icon but with different colors.

**Comment by weirongxu** [comment]
Fixed on v0.18.6

**Comment by cjnucette** [comment]
Yes it is! Thanks.
