### ISSUE TITLE
浮动窗口是否有单独的背景色hi，而不是使用 Pmenu

### ISSUE THREAD

**Issue by yaocccc** [weirongxu/coc-explorer#449]
因为想实现floating窗口能透明背景色，但目前和Pmenu同一个hi，用了非常丑陋的实现方式来实现需求

            au User CocExplorerOpenPre  hi Pmenu ctermbg=NONE
            au User CocExplorerQuitPost hi Pmenu ctermbg=238
            au User CocExplorerQuitPost echo

**Comment by weirongxu** [comment]
wiki 里有 https://github.com/weirongxu/coc-explorer/wiki/Highlight#custom-highlight-example

**Comment by yaocccc** [comment]
> wiki 里有 https://github.com/weirongxu/coc-explorer/wiki/Highlight#custom-highlight-example

是这样的，我进入vim后，手动执行  hi CocExplorerNormalFloat ctermbg=none，打开 :CocCommand explorer --preset floating后，仍然是用的Pmenu的颜色配置

此时我再次 hi CocExplorerNormalFloat ctermbg=none ， 之后才会让 这个hi变成透明状态，所以目前看，第一次init CocExplorerNormalFloat 是发生在 初次开启 explorer 时。尝试了许久未找到解决方法

**Comment by weirongxu** [comment]
试试 `hi CocExplorerNormalFloat ctermbg=none guibg=none`, nvim 给 floatwin 添加 winhl 时行为有点怪

**Comment by yaocccc** [comment]
> 试试 `hi CocExplorerNormalFloat ctermbg=none guibg=none`, nvim 给 floatwin 添加 winhl 时行为有点怪

非常感谢，可以了。。。。这也是有够古怪的
