### ISSUE TITLE
When trying to add a file to a folder, `fsMkdir` breaks with EEXIST error

### ISSUE THREAD

**Issue by lucianoratamero** [weirongxu/coc-explorer#45]
If I try to add any file, with any name, to any folder (using the 'a' key), coc-explorer tries to recreate the folder using `fsMkdir` and always fails with an EEXIST error.
![image](https://user-images.githubusercontent.com/1103672/69168193-0071ef00-0ad5-11ea-9383-0fd23cc8720a.png)
It may be fixed by calling mkdir with the -p flag (--parents), since it fails siletly if the folder exists.

**Comment by weirongxu** [comment]
Could you try the latest version? I can't reproduce on it.

**Comment by lucianoratamero** [comment]
sure, will ping you back when I'm done, thanks! :)

**Comment by lucianoratamero** [comment]
so, I reinstalled coc-explorer and I tried two things.

adding a file with 'a', which gave me the EEXIST error even though the file does not exist (and I traced it to fsMkdir)
![error](https://user-images.githubusercontent.com/1103672/69359652-bf5e1400-0c67-11ea-89f7-1937da4e62fa.gif)

then, I tried to add a new directory, which worked, and then adding a new file with 'a'. same error:
![folder](https://user-images.githubusercontent.com/1103672/69359710-d56bd480-0c67-11ea-9b07-e42bdbfc98a3.gif)

all the other file operations seem solid, except this one. is there an easy way I could debug this locally?

**Comment by weirongxu** [comment]
> all the other file operations seem solid, except this one. is there an easy way I could debug this locally?

check out the [log](https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim#using-logger-module), or use Chrome to debug it, see https://github.com/weirongxu/coc-explorer/issues/15#issuecomment-535019024

**Comment by weirongxu** [comment]
Here is the code to add a file

https://github.com/weirongxu/coc-explorer/blob/9f2d633fe07f7738e5ebce0a8c3c30bf732ea027/src/source/sources/file/file-actions.ts#L382-L404

**Comment by kristijanhusak** [comment]
I have the same issue. I'm not able to create anything, file or directory. Tried debugging it, but the chrome console is not showing anything in the console. Here's screenshot:

![Screenshot](https://i.imgur.com/UN4KIGz.png)

**Comment by weirongxu** [comment]
Reproduced, the `fs.mkdir` recursive only support `node > v10.12.0`, I will fix soon

**Comment by kristijanhusak** [comment]
Works now, thanks!

**Comment by lucianoratamero** [comment]
nice, thanks so much :sparkling_heart:
