### ISSUE TITLE
How do i the background color for explorer window?

### ISSUE THREAD

**Issue by samrath2007** [weirongxu/coc-explorer#450]

**Comment by weirongxu** [comment]
1. General window
Change the `winhl` with the `init_explorer` hook
https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

2. Floating window
https://github.com/weirongxu/coc-explorer/wiki/Highlight

**Comment by samrath2007** [comment]
Sorry for the late reply but thanks! Not on my machine currently but I'll try it when i get back to it.
