### ISSUE TITLE
How do I add custom icons?

### ISSUE THREAD

**Issue by bitterjug** [weirongxu/coc-explorer#453]
I wasn't sure what the format of `customIcons` configuration key was, so I took a guess, but this is, apparently, wrong:

```json
  "explorer": {
    "icon": {
      "enableNerdfont": true,
      "enableVimDevicons": false,
      "customIcons": {
        "icons": {
          "elm": {
            "code": "",
            "color": "#1293D8"
          }
        },
        "extensions":{
          "elm": "elm"
        }
      }
    },
```

How _should_ I add the [Elm](https://elm-lang.org/) icon?

**Comment by weirongxu** [comment]
Coc-explorer already supports elm by default, you need to update your Nerdfont font.

**Comment by bitterjug** [comment]
Thanks for that quick reply!
My NerdFont includes the icon. It worked fine in NerdTree, and maybe until recently in coc-explorer too. I just noticed today I don't have icons for Elm. Nor for scss. I've put my config back as it was. Any idea what might have happened?

![image](https://user-images.githubusercontent.com/495718/124594376-9fd52880-de57-11eb-8633-deaa7345c24c.png)

**Comment by weirongxu** [comment]
![image](https://user-images.githubusercontent.com/1709861/124597197-bdc17e00-de95-11eb-9b49-0a08c630fb08.png)

It seems I can't reproduce your problem. BTW, I just fixed an icon display bug, https://github.com/weirongxu/coc-explorer/releases/tag/v0.18.5

**Comment by weirongxu** [comment]
I think already fixed this in https://github.com/weirongxu/coc-explorer/releases/tag/v0.18.5
