### ISSUE TITLE
[Feature Request] Add onCommand event in activationEvents

### ISSUE THREAD

**Issue by sainnhe** [weirongxu/coc-explorer#454]
I want to open coc-explorer together with startify on startup, so I use `CocNvimInit` event to trigger this action before.

But coc does not wait for extension ready anymore, see https://github.com/neoclide/coc.nvim/issues/3203

The author said a possible solution is adding `onCommand` event in `activationEvents`. If it doesn't have any bad effects, could you add it to package.json?

Thanks!

**Comment by weirongxu** [comment]
I will add it, and consider whether it is possible to start the extension synchronously

**Comment by weirongxu** [comment]
Added in v0.18.7

**Comment by sainnhe** [comment]
Thanks, I just tried that and I can confirm coc-explorer can be triggered via `CocNvimInit` event.

However, I found that by this way, executing `CocCommand explorer` will be very slow.

Just a discussion, I wonder if it's possible to activate this extension on startup just like the earlier versions, plus add an event like `CocExplorerInit` so users can open explorer when it's ready.

**Comment by weirongxu** [comment]
Maybe we should use synchronous instead of `onCommand`, then coc will load the explorer extension when it start.

**Comment by weirongxu** [comment]
I modified it on the `master` branch, could you try it?

**Comment by weirongxu** [comment]
> Just a discussion, I wonder if it's possible to activate this extension on startup just like the earlier versions, plus add an event like CocExplorerInit so users can open explorer when it's ready.

Because `coc.nvim` has changed its loading policy, it no longer waits for asynchronous extensions, so perhaps using synchronous to start extension is a faster way to go

**Comment by sainnhe** [comment]
> I modified it on the `master` branch, could you try it?

I just tried master branch, I can confirm that:

1. It works nicely with `CocNvimInit` event.
2. The first time to start explorer is much faster.

Thanks, from my point of view, all problems have been solved :)
