### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by escorponox** [weirongxu/coc-explorer#46]
Icons are not showing up since the last update. I even tried to install the full nerd fonts package with no luck.

https://aur.archlinux.org/packages/nerd-fonts-complete/

**Comment by weirongxu** [comment]
Show up the garbled text or something else?
Icon working for me, and I haven't changed the icon encoding.

**Comment by escorponox** [comment]
![image](https://user-images.githubusercontent.com/5127194/69410923-4b297c00-0d0c-11ea-9ec1-fdd1fc2cbfa5.png)

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer#--file-columns

Do you include the icon column in `file-columns`?

**Comment by escorponox** [comment]
Ohhhh, it works now. Thanks so much!!!

Icons were working in previous versions without explicitly setting the column config.
