### ISSUE TITLE
Is there any function i can make sure explorer is closed.

### ISSUE THREAD

**Issue by A-GG** [weirongxu/coc-explorer#460]
If coc-explorer is shown when mksession, it will crash on session resotred, so i wonder is there any way that i can make sure coc-explorer is closed, thanks.

**Comment by weirongxu** [comment]
Using the user events or CocAction?

https://github.com/weirongxu/coc-explorer#user-events

https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorergetnodeinfo
```vim
:echo CocAction('runCommand', 'explorer.getNodeInfo', 'closest')
```

**Comment by A-GG** [comment]
Ok, i'll try, maybe feedback later.

**Comment by A-GG** [comment]
It works well, thanks for replying.
