### ISSUE TITLE
Prevent next buffer from replacing explorer

### ISSUE THREAD

**Issue by nrayamajhee** [weirongxu/coc-explorer#464]
I absolutely love this extension! It is very usable however there's this one issue that has been bugging me a lot.

I have my `C-n` bound to `:bn` and `C-p` to `:bn`. Sometimes when I am in the explorer window I impulsively press C-n to go to the next buffer but instead of replacing the right window where the previous buffer was displayed, neovim replaces the window to the left where the explorer was open. Is it possible to avoid this from happening?

Here's an screencast of this happening:

![Screen-recording-2021-08-05-9032](https://user-images.githubusercontent.com/4941091/128454335-b8231881-bff6-484e-94aa-bc2c8abb650c.gif)

**Comment by weirongxu** [comment]
```jsonc
// coc-settings.json
{
  "explorer.keyMappings.global": {
    "<c-n>": "noop",
