### ISSUE TITLE
Is there a way to show all file with diagnostic sign when I open coc-explorer? 

### ISSUE THREAD

**Issue by beautiful-boyyy** [weirongxu/coc-explorer#468]
![Screenshot from 2021-08-17 11-11-39](https://user-images.githubusercontent.com/66351806/129658024-e0c84279-908c-4026-b883-c0617fb304fe.png)
![Screenshot from 2021-08-17 11-11-50](https://user-images.githubusercontent.com/66351806/129658088-f7edd810-f149-4703-a892-1006e775c2d0.png)
![Screenshot from 2021-08-17 11-11-56](https://user-images.githubusercontent.com/66351806/129658100-b627df9c-36e7-4fb4-be72-e64c34892d06.png)

The problem is when I open coc-explorer, it only shows the the current file's diagnostic result.So I wonder  is there any way to show all file with diagnostic sign when I open coc-explorer?

**Comment by weirongxu** [comment]
coc-explorer using the diagnostic list of coc.nvim, so only opened buffers are supported now.
