### ISSUE TITLE
Question: a panel position problem

### ISSUE THREAD

**Issue by black-desk** [weirongxu/coc-explorer#470]
when open coc-explorer with [airline](https://github.com/vim-airline/vim-airline)'s buffers panel([how to enable it](https://github.com/vim-airline/vim-airline#smarter-tab-line)), it looks like this:
```
   buffers
-----+---
files|code
```
![image](https://user-images.githubusercontent.com/29726878/129866427-5f6a35f2-8f7c-4096-b96c-2e5468000a2e.png)
but what I want is:
```
     |buffers
files+----
     |code
```
which is make more sence to me :)
what should I do?

**Comment by weirongxu** [comment]
Unfortunately, As far as I know, this layout is not supported in vim/nvim.

**Comment by black-desk** [comment]
Thanks
