### ISSUE TITLE
How to add a border to coc-explorer?

### ISSUE THREAD

**Issue by DevonPeroutky** [weirongxu/coc-explorer#475]
## Description
Coc-explorer is great! I just can't seem to set a border for it (Screenshot below). I've tried adding the below to my init.vim
```
autocmd FileType coc-explorer-border set winblend=30
```
as well as adding the following to my coc-settings.json
```
"explorer.floating.border.enable": true
```
But neither have worked. Even by looking at the documentation, is seems like `explorer.floating.border.enable` should be true by default anyways. Is there something I'm missing?

<img width="1792" alt="Screen Shot 2021-09-03 at 7 43 28 AM" src="https://user-images.githubusercontent.com/36947377/131999935-b269b761-3c9b-402f-b074-324e6f291b3a.png">

**Comment by weirongxu** [comment]
`explorer.floating.border.enable` only work for floating windows

```
:help "fillchars"
:set fillchars=vert:\│
```
