### ISSUE TITLE
Filetypes icons not working

### ISSUE THREAD

**Issue by ThomasTraineau** [weirongxu/coc-explorer#476]
I'm using urxvt, downloaded nerd-fonts-complete from the AUR and I am getting this result in coc-explorer
![2021-09-18-154440_1920x1080_scrot](https://user-images.githubusercontent.com/71668459/133891022-715ba43e-9437-48b9-be8a-14d68bc56711.png)
Any idea on how to fix it ? (and also is it normal that in the explorer the files are underlined and not highlighted where the cursor is positioned ?)

**Comment by weirongxu** [comment]
> I'm using urxvt, downloaded nerd-fonts-complete from the AUR and I am getting this result in coc-explorer

Please change your terminal font.

> Any idea on how to fix it ? (and also is it normal that in the explorer the files are underlined and not highlighted where the cursor is positioned ?)

That this problem of your vim theme, check out `:help 'cursorline'`

**Comment by ThomasTraineau** [comment]
Thanks for your quick answer ! However, I added this line : `URxvt.font: Hack Bold Nerd Font Complete` in my .Xresources file and I still have the same problem for the icons.

And for the cursor line, it only appears in the coc explorer and not when editing or going through files. I couldn't find how to change the parameter only for the explorer

**Comment by ThomasTraineau** [comment]
Any idea of what I am doing wrong ?

**Comment by weirongxu** [comment]
> Thanks for your quick answer ! However, I added this line : URxvt.font: Hack Bold Nerd Font Complete in my .Xresources file and I still have the same problem for the icons.

I have no experience with URxvt, but this is a terminal problem and I can't fix it.
You should check why your terminal does not display the Nerdfont.

> And for the cursor line, it only appears in the coc explorer and not when editing or going through files. I couldn't find how to change the parameter only for the explorer

You can use event hooks to change the `cursorline` option in the coc-explorer.

https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

**Comment by ThomasTraineau** [comment]
Thanks ! I'll figure it out
