### ISSUE TITLE
Search always ignores .ignore file

### ISSUE THREAD

**Issue by notpeelz** [weirongxu/coc-explorer#482]
The search function passes `showIgnore: true` to the [files ListTask](https://github.com/weirongxu/coc-explorer/blob/78b00883ae51eaf63b6cdb0c2b9560aedcbbf00a/src/source/sources/file/fileSource.ts#L313), which [forces fd to ignore](https://github.com/weirongxu/coc-explorer/blob/259d681b368dd0ea11e3b62bbb537c4eece2ef6a/src/lists/files.ts#L80) `.ignore`, `.fdignore` and `.gitignore`.

Is this intentional? It would be nice if the user had control over that setting.

**Comment by weirongxu** [comment]
This is intentional, and I've made this the default behavior, because without ignoring .gitignore, the search function will search through a lot of `node_modules` or `third-party` or `vendors` folders, making it too slow.
But we can also add an `action` argument to skip this limitation

**Comment by notpeelz** [comment]
I think you have it backwards. On my end, the search function lists a bunch of files from node_modules:
<img src="https://user-images.githubusercontent.com/920910/135837948-cf03a60a-a768-4ecc-a971-b7707c63820d.png" width="500">

**Comment by weirongxu** [comment]
Indeed, you are right, perhaps this function should be changed to ignore `node_modules` by default

**Comment by notpeelz** [comment]
Couldn't you just set [this](https://github.com/weirongxu/coc-explorer/blob/78b00883ae51eaf63b6cdb0c2b9560aedcbbf00a/src/source/sources/file/fileSource.ts#L313`) to false?

**Comment by weirongxu** [comment]
I would like to have an option to possibly let the user control whether to ignore them or not, and I will add this feature as soon as possible.

**Comment by notpeelz** [comment]
Thanks!
