### ISSUE TITLE
Add config settings for customizing icons

### ISSUE THREAD

**Issue by notpeelz** [weirongxu/coc-explorer#487]
The "readonly" icon doesn't render properly on my terminal. Would it be possible to add config settings to customize what icons to use?

![image](https://user-images.githubusercontent.com/920910/138954108-c46ebce0-6b5a-4fdf-b730-7ba89dbaabf0.png)

**Comment by weirongxu** [comment]
> Thanks, works great! Though I think it would look better with a space between the buffer name and the icon(s), i.e: `"explorer.buffer.child.template": "[git | 2] [selection | 1] [bufnr] [name] [modified][readonly] [fullpath]"`... but then it looks weird when there's no icons. Is there a way to add a space only when icons are present?
> 
> ![image](https://user-images.githubusercontent.com/920910/139455447-060ec695-68d4-4bf0-88b9-36c9a21aa644.png)

Yes, I need to design a syntax like `[git | 1]` but with the spaces on the left. but I don't have a good idea yet

**Comment by Blingoose** [comment]
is there any solution for this? couldn't find any answers. Ai doesn't help either. Appreciate a lot!
