### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by isavl** [weirongxu/coc-explorer#489]
Trying install with command :CocInstall coc-explorer but got error:

`
npm install exited with 127

58 verbose stack Error: command failed
58 verbose stack     at ChildProcess.<anonymous> (/home/badman/.local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
58 verbose stack     at ChildProcess.emit (node:events:394:28)
58 verbose stack     at maybeClose (node:internal/child_process:1067:16)
58 verbose stack     at Socket.<anonymous> (node:internal/child_process:453:11)
58 verbose stack     at Socket.emit (node:events:394:28)
58 verbose stack     at Pipe.<anonymous> (node:net:672:12)
59 verbose pkgid coc-explorer@0.20.0
60 verbose cwd /tmp/vyGYcY8/coc-explorer-DjD8yX
61 verbose Linux 5.13.10-1.fc35.x86_64
62 verbose argv "/usr/bin/node" "/home/badman/.local/bin/npm" "install" "--ignore-scripts" "--no-lockfile" "--production" "--legacy-peer-deps"
63 verbose node v16.5.0
64 verbose npm  v8.1.2
65 error code 127
66 error path /tmp/vyGYcY8/coc-explorer-DjD8yX
67 error command failed
68 error command sh -c run-s clean build
69 error sh: line 1: run-s: command not found
70 verbose exit 127
`
Missing space between run command and -s argument?

**Comment by weirongxu** [comment]
Can't be reproduced, it may be a problem with your nodejs or npm version or configuration, `npm install --ignore-scripts` should not execute the scripts on package.json

**Comment by weirongxu** [comment]
For your information, I'm using node v16.5.0 and npm v8.1.2 and did cache cleanup `npm clear cache --force` and still can't reproduce this error

**Comment by isavl** [comment]
Aha, my npmrc config have 3 lines:

```
prefix = ${HOME}/.local

global = true
global-style = true
```

When i delete npmrc config file coc-exlorer install without fail.

Why?

**Comment by weirongxu** [comment]
coc.nvim does not expect users to configure `global=true`, so it does not support this. I have submitted a PR to coc.nvim.
