### ISSUE TITLE
[Feature Request] Remove padding after filename column

### ISSUE THREAD

**Issue by rcarriga** [weirongxu/coc-explorer#49]
There is a large amount of white space added after the filename. I'm assuming it's there for a reason but it would be great to be able to turn it off so that columns can be added after the filename. I had a look but couldn't figure out where it is coming from.

This is an example what I'd like to have: 

![Imgur](https://i.imgur.com/ntAk7Im.png)

I have a very hacky fix [here](https://github.com/rcarriga/coc-explorer/commit/7d8593f1debd948e4fcc2d0ab3bbc9e3e51bf749) if more clarification is needed:

**Comment by weirongxu** [comment]
I have added an option `explorer.file.column.filename.paddingEnd`

**Comment by rcarriga** [comment]
Amazing thank you!
