### ISSUE TITLE
.ini files wrong indentation

### ISSUE THREAD

**Issue by Andoku** [weirongxu/coc-explorer#490]
.ini config files are shifted to the left somehow:

<img width="212" alt="Снимок экрана 2021-11-10 в 23 29 11" src="https://user-images.githubusercontent.com/669031/141188780-7359fec5-90f3-413c-807e-057aaf9b57f7.png">

**Comment by Andoku** [comment]
on second look it is the problem with .xml files, not with .ini files
<img width="226" alt="Снимок экрана 2021-11-11 в 22 57 40" src="https://user-images.githubusercontent.com/669031/141360866-f480075e-2bed-4590-994f-67d210270dcf.png">

**Comment by weirongxu** [comment]
This is `xml` icon rendering issue, probably the best solution is to use `html` icons instead of `xml` icons
