### ISSUE TITLE
floating window appear automatically when searching files by press 'f' or 'F'

### ISSUE THREAD

**Issue by alps2006** [weirongxu/coc-explorer#492]
If setting `--position floating` ,  i can't search files by exploreFiles for the floating window show automatically.

**Comment by alps2006** [comment]
![1](https://user-images.githubusercontent.com/4474770/144225777-1860c4da-8d36-40fe-89c2-31bb6a7a861e.gif)

**Comment by weirongxu** [comment]
Check out the `explorer.floating.hideOnCocList` option in `readme.md`

**Comment by weirongxu** [comment]
I have reproduced this issue.

**Comment by weirongxu** [comment]
Should fixed on latest version of coc-explorer
