### ISSUE TITLE
preview action failed in vim8 

### ISSUE THREAD

**Issue by kayw** [weirongxu/coc-explorer#495]
*il* in vim8 not work
with `call win_execute(a:ctx.winid, 'set filetype=coc-explorer-labeling'] Vim(call):E116: Invalid arguments for function win_execute Error ` in CocInfo

https://github.com/weirongxu/coc-explorer/blob/a3800cafd9534e1c99ef4f3ca55fca0ea18f19e1/src/floating/floatingWindow.ts#L84

this line should add ')' after 'set filetype=${options.filetype}'

**Comment by weirongxu** [comment]
Thank you very much, I fixed and released a new version.
