### ISSUE TITLE
Floating file information popup box not working.

### ISSUE THREAD

**Issue by AGou-ops** [weirongxu/coc-explorer#498]
my coc-explorer config is default.
- os: macos 12.1
- nvim version: 0.6

It didn't show file information popup box:

![image](https://user-images.githubusercontent.com/57939102/147715955-e09dce69-c10a-4822-a949-7b8d4630b10f.png)

I want this: [https://github.com/weirongxu/coc-explorer#screenshot](https://github.com/weirongxu/coc-explorer#screenshot)

Did I ignore some options?

**Comment by weirongxu** [comment]
You should use `il` mapping or the `explorer.previewAction.onHover` configuration
