### ISSUE TITLE
Option to hide buffers 

### ISSUE THREAD

**Issue by Rizhiy** [weirongxu/coc-explorer#502]
**Is your feature request related to a problem? Please describe.**
I have a separate plugin for managing buffers, so would like to hide them completely.

**Describe the solution you'd like**
Config option to change which roots are available.
Currently, I just want to hide buffers, but having other folders (such as python packages) would be useful as well.

**Describe alternatives you've considered**
I checked if such option exists already, but looks like it is missing.
Docs are quite difficult to search.

**Additional context**
N/A

**Comment by weirongxu** [comment]
Try "explorer.sources" option in `coc-settings.json`, or command options https://github.com/weirongxu/coc-explorer#--sources-sources

**Comment by Rizhiy** [comment]
That works, thank you.
