### ISSUE TITLE
Enable search with `omitCenter` enabled

### ISSUE THREAD

**Issue by Rizhiy** [weirongxu/coc-explorer#505]
**Is your feature request related to a problem? Please describe.**
When `omitCenter` is enabled, searching for files using default vim search doesn't work.

**Describe the solution you'd like**
Vim search works with `omitCenter`

**Describe alternatives you've considered**
I tried putting the full filename at the end of the template, but this just caused the original to disappear.

**Additional context**
Some ideas:

* Keep original name after shortened name, but don't take it into account when calculating width.
* With fancy fonts enabled perhaps it is possible to change hidden characters to zero-width, so they can still be searchable?
* Somehow detect when user is searching and expand all filenames?

**Comment by weirongxu** [comment]
I suggest is using the search action (Default mapping to `F`) to find the file name, and you can use the `preview:labeling` (maping `il`) action to view more information about the file.

**Comment by weirongxu** [comment]
This part of the feature is really missing a lot of documentation, I will think about how to improve it later. In addition, there are actually two modifiers called `omitLeft` and `omitRight` used to ignore different positions.

**Comment by Rizhiy** [comment]
Thanks, didn't know there was a separate search.
