### ISSUE TITLE
How to open file on the right ?

### ISSUE THREAD

**Issue by linrongbin16** [weirongxu/coc-explorer#510]
Hi, I'm new to coc-explorer, when I use `:CocCommand explorer<CR>` to open explorer the first time, it's 40 width on the left. like this:
![image](https://user-images.githubusercontent.com/6496887/152647189-4b923ae9-011a-4dd9-afd7-39a4fb9b3ed7.png)

Then I type `<C-w>l` to move cursor from coc-explorer window to right (No Name buffer). Then I type `:q` to quit buffer, then I select some file and open with `<CR>`, then this file is opened on the left, but I want to open it on the right, just like the first No-Name buffer:

![image](https://user-images.githubusercontent.com/6496887/152647275-af0001cc-0f8c-4156-9f5a-6f116d269d39.png)

How should I do that?

**Comment by weirongxu** [comment]
`:set splitright`

**Comment by linrongbin16** [comment]
hi @weirongxu , `set splitright` seems a global vim option. I dont want to change this global. is there an option or command to do this?

**Comment by weirongxu** [comment]
Not supported, may need to refactor `openAction.strategy` to add `botright vsplit` or something like that

**Comment by weirongxu** [comment]
If you think this feature is important, you can create a feature issue

**Comment by linrongbin16** [comment]
Hi, @weirongxu , I think maybe I describe my needs in a wrong way.

Actually when coc-explorer is the only window in vim, and I open a text file with `<CR>`. the new-opened file window is on the left (default) or on the right (use `:set splitright`). Then the coc-explorer window width is equal to the new-opened file window width. like this:

![image](https://user-images.githubusercontent.com/6496887/152683817-ef669221-fb25-4231-89b0-f537106a1481.png)

But  I want coc-explorer always stay in width 40, just like nerdtree. How should I configure coc-explorer to do this?
