### ISSUE TITLE
[BUG] Jump to definition always opens in coc-explorer split

### ISSUE THREAD

**Issue by Rizhiy** [weirongxu/coc-explorer#512]
**Describe the bug**
When using jump to definition, definition always opens in coc-explorer

**Result from CocInfo**

```
    7 ## versions
    6
    5 vim version: NVIM v0.6.0
    4 node version: v12.22.7
    3 coc.nvim version: 0.0.80-76309a76e7
    2 coc.nvim directory: /home/rizhiy/.vim/plugged/coc.nvim
    1 term: tmux-256color
  8   platform: linux
```
extensions:
```
  * coc-html 1.6.1 ~/.config/coc/extensions/node_modules/coc-html
  * coc-floaterm 0.2.2 ~/.config/coc/extensions/node_modules/coc-floaterm
  * coc-explorer 0.22.4 ~/.config/coc/extensions/node_modules/coc-explorer
  + coc-yaml 1.6.1 ~/.config/coc/extensions/node_modules/coc-yaml
  + coc-pyright 1.1.219 ~/.config/coc/extensions/node_modules/coc-pyright
  + coc-json 1.4.1 ~/.config/coc/extensions/node_modules/coc-json
  + coc-css 1.3.0 ~/.config/coc/extensions/node_modules/coc-css
 ```

**Steps to reproduce**
I guess install extensions, open python file and use jumpDefinition (`gd` by default`)

**Expected behaviour**

Definition opens in the same split as original file

**Screenshots**

**Additional context**
This started happening after I updated extensions recently, before that I updated extensions about a month ago.

Not sure whether this bug in `coc-explorer` or another extension.

**Comment by weirongxu** [comment]
I can't reproduce with the same version, maybe caused by other vim plugins

**Comment by Rizhiy** [comment]
Ok, I will try to check if it's a weird extension interaction.

BTW, I noticed that it only happens when there are multiple options for definition.
It works properly if only one definition is available, but if multiple are available and I have to choose, the bug occurs.

**Comment by weirongxu** [comment]
https://github.com/neoclide/coc.nvim/issues/3630

**Comment by jkgithubrep** [comment]
> Ok, I will try to check if it's a weird extension interaction.
> 
> BTW, I noticed that it only happens when there are multiple options for definition. It works properly if only one definition is available, but if multiple are available and I have to choose, the bug occurs.

@Rizhiy I have the same issue. Have you identified the origin of the bug from your side?

**Comment by Rizhiy** [comment]
See issue linked by @weirongxu
