### ISSUE TITLE
[Feature] How to replace the default key mapping?

### ISSUE THREAD

**Issue by ehyyoj** [weirongxu/coc-explorer#513]
Now I want to use `s` to `vsplit` file. And I try to set `map s :vsplit` in `.vimrc` or set 
```
explorer.keyMappings: {
    "s": "open:vsplit"
}
```

But neither work, pls help

**Comment by weirongxu** [comment]
use explorer.keyMappings.global instead of the explorer.keyMappings, install `coc-json` for better experience in json, please

**Comment by ehyyoj** [comment]
It worked, thanks a lot!
