### ISSUE TITLE
How to run CocExplorer commands without keybindings?

### ISSUE THREAD

**Issue by ic-768** [weirongxu/coc-explorer#526]
I want to run copyRelativePath from inside a vim function and can't figure out how to do it.
So far I can only use it with a keybinding like so

```
"explorer.keyMappings.global": {
  "L":"copyRelativeFilepath"
},
```

How can I run it from a vim function like this one (assuming my cursor is on a directory in coc-explorer) ?

```
"Doesn't work
function! CopyPath()
  let path = CocAction('runCommand', 'explorer.copyRelativeFilepath')
endfunction
```

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/wiki/Vim-API#explorerdoaction

**Comment by weirongxu** [comment]
```
:call CocActionAsync('runCommand', 'explorer.doAction', 0, ['copyRelativeFilepath'])
```

**Comment by ic-768** [comment]
> ```
> call CocAction('runCommand', 'explorer.doAction', 0, ['copyRelativeFilepath'])
> let path = getreg('"')
> ```

Thanks!
