### ISSUE TITLE
Show warnings in coc-eplorer

### ISSUE THREAD

**Issue by BabyShodan** [weirongxu/coc-explorer#531]
<img width="218" alt="Screenshot 2022-06-30 at 19 37 25" src="https://user-images.githubusercontent.com/72989195/176731356-08399517-4f2f-4084-a419-4bdc22adbd5e.png">

Me need help with my question. How can i add warnings next after errors in my coc-explorer with coc diagnostics?

**Comment by weirongxu** [comment]
You could use the template to change the view of explorer.

https://github.com/weirongxu/coc-explorer#--file-child-template-template

or `explorer.file.child.template` of [Configuration](https://github.com/weirongxu/coc-explorer#configuration)
