### ISSUE TITLE
[Feature] Buffer wipeout (bwipeout)

### ISSUE THREAD

**Issue by MajorZiploc** [weirongxu/coc-explorer#533]
The ability to close open buffered from the buffer view would be really nice.

Then being able to bind the functionality to a user defined button in the config aswell.

Example: pressing 'x' while on a buffer in the buffer nav would close said buffer

**Comment by weirongxu** [comment]
Do you mean the custom mappings?

https://github.com/weirongxu/coc-explorer#custom-mappings-example

**Comment by MajorZiploc** [comment]
right, the custom mappings. I just dont see a mapping to allow for bwipeout

**Comment by weirongxu** [comment]
Use dF to `bwipeout` the buffer.

```json
{
 ....
   "df": "delete",
   "dF": "deleteForever",
....
}
```

You can list the explorer action by press `?` in buffer source.

**Comment by MajorZiploc** [comment]
ah i see. sorry. i did see those choices but just assumed they would delete the files without trying it out.

Thank you!
