### ISSUE TITLE
[Feature] Is there a way to make the icons bigger?

### ISSUE THREAD

**Issue by npearson72** [weirongxu/coc-explorer#536]
**Is your feature request related to a problem? Please describe.**
I would like to increase the icons to be larger... similar to vs code.

Here is how icons look in vim with coc-explorer

<img width="328" alt="Screen Shot 2022-08-06 at 9 22 44 PM" src="https://user-images.githubusercontent.com/1323414/183275201-5c553cde-284f-4df9-881a-a81876dc7c29.png">

Here's what the icons look like in vs code (notice there's extra line height too)

<img width="185" alt="Screen Shot 2022-08-06 at 9 26 03 PM" src="https://user-images.githubusercontent.com/1323414/183275271-bdb9dd79-792b-4474-86fa-bfc9d3799354.png">

Is there currently a setting to increase their size or can this be done as a feature request?

**Comment by weirongxu** [comment]
In the terminal, nvim can not control the width of the characters, generally this depends on the width of the nerdfont font, for example, you can try the nerdfont with `double-width`. https://github.com/ryanoasis/nerd-fonts#features
