### ISSUE TITLE
Windows Terminal: Cursor keeps moving to the bottom of buffer, or to next parent node

### ISSUE THREAD

**Issue by nbn22385** [weirongxu/coc-explorer#537]
Issue when using Windows Terminal + PowerShell **only**.

Is there a custom keymapping I can set to overcome the behavior? If this is out of scope of coc-explorer please close the issue.

So far I have 3 examples of this behavior:

- When pressing `l` or `o` on the "after" folder, the cursor is moved to the "pack" folder, and I have to move back up to access any of "after"'s children.

   ![image](https://user-images.githubusercontent.com/5347925/185417698-714a3d34-7898-46d3-8e56-a734305a75c8.png)

- When pressing `<cr>` on the "after" folder, the cursor is moved to the last item in the folder

   ![image](https://user-images.githubusercontent.com/5347925/185416515-f27775b6-a2ae-441e-8809-48c234dbca3b.png)

- When pressing `?` to access the help page, the cursor is moved to the bottom

   ![image](https://user-images.githubusercontent.com/5347925/185416847-f7fd3e06-9c40-48d0-95c8-8607b4a70b8c.png)

I still have the behavior when disabling all other plugins, mappings, and autocommands.

`:verbose map l` in coc-explorer produces:
```
n  l            @<Plug>(coc-explorer-key-n-l)
        Last set from ~/.config/coc/extensions/node_modules/coc-explorer/autoload/coc_explorer/mappings.vim line 13
v  l            @<Plug>(coc-explorer-key-v-l)
        Last set from ~/.config/coc/extensions/node_modules/coc-explorer/autoload/coc_explorer/mappings.vim line 13
Press ENTER or type command to continue
```

**Comment by weirongxu** [comment]
Maybe it only happens with special vim versions? I tried vim / nvim on windows terminal + powershell and didn't reproduce

**Comment by nbn22385** [comment]
Thanks for the response,

I just set up a fresh VM of Ubuntu 22.04 via Vagrant on Windows Terminal 1.14.228 and the issue is still there.

- vim (8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30))
- and then vim (9.0 (2022 Jun 28, compiled May 10 2022 08:40:37))
- coc.nvim plugin via minpac
- coc-explorer
- no other custom configuration

Then I switched over to a Git Bash terminal and the issue happens over there too, so now I don't know what to think or how else to debug the issue.

On both occasions, I am SSHing into my VM, if you think that matters.

**Comment by weirongxu** [comment]
Hmm. I still don't have an idea about this, can you provide a vimrc that can be reproduced?

**Comment by nbn22385** [comment]
I was not able to reproduce it on any other platform than a couple Ubuntu VMs on my work computer. 😞 

For what it's worth, my minimal `vimrc` looks like:

```vim
function! PackInit() abort
  packadd minpac
  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})
  call minpac#add('neoclide/coc.nvim', {'branch': 'release'})
endfunction

command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#status()

let g:coc_global_extensions = ['coc-explorer']
```

**Comment by nbn22385** [comment]
Update: I just installed my dotfiles setup on a fresh Ubuntu 22.04 docker image and the problem persisted. Then I installed my dotfiles setup on an Ubuntu 20.04 docker image and the problem did not exist. Can you try to reproduce on Ubuntu 22.04?

**Comment by nbn22385** [comment]
This seems like an environment issue on my side, so I'm going to close this one out.
