### ISSUE TITLE
Open and Close folders.

### ISSUE THREAD

**Issue by ElcomJ** [weirongxu/coc-explorer#539]
Good evening, I would like to know if there is a way for me to open and close folders using the `Enter` key, or only the `o` key does that?

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer#custom-mappings-example

**Comment by weirongxu** [comment]
Checkout the `explorer.openAction.for.directory` option from readme.

https://github.com/weirongxu/coc-explorer/issues/130
