### ISSUE TITLE
What does the X next to a filename mean??

### ISSUE THREAD

**Issue by lkj4** [weirongxu/coc-explorer#542]
Just git pushed everything and got this X next to the filename, what does it mean? I couldn't find anything in the readme...

![image](https://user-images.githubusercontent.com/84568845/189933155-29e3cd66-9a75-4f4b-b6a4-858e28c97026.png)

**Comment by weirongxu** [comment]
That's an internal clipboard, meaning the file has been cut

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer/issues/538
