### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by ymzuiku** [weirongxu/coc-explorer#543]
coc-explorer is a great explorer plugin.
Before coc-explorer, I use  NERDTree, and use `NERDTreeQuitOnOpen=1`, the option help me focus in one file, it's fun of coding.
How can i set coc-explorer, like `NERDTreeQuitOnOpen=1` ?

**Comment by weirongxu** [comment]
see https://github.com/weirongxu/coc-explorer/issues/121

**Comment by ymzuiku** [comment]
Thanks, I used this:
```
nmap <space>e :CocCommand explorer --quit-on-open<CR>
```
