### ISSUE TITLE
[Feature] Stay in coc-explorer after opening as optional setting

### ISSUE THREAD

**Issue by 205g0** [weirongxu/coc-explorer#546]
**Is your feature request related to a problem? Please describe.**
I often open many files at the same time and with the current version, I have to go back to the coc-explorer pane every time.

**Describe the solution you'd like**
A setting that allows to let stay the cursor in coc-explorer, something like `stayInExplorerAfterOpeningAFile: true`, default is false.

**Describe alternatives you've considered**
None, yet.

**Comment by weirongxu** [comment]
```
{
   "explorer.keyMappings.global": {
    “<cr>”: "open:select:keep"
  }
}
```

**Comment by weirongxu** [comment]
You can use <kbd>&lt;tab&gt;</kbd> to list all preset action in explorer

**Comment by 205g0** [comment]
Thanks, I've put the setting above in my coc setting.json and got...
```
invalid symbol (config)
───────────────────────────────
property name expected (config)
```
...at `"<cr>"` and fwiw, the cursor is still going to the the pane.

**Comment by weirongxu** [comment]
Sorry, it's problem of my input method, I have modified the above content

**Comment by 205g0** [comment]
all good, sorry that I ask again, what should I do now? The code snippet above is still the same and the one I've added to my settings.json...

**Comment by weirongxu** [comment]
Actually, they are different, you can check out my edit records

**Comment by 205g0** [comment]
ah ok, you are right!! Now, there's no error anymore in the editor. But still, after restarting nvim, the cursor goes to the pane with the opened file and won't stay in the coc-explorer pane

**Comment by weirongxu** [comment]
Try using <kbd>enter</kbd> to open the file.

**Comment by 205g0** [comment]
Great and of course! Thanks. 🙂

One more thing if I press too fast `l` and `b` (opening a file and putting in into pane b), coc-explorer go away and I see a list of file sizes in the coc-explorer pane:

```
                531 B
              4.63 kB
                 96 B
                226 B
              1.11 kB
...
```
