### ISSUE TITLE
[Feature] How to turn off the function of "Enter" to switch the root directory

### ISSUE THREAD

**Issue by x93008** [weirongxu/coc-explorer#549]
**Is your feature request related to a problem? Please describe.**
I used to use the "nerdtree" plug-in, but now I want to keep some habits. I like to use the Enter key to open or collapse the directory, which is more convenient.

**Describe the solution you'd like**
I hope you can define the functions of shortcut keys more freely

**Comment by weirongxu** [comment]
You can change the `explorer.root.strategies` configuration, because this configuration will use coc workspace by default, and the workspace will switch automatically with coc.

https://github.com/weirongxu/coc-explorer#--root-strategies-root-strategies
