### ISSUE TITLE
Replacing coc explorer buffer

### ISSUE THREAD

**Issue by leosmaia21** [weirongxu/coc-explorer#551]
Hello, 
Is there any way of preventing coc explorer  from being replaced by another buffer? I am using the nvimgdb and sometimes i am in the explorer buffer and open accidentally the plugin inside of explorer.

Thank you

**Comment by weirongxu** [comment]
I think this should be implemented on nvim-gdb to avoid opening nvimgdb on some readonly buffer, or on some filetypes.
