### ISSUE TITLE
[Bug]: Up motion (k) behaving strangely

### ISSUE THREAD

**Issue by willdavidow** [weirongxu/coc-explorer#56]
I just noticed when I couple the up motion, `k`, with a number, e.g. `9k`, it goes down instead of up. Single movements work just fine, and `9j` to go down 9 lines works just fine as well...

I checked the mapping for `k` in `coc-explorer` and it showed

```
n  k                     @<Plug>(coc-explorer-action-n-k)
```

I haven't customized anything other than the following items related to `coc-explorer`:

```
"explorer.quitOnOpen": true,
"explorer.icon.enableNerdfont": true,
"explorer.icon.enableVimDevions": true,
```
Is there something I'm missing - or do I have some kind of setting messed up somewhere? I checked over my init.vim file and I don't have any mappings set for `k`, so I'm at a loss as to what could be causing this issue other than a bug of some sort.

**Comment by weirongxu** [comment]
Fixed, please upgrade `coc.nvim` and `coc-explorer`
