### ISSUE TITLE
[Feature] search full project

### ISSUE THREAD

**Issue by jackielii** [weirongxu/coc-explorer#562]
**Is your feature request related to a problem? Please describe.**

When I'm at the explorer buffer, I often want to jump to some file, I want to search the whole workspace a file. I used `F` to search recursively but it only searches current node.

**Describe the solution you'd like**

I have coc config:

```
    "F": ["cd:$workspaceRoot", "wait", "searchRecursive"]
```
But the "$workspaceRoot" part obviously didn't work. Is this supported? Is there an variable I can put here?

**Describe alternatives you've considered**

**Additional context**

**Comment by weirongxu** [comment]
``` 
"explorer.keyMappings.global": {
    "F": ["resolveRoot", "gotoSource:file", "searchRecursive"]
 },
```
