### ISSUE TITLE
[Question] 如何自定义action

### ISSUE THREAD

**Issue by zgpio** [weirongxu/coc-explorer#564]
如何自定义action，比如我想在目录树的某个节点执行此action，能够获取此节点的一些基础信息，比如节点路径等等

**Comment by weirongxu** [comment]
参考 readme 里 `init_explorer` 函数的例子 https://github.com/weirongxu/coc-explorer#example-by-vim-api-and-event-hooks

`explorer.getNodeInfo` 的文档在 wiki 里 https://github.com/weirongxu/coc-explorer/wiki/Vim-API
