### ISSUE TITLE
Can't enable icons 无法使用图标

### ISSUE THREAD

**Issue by huanmoon** [weirongxu/coc-explorer#577]
I'm trying to enable icons by adding "explorer.icon.enableNerdFont": true      in coc-settings.json, but it doesn't work and it warned “Property explorer.icon.enableNerdFont is not allowed. (json) "

我正在尝试使用图标功能，在coc-settings里加入了"explorer.icon.enableNerdFont": true 但没用，警告Property explorer.icon.enableNerdFont is not allowed. (json) 
![image](https://github.com/weirongxu/coc-explorer/assets/63947748/35e8c44d-4f1d-4b60-b360-63fc559572bf)

**Comment by weirongxu** [comment]
使用 `:CocConfig` 命令来确认当前位置是不是正确的 coc-settings.json 所在位置。

**Comment by huanmoon** [comment]
> 使用 `:CocConfig` 命令来确认当前位置是不是正确的 coc-settings.json 所在位置。

确实是正确的位置，我还在配置里加了"explorer.openAction.strategy": "tab"，也能正常使用，没有警告，就是图标不行

**Comment by weirongxu** [comment]
正确的 settings key 应该是 `explorer.icon.enableNerdfont` 而不是 `explorer.icon.enableNerdFont`，建议尽量使用补全来输入 key。

**Comment by auqf** [comment]
还需要安装图标
