### ISSUE TITLE
Open on vim enter

### ISSUE THREAD

**Issue by kristijanhusak** [weirongxu/coc-explorer#58]
Hello,
how can I set explorer to open up automatically when i open vim?

I tried this:
```vimL
  autocmd User CocNvimInit :CocCommand explorer<CR>

```
But it returns `[coc.nvim] Command: explorer<CR> not found`

**Comment by weirongxu** [comment]
No need the `<CR>`?
Try this
```
autocmd User CocNvimInit :CocCommand explorer
```

**Comment by kristijanhusak** [comment]
What a rookie mistake. Thanks!

**Comment by linrongbin16** [comment]
hi @weirongxu , is it available to open coc-explorer synchronizely, just like nvim-tree.lua and nerdtree ?
I have tried `autocmd User CocNvimInit :CocCommand explorer`, it's asynchronizely opened coc-explorer after vim start.

**Comment by weirongxu** [comment]
> hi @weirongxu , is it available to open coc-explorer synchronizely, just like nvim-tree.lua and nerdtree ? I have tried `autocmd User CocNvimInit :CocCommand explorer`, it's asynchronizely opened coc-explorer after vim start.
> 
> If so, how is the first open performance?

I think this may not be possible because CocNvimInit is asynchronous,
and coc.nvim is also asynchronous when loading plugins in order to improve the speed of vim startup

**Comment by linrongbin16** [comment]
thanks for reply

**Comment by linrongbin16** [comment]
> > hi @weirongxu , is it available to open coc-explorer synchronizely, just like nvim-tree.lua and nerdtree ? I have tried `autocmd User CocNvimInit :CocCommand explorer`, it's asynchronizely opened coc-explorer after vim start.
> > If so, how is the first open performance?
> 
> I think this may not be possible because CocNvimInit is asynchronous, and coc.nvim is also asynchronous when loading plugins in order to improve the speed of vim startup

thanks for reply
