### ISSUE TITLE
key mapping

### ISSUE THREAD

**Issue by bye-byte** [weirongxu/coc-explorer#580]
coc-explorer can use j or k to move the cursor up or down, l to expand a folder or open a file, and h to collapse a folder.  Before using this plugin, I had remap hjkl in my vimrc.

> noremap j h
   noremap k j
   noremap i k

The remapping in vimrc doesn't fully work in explorer and I can't collapse the folder using j. And there is some delay when pressing i to move the cursor up. I hope to still use the customized shortcut keys for moving the cursor in Explorer. How can I set this up?

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer?tab=readme-ov-file#custom-mappings-example
