### ISSUE TITLE
[Bug]: filetypes icon display bug

### ISSUE THREAD

**Issue by iamcco** [weirongxu/coc-explorer#61]
![image](https://user-images.githubusercontent.com/5492542/70876834-24eab980-1ff6-11ea-9970-00fa80d734d7.png)

**Comment by weirongxu** [comment]
Fixed in https://github.com/weirongxu/coc-explorer/commit/47dbd0d62d9aadbc40f95681c776cbf5de37fb41
I will dump a new version
