### ISSUE TITLE
[Feature Request] Open files to specific winid without select

### ISSUE THREAD

**Issue by linjiX** [weirongxu/coc-explorer#67]
It will be very nice if the explorer can be bind with a specific window.
The file will be open to this window no matter how the window layout changes.
Normally the specific window is where to open the explorer.
Just like "Defx" and "NerdTree"

**Comment by weirongxu** [comment]
Could you point out the documentation in `Defx` and` NerdTree` for this feature?

**Comment by linjiX** [comment]
Seems there is no documentation for this feature.
But actually the default behavior of `Defx` and `NerdTree` is to open files to where it from.
Also you can use `:echo b:defx.context.prev_winid` in `Defx` window to get the binded winid.

**Comment by weirongxu** [comment]
Looks like can be implemented a new strategy,
for example `openAction.strategy = 'openExplorerFrom'`
