### ISSUE TITLE
addFile directory scope

### ISSUE THREAD

**Issue by jrock2004** [weirongxu/coc-explorer#69]
Is there a config option for when I hit a, that it scopes to the directory of the file that is open?

Example:

Folder1
  file-a.txt
Folder2
file-b.txt
file-c.txt

So if I have open `file-a.txt`, then I open explorer and hit a, I would expect that I am in the Folder1 directory but its not and its higher

**Comment by weirongxu** [comment]
It seems not feasible. If the user hasn't opened the file yet or has two files opened, then user how to know where the scope is.

**Comment by jrock2004** [comment]
I am sorry I did not comment sooner. This feature I am asking is similar to how Atom allows you add a file
