### ISSUE TITLE
[Feature/request]: preview file

### ISSUE THREAD

**Issue by casprwang** [weirongxu/coc-explorer#71]
Hi, there! I really like the extension. but I wonder if we can have a `preview file` feature. 

I often found my self peeking files without editing intention, so I tend to keep the cursor within explorer sidebar. 

One simple way to achieve this is to bind a macro for opening file and jump back to explorer, similarly as `go` in nerdtree([doc](https://github.com/preservim/nerdtree/blob/master/doc/NERDTree.txt#L250)). Or, maybe we can spawn a floating window after the cursor stop at a file in the explorer.

I would like to hear your thoughts, thanks!

**Comment by weirongxu** [comment]
I think both can be implemented

**Comment by wangsongiam** [comment]
great, I haven't delved into the code, but I'd love to start helping. Where do you think I can start with?

**Comment by weirongxu** [comment]
If you want to contribute code, you can learn from these `actions`

https://github.com/weirongxu/coc-explorer/blob/5219e78aa87ff9fa7cbe57fedf111338ab939499/src/explorer.ts#L73-L177

and

https://github.com/weirongxu/coc-explorer/blob/dbbf7878aaee4e3afe9825ea2c398888ac5c6e09/src/source/sources/file/file-actions.ts#L83-L103

**Comment by cabaalexander** [comment]
Did this feature got implemented ? :eyes:

**Comment by cabaalexander** [comment]
oh, wait II thought this was a close issue but it was the #197 :sweat_smile: Sorry my bad. I will keep an eye on this. Never mind what I said. :walking_man:

**Comment by weirongxu** [comment]
```
    "il": "preview:labeling",
    "ic": "preview:content",
    "Il": "previewOnHover:toggle:labeling",
    "Ic": "previewOnHover:toggle:content",
    "II": "previewOnHover:disable",
```
Implemented in latest version

**Comment by yutakatay** [comment]
wow! great work!!
[]
![2020-12-09_17-03](https://user-images.githubusercontent.com/8683947/101601866-847c7900-3a40-11eb-8561-cc0a81ca0585.png)
(url)
