### ISSUE TITLE
Strategy "originWindow" was misspelled as "sourceWindow"?

### ISSUE THREAD

**Issue by linjiX** [weirongxu/coc-explorer#72]
Seems the strategy "originWindow" was misspelled as "sourceWindow" in `packet.json` and `readme.md`

**Comment by weirongxu** [comment]
typo, should be sourceWindow

**Comment by linjiX** [comment]
But it is still "originWindow" in file `src/source/source.ts` and `src/util/config.ts`.

**Comment by weirongxu** [comment]
> But it is still "originWindow" in file `src/source/source.ts` and `src/util/config.ts`.

Sorry, fixed now.

**Comment by weirongxu** [comment]
I also have added a vim variable, `b:coc_explorer_context` in explorer buffer.

**Comment by linjiX** [comment]
Wow, it helps a lot, thanks.
