### ISSUE TITLE
Key "expand" can open a file, but "expandOrCollapse" cannot?

### ISSUE THREAD

**Issue by linjiX** [weirongxu/coc-explorer#73]
Key "expand" can expand folder or open a file,
But key "expandOrCollapse" can expand or collapse folder, but not open a file?

**Comment by weirongxu** [comment]
Indeed, `expand` is inconsistent, I need to refactor some logic of actions to allow custom maps to determine whether the current node is a folder or file.

If you want to use `expandOrCollapse` with `open` for now, you can set `explorer.openAction.changeDirectory` to false, and map your key to `open`.

**Comment by daGrevis** [comment]
So for now I had to do this:

```
call coc#config('explorer', {
      \ 'keyMappings.<cr>': 'open',
      \ 'openAction.changeDirectory': 0,
      \ 'quitOnOpen': 1,
      \ })
```

It will map `Enter` key to either:

a) toggle the directory
b) open the file and close coc-explorer

**Comment by weirongxu** [comment]
Use `["expandable?", "Expand", "open"]` instead of the before `expand` logic

**Comment by linjiX** [comment]
Cool, I can use `"<CR>": ["expandable?", "expandOrCollapse", "open"]` to get what I want.
Thanks~
