### ISSUE TITLE
[Bug] Nerdfont icons appearing as question marks

### ISSUE THREAD

**Issue by unknownbreaker** [weirongxu/coc-explorer#74]
![image](https://user-images.githubusercontent.com/6026454/71931439-be2b6c80-316b-11ea-9be1-3600faf4c235.png)

Have already followed instructions for installing nerdfont.
```
brew tap homebrew/cask-fonts
brew cask install font-hack-nerd-font
```

**Comment by weirongxu** [comment]
""
Try copying this character into your Vim buffer or Terminal

**Comment by weirongxu** [comment]
Also, have you set the Terminal font to "Hack Bold Nerd Font Complete"

**Comment by unknownbreaker** [comment]
Changing the iTerm font fixed it. Thanks!
