### ISSUE TITLE
cd action is not changing vim working directory 

### ISSUE THREAD

**Issue by jg-rc** [weirongxu/coc-explorer#75]
when i'm over a directory and i hit tab then i select cd, the folder tree root changes successfully to the actual folder but when i check the current working directory in vim, it stays unmodified. 
NerdTree cd command does it in that way so i thought that would be a nice a feature in coc-explorer

**Comment by HawkinsT** [comment]
Sadly this commit doesn't seem to fully handle edge cases, e.g. starting vim and then typing `:cd ~` will change the coc-explorer directory, but `autocmd VimEnter * cd ~` (for example) won't change the coc-explorer directory.

**Comment by weirongxu** [comment]
> Sadly this commit doesn't seem to fully handle edge cases, e.g. starting vim and then typing `:cd ~` will change the coc-explorer directory, but `autocmd VimEnter * cd ~` (for example) won't change the coc-explorer directory.

`:cd` never change the explorer directory
