### ISSUE TITLE
Use "/" to search will mess the display

### ISSUE THREAD

**Issue by linjiX** [weirongxu/coc-explorer#77]
If using vim's default search method `/` in explorer window.
The display of the explorer will be messed, seems the indentation goes wrong.
Here is the snapshot:
![截屏2020-01-14上午10 55 32](https://user-images.githubusercontent.com/46097255/72310415-ac425000-36bc-11ea-8761-ebbede4e2ac9.png)

**Comment by weirongxu** [comment]
It seems a bug when vim displays conceal. Recently I was researching using `nvim_buf_add_highlight` and `textprop` to replace the `conceal`.

**Comment by weirongxu** [comment]
Solved in the develop branch
