### ISSUE TITLE
Error message appears when execute "CocCommand explorer --reveal"

### ISSUE THREAD

**Issue by linjiX** [weirongxu/coc-explorer#80]
When adding `--reveal` flag,
Below error message appears:
```
[coc.nvim] Error: ENOENT: no such file or directory, scandir '--reveal'
```

**Comment by weirongxu** [comment]
reveal flag should be used with file path

--reveal path/to/file

**Comment by linjiX** [comment]
But the `README.md` says `--reveal` has default value, which is `current buffer`.

Also I add a file path after `--reveal`, but seems it doesn't work at all.

**Comment by weirongxu** [comment]
> Also I add a file path after --reveal, but seems it doesn't work at all.

This should be a bug of `autoReveal`

> PS. explorer.file.autoReveal is set to false

Do you need explorer not reveal file path automatically, but reveal to a directory when open?

**Comment by linjiX** [comment]
Yes I do not like reveal file automatically.
In fact, I prefer to reveal file path only when it is necessary.
It will be very helpful if there is a command to trigger the "reveal" move.

**Comment by NullVoxPopuli** [comment]
why was this closed? I'm having this issue
