### ISSUE TITLE
[Bug]: Setting `explorer.file.hiddenRules` is not work

### ISSUE THREAD

**Issue by StrayDragon** [weirongxu/coc-explorer#85]
Hello, thanks for developing this extensions for `coc.nvim` , it's powerful and easy to use. :+1: 

However, a problem that is inconsistent with the [README Configuration](https://github.com/weirongxu/coc-explorer#configuration) bothers me,
the `explorer.file.hiddenRules` should have expected `Object` (Like the default values ​​given below) 
and not `boolean`, but the type checker is set to `boolean`: 

![DeepinScreenshot_select-area_20200118230831](https://user-images.githubusercontent.com/26061593/72665882-ba3efa80-3a47-11ea-87f6-ef56b393b48c.png)

In addition, I want to hidden the `__pycache__` folder in my workspace, but it doesn't seem to work.

Could you further describe its "patternMatches" grammar or link some data in the README?

**Comment by weirongxu** [comment]
`patternMatches` just a regular expression for the file name. If you want filter file name, you should write it in `filenames`

**Comment by StrayDragon** [comment]
@weirongxu Thank you for explaining this:smile:. But today I found another problem, this option seems to take effect only in the global configuration (`:CocConfig`) , and the local configuration (`:CocLocalConfig`) is not work...

**Comment by weirongxu** [comment]
Maybe is issue of coc.nvim  https://github.com/neoclide/coc.nvim/issues/1460
