### ISSUE TITLE
Wants always open explorer

### ISSUE THREAD

**Issue by bigzhu** [weirongxu/coc-explorer#89]
How to set default open explorer when open new file

**Comment by weirongxu** [comment]
You mean open explorer when open vim first time?

**Comment by bigzhu** [comment]
Yes, or open new vim tab

**Comment by adamki** [comment]
wouldalso love to have an option to have Coc-Explorer open instead of NETRW

**Comment by yutakatay** [comment]
https://github.com/weirongxu/coc-explorer/issues/123

**Comment by yutakatay** [comment]
workaround

```vim
augroup MyCocExplorer
  autocmd!
  autocmd VimEnter * sil! au! FileExplorer *
  autocmd BufEnter * if isdirectory(expand('%')) | bd | exe 'CocCommand explorer ' . expand('%') | endif
augroup END
```

**Comment by daGrevis** [comment]
Here's what I have come up with:

```viml
let g:loaded_netrw = 1

function! AuCocNvimInit()
    if @% == '' || @% == '.'
      exe ':CocCommand explorer'
    endif
endfunction
autocmd User CocNvimInit call AuCocNvimInit()
```

**Comment by burgessa23** [comment]
I use Startify.vim, so I added the following to that plugin's `VimEnter` call: 

```
function! s:explore()
  sleep 350m
  call execute('CocCommand explorer')
endfunction
```
(the sleep is needed to ensure explorer sources are loaded)

This way it loads automatically for whatever directory I'm in when I open a new session, but only on a new session

**Comment by weirongxu** [comment]
> @burgessa23 
> I use Startify.vim, so I added the following to that plugin's `VimEnter` call:
> 
> ```viml
> function! s:explore()
>   sleep 350m
>   call execute('CocCommand explorer')
> endfunction
> ```
> 
> (the sleep is needed to ensure explorer sources are loaded)
> this should work anywhere, just call it via: `call s:explore()`
> 
> This way it loads automatically for whatever directory I'm in when I open a new session, but only on a new session

Use the `CocExplorerOpenPost` event

`autocmd User CocExplorerOpenPost call <SID>opened_explorer()`

**Comment by burgessa23** [comment]
@weirongxu I tried adding `autocmd User CocExplorerOpenPost call <SID>opened_explorer()` to init.vim, but I get an error: `Unknown function: <SNR>1_opened_explorer` and I still get the missing sources error if I remove `sleep 350m`

**Comment by weirongxu** [comment]
@burgessa23 

> @weirongxu I tried adding `autocmd User CocExplorerOpenPost call <SID>opened_explorer()` to init.vim, but I get an error: `Unknown function: <SNR>1_opened_explorer` and I still get the missing sources error if I remove `sleep 350m`
> 
> seems like it can't find `opened_explorer()` to map it

Sorry, my above understanding is incorrect.

The `autocmd User CocNvimInit CocCommand explorer` is work fine for me

**Comment by weirongxu** [comment]
> This way it loads automatically for whatever directory I'm in when I open a new session, but only on a new session

Sorry, the above is my misunderstanding, you should use `SessionLoadPost` event

**Comment by bigzhu** [comment]
If I want auto open explorer in all python file , just add this config to ftplugin/python.vim file 
```
"auto open explorer
exe ':CocCommand explorer --no-toggle --no-focus'
```

**Comment by Dev-Addict** [comment]
I use the code below to auto open the coc explorer and then change the focus to the other window.

```
au VimEnter * CocCommand explorer
au User CocExplorerOpenPre wincmd p
```

note that this will change the focus on the other window every time that you open the coc explorer even in the middle of working with vim not just at the start.
