### ISSUE TITLE
why is my filename error code ? 

### ISSUE THREAD

**Issue by livmortis** [weirongxu/coc-explorer#90]
^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|--
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|>
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|⚠
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|⚠
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|⚠
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|⚠
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|⚠
   ^A11^B  ^C11^D^A97^B^A109^B  ^C109^D^|⚠
~                                       |  ~
~                                       |  ~
~

my tree file name are codes above,  i'dont know what's the problem
thanks

**Comment by weirongxu** [comment]
Are you use the `indentLine.vim`? https://github.com/weirongxu/coc-explorer/issues/44

**Comment by Jinlixian** [comment]
I have this problem, too

**Comment by weirongxu** [comment]
Solved in the develop branch

**Comment by yyn19951228** [comment]
Thank you for solving the issues in the dev? 
May I ask if the dev is released? 
I installed by using `CocInstall`, and still got the same problem.

I am using Vim8.1.1312, using coc0.0.74, here is the screenshot



<img width="1028" alt="Screen Shot 2020-02-15 at 10 06 09 PM" src="https://user-images.githubusercontent.com/12838556/74598427-5fe18b80-503f-11ea-90da-b9f96c85aff4.png">

**Comment by weirongxu** [comment]
> Thank you for solving the issues in the dev?
> May I ask if the dev is released?
> I installed by using `CocInstall`, and still got the same problem.
> 
> I am using Vim8.1.1312, using coc0.0.74, here is the screenshot
@yyn19951228 If you really want to try the develop version, you should install it from develop branch. Check out https://github.com/weirongxu/coc-explorer/tree/develop and https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension
