### ISSUE TITLE
Feature Request - Move cursor multiple nodes at a time

### ISSUE THREAD

**Issue by s-taylor** [weirongxu/coc-explorer#91]
`j/k` map to `NodeNext/NodePrevious`, but it doesn't allow repeats.
In Nerdtree I used to use `5j` and `5k` to jump up and down the list quicker.
Is it possible to implement this in coc-explorer? or is there are better way to quickly navigate the explorer pane? I know you can use `H/M/L` but looking for smaller increments than half page jumps.

**Comment by weirongxu** [comment]
Update `coc.nvim` to the latest

**Comment by s-taylor** [comment]
Ah awesome, thankyou!
