### ISSUE TITLE
Error: Explorer sources not initialized yet

### ISSUE THREAD

**Issue by Dammic** [weirongxu/coc-explorer#92]
Hey,

I've recently came across an annoying problem which didn't for sure occur a few versions back.

I have set 'autocmd vimenter * CocCommand explorer' in nvim to start up the explorer as soon as I open vim window. Most of the times I'm a bit fast, and if I try to move around the explorer too quickly (ex. going down with j, try launching vim with 'j' already pressed), coc throws this error and prevents me from doing anything within the explorer.
I've attached the screenshot with the problem:
![Screenshot 2020-02-11 at 07 25 57](https://user-images.githubusercontent.com/18100361/74215137-58695d80-4ca0-11ea-953c-14ff46141398.png)

**Comment by weirongxu** [comment]
I reproduced it, Seems that mappings are not registered

**Comment by jiangjianshan** [comment]
@weirongxu,  I have just meet this problem when I first time to open coc-explorer, but second time it will be OK. What you said mappings are not registered and how to solve this problem?

**Comment by weirongxu** [comment]
> @weirongxu, I have just meet this problem when I first time to open coc-explorer, but second time it will be OK. What you said mappings are not registered and how to solve this problem?

This bug has been fixed in the latest
