### ISSUE TITLE
[Suggest] Format preview window info

### ISSUE THREAD

**Issue by fgheng** [weirongxu/coc-explorer#93]
i think it would be better if the label is aligned

![image](https://user-images.githubusercontent.com/50551377/74240764-92c11200-4d15-11ea-869e-497bcabbb58e.png)

**Comment by fgheng** [comment]
![image](https://user-images.githubusercontent.com/50551377/74240817-ac625980-4d15-11ea-99b0-eb1eda18b142.png)

**Comment by fgheng** [comment]
sorry, i upload the picture, but it does't show

**Comment by weirongxu** [comment]
OK, But I can see the picture

**Comment by weirongxu** [comment]
Why you close this? I think it can be implemented.
