### ISSUE TITLE
[Feature request] Allow preview window to contain diagnosticError errors

### ISSUE THREAD

**Issue by alex-popov-tech** [weirongxu/coc-explorer#99]
That would be super cool to be able to hover file with errors, and by `gp` see these errors in preview

**Comment by weirongxu** [comment]
Solved in the develop branch

**Comment by alex-popov-tech** [comment]
@weirongxu sorry, I didn't found description for that, how should i call explorer to be able to see error messages in preview?

**Comment by weirongxu** [comment]
Don't worry, I will release a new version in the near future, which will be contain errors in the preview

**Comment by alex-popov-tech** [comment]
thanks @weirongxu , waiting for it :)
